// Cinematography — Module 12: Building a Cinematography Career & Final Project
export const cineCareerModule = {
  id: "cine12",
  title: "Building a Cinematography Career & Final Project",
  type: "Rich Module",
  duration: "4 hours",
  desc: "How DPs actually build careers. Reel strategy, pricing, client acquisition, union vs non-union, industry relationships, and your capstone project.",
  topics: ["Reel Strategy", "Pricing + Rates", "Client Acquisition", "Industry Relationships", "Union vs Freelance", "Capstone Project"],
  quiz: [
    { q: "A producer opens your reel and the first 5 seconds are a logo card + slow fade-in to your name. What\'s the likely result?", opts: ["Professional first impression \u2014 establishes your brand", "The producer scrubs past or clicks away; reels are evaluated in the first seconds, and any second not spent on your strongest image is a second lost", "Acceptable if the music is interesting enough", "Fine for narrative but wrong for commercial reels"], correct: 1 },
    { q: "A producer emails: \"We\'re doing a 2-day commercial in July. What\'s your rate?\" What\'s the most professional response?", opts: ["Send your highest day rate in reply to anchor high", "Ask for the scope first (days, deliverables, crew size, usage, client, location) + then quote \u2014 rate is a function of scope; quoting blind signals inexperience and leaves money on the table", "Send a mid-range rate to be safe", "Defer \u2014 say \u2018TBD after we talk\u2019"], correct: 1 },
    { q: "You\'ve been freelance for 2 years, your calendar is 40% booked at $1,500/day. A competitor is fully booked at $2,500/day. What\'s the responsible rate-raise strategy?", opts: ["Raise your rate to $2,500 immediately \u2014 perception drives demand", "Gradually raise to $1,800\u2013$2,000 as your calendar fills past 70% \u2014 rate follows demand; raising on an empty calendar typically produces an empty calendar at a higher number", "Stay at $1,500 until 100% booked", "Quote $2,500 to new clients, $1,500 to returning ones \u2014 price discrimination"], correct: 1 },
    { q: "A past director who hired you twice 18 months ago hasn\'t called. You haven\'t reached out either. What\'s the likeliest reason + the fix?", opts: ["They didn\u2019t like your work \u2014 move on", "You went silent; directors default to whoever\u2019s visible + recent \u2014 a brief, genuine check-in (not a pitch) re-enters you into their consideration set. 70% of DP repeat work comes from maintained relationships, not new ones", "They\u2019re waiting for you to send a new reel", "They\u2019ve moved on to bigger DPs \u2014 unreachable now"], correct: 1 },
    { q: "You\'re a US-based DP who\'s been consistently turned away from union productions because you\'re non-union. What does the math say about joining IATSE 600?", opts: ["Always join day 1 \u2014 union credit is a badge", "Never join \u2014 freedom is more valuable than any union benefit", "Join when you\'re being turned away from work you\'d actually take + have the IATSE-qualifying days to initiate; premature joining costs dues + locks you out of non-union work you still rely on", "Join only if a specific production sponsors you"], correct: 2 },
    { q: "You\'re pitching a narrative indie director who\'s seen your reel. They reply: \"I like your work but I\'m not sure you can handle the scale of this project.\" What response moves the needle?", opts: ["Defensive \u2014 list past projects that were similar scale", "Concrete \u2014 send 2\u20133 specific references (past producers + directors they can call) + offer to prep a free scene-specific lookbook for their script so they can see your thinking on THIS project before deciding", "Aggressive \u2014 quote a low rate to reduce their perceived risk", "Walk away \u2014 the relationship is dead"], correct: 1 },
  ],
  slides: [
    { type: "cover", module: "MODULE 12", title: "Building a", titleAccent: "Cinematography Career", subtitle: "How DPs build careers. Reel strategy, pricing, clients, relationships, union, and your capstone.", meta: "Cinematography \u00B7 Tier III \u00B7 Module 12  |  7 Slides" },
    { type: "stats", eyebrow: "WHY CAREER CRAFT MATTERS AS MUCH AS IMAGE CRAFT", title: "Most cinematographers don't fail on talent \u2014 they fail on business", intro: "The path from 'I can shoot' to 'I book consistent professional work' is almost entirely about business decisions, relationships, and sustained visibility. The camera craft is table stakes. Career craft is the differentiator.", stats: [
      { num: "5\u201310 yr", label: "typical timeline from first paid job to stable full-time cinematographer income" },
      { num: "70%", label: "of repeat work comes from past clients or colleagues \u2014 your network is your pipeline" },
      { num: "30 sec", label: "average time producer spends on a first-viewing of your reel \u2014 every frame matters" },
    ], subheading: "The 5 Career Levers a Working DP Manages", bullets: [
      "Reel: frequently updated showcase of best recent work, tailored to client type",
      "Pricing: rate that reflects value delivered; confident quoting",
      "Relationships: directors, producers, crew, colorists \u2014 treated as long-term",
      "Visibility: consistent presence online + in industry communities",
      "Craft growth: every project raises the portfolio floor",
    ] },
    { type: "grid", eyebrow: "CAREER PATHS", title: "Six realistic paths cinematographers actually take", subtitle: "None is better than the others. Pick the path that matches your temperament + local market.", items: [
      { num: "01", title: "Wedding / Event DP", desc: "High volume, $2k\u2013$8k/day, stable income. Not glamorous; reliable.", icon: "\u{1F48D}" },
      { num: "02", title: "Commercial DP", desc: "$3k\u2013$15k/day, project-based, polish-focused. Hardest to break into.", icon: "\u{1F4B8}" },
      { num: "03", title: "Narrative DP (Indie\u2014Feature)", desc: "Prestige-driven. Low day rates initially; becomes lucrative with IMDb credits.", icon: "\u{1F3AD}" },
      { num: "04", title: "Documentary DP", desc: "$800\u2013$2.5k/day, globe-trotting, story-first work. Rewarding creatively.", icon: "\u{1F50D}" },
      { num: "05", title: "Music Video / Branded Content", desc: "Stylistic, fast turnaround, $2k\u2013$8k/day, feeds into commercial + narrative.", icon: "\u{1F3B5}" },
      { num: "06", title: "Social / Creator DP", desc: "Vertical content, influencer brands, retainer work. Newer path; growing fast.", icon: "\u{1F4F1}" },
    ], footer: "Rule: most working DPs do 2\u20133 of these, not one. Diversification = resilience. Pick 1 primary + 1\u20132 adjacent." },
    { type: "principle", num: "01", title: "Your Reel \u2014 The Single Most Important Career Asset", intro: "Your reel is how you get hired. It's also how you get turned down without you knowing. Treat it as a living marketing asset, not a one-and-done project.", sectionTitle: "Building a Reel That Books Work", sections: [
      { heading: "1. Lead With Your Strongest Frame", example: "First 5 seconds should be your most distinctive image. Not an intro card. Not a slow build. Strongest frame.", note: "Producers scrub reels. If the first frame doesn't grab, the rest is never watched. Front-load brilliance." },
      { heading: "2. Keep It Short \u2014 60 to 90 Seconds Max", example: "Short reel = 60\u201390 sec. Longer reel loses attention. Showcase diversity if you want but keep each segment tight.", note: "Every second past 90 risks a click-away. Discipline of cutting 10 great shots down to 5 great shots raises quality." },
      { heading: "3. Music That Matches Your Work, Not Trend", example: "Avoid the tired corporate-epic track. Pick music that matches the emotional range of your images.", note: "Music is part of the brand. Cliche music signals amateur; interesting music signals taste." },
      { heading: "4. Tailor Versions for Different Pitch Types", example: "Narrative reel for narrative pitches. Commercial reel for commercial pitches. Don't send the same generic reel everywhere.", note: "A 45-second tailored reel beats a 90-second generic one 10 times out of 10. Producers are hiring for a specific need." },
      { heading: "5. Update Every 6\u201312 Months", example: "Remove weakest shots. Replace with newest strongest. Reel quality should always be rising.", note: "A stale 2-year-old reel signals \u2018this DP hasn't grown.\u2019 A fresh reel signals momentum. Keep yours current." },
    ], rule: "Your reel is the first + sometimes only thing a decision-maker sees. Invest more in it than in any single piece of gear." },
    { type: "comparison", eyebrow: "AMATEUR vs PROFESSIONAL CAREER HABITS", title: "Two DPs, 3 years in", subtitle: "Started at the same point. One built a sustainable career; one stalled. The difference is entirely non-creative habits.", left: { title: "Stalled DP", color: "#EF4444", items: [
      { strong: "Reel never updated after Year 1", note: "Showcases mid-quality work from 2 years ago. Clients assume current work is similar. Jobs go elsewhere." },
      { strong: "Quotes the same rate regardless of client + scope", note: "Underpriced on high-budget work, overpriced on low-budget. Loses jobs both directions." },
      { strong: "Doesn't follow up after projects \u2014 relationships go cold", note: "Had great rapport with 3 directors in Year 1. Didn't stay in touch. None rehired. Pipeline dry." },
      { strong: "No consistent online presence or portfolio site", note: "Hard to find. Referrals google them + find nothing substantial. Lost opportunities." },
      { strong: "Result: still scrambling for next gig at Year 3", note: "Talented but invisible. Career treading water. Considering a career change." },
    ] }, right: { title: "Growing DP", color: "#10B981", items: [
      { strong: "Reel updated every 6 months, tailored for 3 client types", note: "Every pitch is met with a reel that looks alive + current. Wins at the first-impression stage consistently." },
      { strong: "Rates adjusted thoughtfully based on project type + client budget", note: "High-budget gets the rate it should. Low-budget gets fair. Rate confidence reads as professional." },
      { strong: "Follows up personally 2 weeks after every project", note: "Past directors become repeat clients. Past colleagues recommend her. Pipeline self-sustains." },
      { strong: "Clean portfolio site + consistent Instagram + LinkedIn presence", note: "Easy to find + hire. Shows up first on referrals + cold discovery. Wins visibility consistently." },
      { strong: "Result: 70% calendar booked 3 months out by Year 3", note: "Stable income. Rising rates. Can choose projects. Career compounding." },
    ] }, footer: "Rule: the creative work is necessary but not sufficient. Business habits are what separate stalled + growing DPs." },
    { type: "table", title: "Your Final Project \u2014 The Cinematography Capstone", subtitle: "A complete short piece that demonstrates every technical + creative skill from this course. This is the reel-worthy artefact you take from the course.", columns: ["Deliverable", "Spec", "What It Demonstrates"], rows: [
      ["Lookbook (1 page)", "5\u20138 reference images + 3\u20135 colour palette", "Pre-production discipline + visual thinking"],
      ["Shot list (per scene)", "At minimum 10 shots. Each specifying size, lens, lighting, movement", "Planning + technical communication"],
      ["Lighting diagram (1 scene)", "Sketch showing key + fill + back + motivation", "Lighting fluency"],
      ["Final video (60\u201390 sec)", "Properly exposed, shaped lighting, intentional composition + movement", "Complete cinematography craft"],
      ["Color-graded output", "In DaVinci Resolve or comparable. Skin protected.", "Post-production awareness"],
      ["500-word reflection", "What worked, what you'd change, what you learned", "Self-awareness + growth mindset"],
      ["BTS stills (3\u20135)", "Your setup on-location + equipment + crew (if any)", "Proof of execution + behind-the-camera authenticity"],
    ], footer: "Rule: this final project is not an exercise. It should go on your actual reel. Treat it as your first piece of professional portfolio." },
    { type: "exercise", title: "Plan + Execute Your Capstone Video", intro: "The culmination of this course. A complete short piece you can show any client.", items: [
      { num: "1", copy: "Pick your subject: 60\u201390 second narrative or documentary piece with real emotional intent. One character, one location is fine.", answer: "Constraint breeds focus. Don't pick something grand. A well-executed simple idea beats a half-executed complex one. The craft is in the execution." },
      { num: "2", copy: "Complete pre-production: lookbook, shot list, lighting diagram, schedule. Treat this like a paid job.", answer: "Pre-production is 60% of the quality. If you rush this stage, nothing on shoot day will save it. Give this the time it deserves." },
      { num: "3", copy: "Shoot. Light intentionally. Compose deliberately. Move the camera only when justified. Capture clean audio.", answer: "On-set, execute the plan. When you improvise, do it from strength. Bring the lookbook + shot list to the shoot + reference them." },
      { num: "4", copy: "Edit + grade in DaVinci Resolve. Correct first, grade second. Protect skin. Export in broadcast-quality ProRes + web-ready H.265.", answer: "Post is where the piece becomes cinema. Give this stage days, not hours. Let it rest overnight + re-watch before calling it done." },
      { num: "5", copy: "Write your 500-word reflection. Honest assessment: technical wins, technical misses, creative wins, creative misses, what you'd do differently.", answer: "Growth depends on honest reflection. This document becomes your reference for the next project + accelerates your improvement curve." },
    ] },
  ],
};
