// Cinematography — Module 11: Gear Strategy & Equipment Choices
export const cineGearModule = {
  id: "cine11",
  title: "Gear Strategy & Equipment Choices",
  type: "Rich Module",
  duration: "2.5 hours",
  desc: "What to buy, what to rent, what to skip. Camera bodies at each budget tier, lighting kits, audio gear, support equipment, and the 12-month gear roadmap.",
  topics: ["Budget Tiers", "Camera Bodies", "Lens Strategy", "Lighting Kits", "Audio + Support", "12-Month Roadmap"],
  quiz: [
    { q: "The gear rule that matters most early in a cinematographer's career is:", opts: ["Buy the most expensive camera", "Own your core kit (camera, 2\u20133 lenses, basic lighting, audio) \u2014 rent everything else as jobs require. Owning everything is how DPs go broke.", "Rent everything", "Buy used only"], correct: 1 },
    { q: "For a sub-$3k budget, the best camera choice is typically:", opts: ["Cheapest DSLR", "Sony FX30, Panasonic S5 IIX, or Blackmagic Pocket 6K \u2014 each shoots real 10-bit cinema codecs at this price tier", "Phone camera", "Any webcam"], correct: 1 },
    { q: "Lighting investment should start with:", opts: ["Huge HMI", "One good key (Aputure 120D or similar), one softbox modifier, + diffusion/reflector kit \u2014 90% of looks come from one well-shaped source", "50 small LEDs", "Only practicals"], correct: 1 },
    { q: "Why is audio gear part of cinematography budgets?", opts: ["It isn't", "Bad audio kills otherwise-good footage \u2014 audiences tolerate weak image before weak sound. Every DP should own at least a shotgun + lav backup.", "Only if shooting dialogue", "Only for weddings"], correct: 1 },
    { q: "Buying used cinema gear is:", opts: ["Never safe", "Standard professional practice \u2014 cameras + lenses depreciate fast but hold performance; buying 2-gen-old gear saves 40\u201360% with no quality loss", "Risky always", "Only lenses"], correct: 1 },
    { q: "The gear mistake that bankrupts most early cinematographers is:", opts: ["Not enough gear", "Buying faster than jobs justify \u2014 financing $15k+ of gear before you have $15k+/yr of work it unlocks. Rent first, buy from profit, not hope.", "Buying used", "Sharing with others"], correct: 1 },
  ],
  slides: [
    { type: "cover", module: "MODULE 11", title: "Gear Strategy", titleAccent: "& Equipment Choices", subtitle: "What to buy, what to rent, what to skip. Cameras, lenses, lighting, audio, and the 12-month gear roadmap.", meta: "Cinematography \u00B7 Tier III \u00B7 Module 11  |  7 Slides" },
    { type: "stats", eyebrow: "WHY GEAR DECISIONS MATTER", title: "Gear doesn't make your work better \u2014 but bad gear decisions kill careers", intro: "The right kit, bought at the right time, pays for itself in jobs unlocked. The wrong kit, bought too early, locks you into debt before you have the work to support it. Most DPs go broke not from lack of talent but from gear over-reach.", stats: [
      { num: "$3k\u2013$6k", label: "realistic entry professional kit \u2014 camera, 2\u20133 lenses, basic lighting, audio, support" },
      { num: "60%", label: "of professional shoots rely on rental, not owned gear; budget-per-project includes rentals" },
      { num: "2x", label: "multiplier \u2014 your gear should unlock at least 2x its cost in annual work, or it's a liability" },
    ], subheading: "The Core Gear Mindset", bullets: [
      "Own core + reliable: what you use on 80% of jobs. Rent specialty: what you use once a year.",
      "Buy slowly. Every purchase should be justified by earned income, not aspirational future work.",
      "Skip luxury. A $6k camera that books $50k/yr beats a $25k camera that books $30k/yr.",
      "Used is professional. Cinema gear depreciates fast + holds quality; 2-gen-old saves 40\u201360%.",
      "Invest in glass before bodies. Good lenses outlast 3 camera generations + shape image more.",
    ] },
    { type: "grid", eyebrow: "CAMERA BODIES BY BUDGET", title: "What to buy at each tier \u2014 current as of 2026", subtitle: "Each tier is a complete working setup. Every camera here shoots at minimum 10-bit cinema codecs.", items: [
      { num: "01", title: "Under $2k (Entry)", desc: "Used Sony a7S III, used Panasonic GH6, or Blackmagic Pocket 4K. Real cinema codecs.", icon: "\u{1F4B5}" },
      { num: "02", title: "$2k\u2013$5k (Professional Entry)", desc: "Sony FX30, Panasonic S5 IIX, Blackmagic Pocket 6K Pro. Industry-ready.", icon: "\u{1F4B0}" },
      { num: "03", title: "$5k\u2013$10k (Working Pro)", desc: "Sony FX3, FX6, Canon C70, Blackmagic Ursa 12K. Netflix-approved.", icon: "\u{1F3AC}" },
      { num: "04", title: "$10k\u2013$25k (Mid-Market)", desc: "Sony FX9, Canon C300 III, RED Komodo. Commercial + narrative feature territory.", icon: "\u{1F3C6}" },
      { num: "05", title: "$25k+ (High-End / Rental)", desc: "ARRI Alexa Mini LF, RED V-Raptor. Rent these; buying only makes sense if they print.", icon: "\u{1F48E}" },
      { num: "06", title: "Phone / iPhone Pro", desc: "Genuinely viable for social + some commercial. ProRes + Log shooting on iPhone 15 Pro+.", icon: "\u{1F4F1}" },
    ], footer: "Rule: pick the camera that unlocks the work you're booking now, not the work you dream of. Upgrade from profit, not hope." },
    { type: "principle", num: "01", title: "The 12-Month Cinematographer Gear Roadmap", intro: "A realistic build-out for someone starting seriously. Assumes $1\u20132k/month reinvestment from paid work. If you can't do this tempo from earnings, slow down \u2014 don't finance ahead.", sectionTitle: "Month-by-Month Acquisition Priority", sections: [
      { heading: "Months 1\u20132: Core Camera + One Lens + Audio", example: "Used Sony FX30 or S5 IIX + 24\u201370 2.8 or 35mm prime + Rode NTG4+ shotgun + Zoom H5 recorder.", note: "This is a complete starter kit. You can shoot interviews, narrative, weddings at this stage. Every dollar here earns." },
      { heading: "Months 3\u20134: Lighting + Support", example: "Aputure 120D II + softbox modifier + 5-in-1 reflector + sturdy tripod + basic gimbal (Ronin RS3 Mini).", note: "Lighting unlocks better work + more money. Support gear unlocks stability. Both pay for themselves in 3\u20135 jobs." },
      { heading: "Months 5\u20138: Second Lens + Second Light + Audio Upgrade", example: "Prime lens (50mm or 85mm) + Aputure 300D or second 120 for fill + lavalier kit (Rode Wireless Pro or similar).", note: "You can now shoot real multi-light setups + capture professional audio. Rate cards can raise here." },
      { heading: "Months 9\u201312: Specialty + Upgrade", example: "Choose based on work: anamorphic or macro lens / color-tunable lights (Nanlux) / DIT drives + monitor / drone.", note: "By month 12, you have a complete pro kit that will cover 80\u201390% of jobs. Rent the remaining 10\u201320%." },
    ], rule: "The roadmap is 12 months because it matches how your rate raises. Each quarter of added gear justifies raising rates in the next quarter. Gear + rate grow together." },
    { type: "comparison", eyebrow: "OWN vs RENT DECISION", title: "Two cinematographers, same income, different gear strategies", subtitle: "Both earn $60k/yr. One owns $40k of gear on finance; one owns $8k of gear + rents as needed. Guess who has better cash flow?", left: { title: "Over-Owned (Debt-Financed)", color: "#EF4444", items: [
        { strong: "Financed $40k kit: ARRI Amira, two primes, lights", note: "Monthly payments $1,400+. Locked into those payments regardless of work volume." },
        { strong: "Rarely rents \u2014 uses owned gear for every shoot", note: "Client wants anamorphic? Uses the non-ideal spherical because they own it. Work suffers." },
        { strong: "Cash flow negative 3 months per year due to payments", note: "One slow month = emergency. No savings. Any gear failure = crisis." },
        { strong: "Psychological pressure: must book everything to service debt", note: "Takes jobs that don't elevate the portfolio. Career plateaus because every decision is survival-mode." },
    ] }, right: { title: "Balanced (Owned Core + Rentals)", color: "#10B981", items: [
        { strong: "Owns $8k core kit: FX30 + 3 lenses + 2 lights + audio", note: "No debt. Cash flow clean. Gear covers 80% of typical jobs." },
        { strong: "Rents $500\u2013$2k per project as specialty requires", note: "Client wants anamorphic? Rents for 2 days. Cost passed through to budget. Perfect tool for the job." },
        { strong: "Saves 15\u201320% of income; builds reserve + upgrades from savings", note: "Slow months covered. Can afford to turn down bad jobs. Better portfolio = rate raises." },
        { strong: "Psychological freedom: can focus on craft + career, not debt", note: "Better decisions compound. Over 5 years, this DP out-earns the debt-financed one significantly." },
    ] }, footer: "Rule: gear is a tool, not an identity. Professional DPs use the right tool per job \u2014 owned or rented. Ego-owning gear slows careers." },
    { type: "table", title: "Rent vs Buy Decision Matrix", subtitle: "A simple test for every gear purchase \u2014 do the math before the shopping cart.", columns: ["Gear", "Decision", "Reasoning"], rows: [
      ["Primary camera body", "Buy (mid-tier)", "Used on every job. Owning saves per-shoot rental. Upgrade every 4\u20135 years."],
      ["Workhorse zoom (24-70)", "Buy", "Used on 70%+ of jobs. Rental ROI after ~15 days of work."],
      ["Fast prime (35mm, 50mm, or 85mm)", "Buy one of these", "Signature lens defines your look. Used often. Buy the one you reach for most."],
      ["Anamorphic lenses", "Rent", "Expensive, project-specific. Rent when the script demands. $2k/day in rentals beats $30k+ to own."],
      ["Basic lighting (1\u20132 lights + modifiers)", "Buy", "Used on most jobs. Cheap to own. Huge image impact."],
      ["Heavy lighting (HMI, large LEDs)", "Rent", "Per-project. Rental shops have newer gear than you can afford."],
      ["Camera support (tripod, gimbal)", "Buy", "Everyday use. Buy once + it lasts 10 years."],
      ["Dolly, crane, steadicam", "Rent", "Specialty support; rent with operator on larger budgets."],
      ["Monitors + wireless video", "Buy if client-facing work dominates", "Directors + clients want their own monitor. Owning speeds setup."],
      ["Drones", "Rent or hire a drone op", "Regulations + crashes; often cheaper to hire a licensed operator per shoot."],
    ], footer: "Rule: rent anything used fewer than 15\u201320 days/year. Buy anything used more. This rule alone protects your cash flow." },
    { type: "exercise", title: "Design Your Personal 12-Month Gear Plan", intro: "Given your current income + work type, plan what you'd acquire in the next 12 months + at what tempo.", items: [
      { num: "1", copy: "Calculate your realistic monthly reinvestment budget (10\u201320% of cinematography income). Write the number down.", answer: "Honesty matters. If it's $300/mo, plan for $300/mo. No aspirational financing. The pace is what it is." },
      { num: "2", copy: "List your current kit. Note which pieces cover which typical jobs. Identify 2 biggest gaps.", answer: "Example gaps: 'I rent a gimbal 8x/year' or 'I don't own a second light + always borrow.' These are your buy priorities." },
      { num: "3", copy: "Map the next 4 quarterly purchases to plug those gaps. Total cost must fit inside your budget.", answer: "Quarterly rhythm forces discipline. Each buy is backed by 3 months of earned income. No credit card decisions." },
      { num: "4", copy: "Write a one-sentence rate-raise justification for each purchase. ('Adding second light enables multi-source interviews, raising rate $200/day.')", answer: "If you can't justify a rate raise from a gear addition, reconsider the purchase. Gear should unlock earning, not consume it." },
    ] },
  ],
};
