// Voice, CTAs & The Close - Module 6 (capstone) for Copywriting
// The final 20% that separates forgettable copy from copy that converts \u2014 and the part AI understands least

export const closeModule = {
  id: "clse01",
  title: "Voice, CTAs & The Close",
  type: "Rich Module",
  duration: "90 min",
  desc: "The capstone module: brand voice, offer construction, and CTA design \u2014 the final 20% of copy that moves a reader from \"interested\" to \"bought.\"",
  topics: ["Brand Voice", "Voice Diagnosis", "Offer Stacking", "Risk Reversal", "CTA Design", "Landing Page Capstone"],
  quiz: [
    { q: "The single most reliable signal that copy was written by a human rather than AI is:", opts: ["Perfect grammar", "A consistent, recognisable voice \u2014 including rhythm, word choice, and point of view", "Formal tone throughout", "Heavy use of industry jargon"], correct: 1 },
    { q: "Which CTA is strongest?", opts: ['"Learn More"', '"Click Here"', '"Submit"', '"See how Priya cut triage time to 2 min \u2014 live in your Zendesk in 4 clicks"'], correct: 3 },
    { q: "Offer stacking works because:", opts: ["It makes the page longer", "Each layer (price \u2192 deliverables \u2192 bonuses \u2192 guarantee) raises perceived value while lowering perceived risk", "It intimidates the buyer", "It's an SEO technique"], correct: 1 },
    { q: "The most common reason a perfectly written CTA still fails to convert is:", opts: ["Wrong font", "Button colour", "The reader has an unresolved objection within 150px of the button", "The button is too small"], correct: 2 },
    { q: "A good voice audit question to ask when reviewing a draft is:", opts: ['"Is it grammatically correct?"', '"Could any competitor\'s CEO have written this paragraph?"', '"Is it long enough?"', '"Does it use the keyword enough?"'], correct: 1 },
    { q: "Risk reversal on a CTA means:", opts: ["Warning the reader about risks of buying", "Shifting the risk of the purchase from the buyer to the seller right at the commitment moment", "Adding legal disclaimers", "Linking to the terms of service"], correct: 1 },
  ],
  slides: [
    {
      type: "cover",
      module: "MODULE 6",
      title: "Voice, CTAs",
      titleAccent: "& The Close",
      subtitle: "The final 20% of copy \u2014 brand voice, offer construction, and call-to-action design \u2014 is also the hardest part for AI to fake. This module puts the entire course together.",
      meta: "Advanced Copywriting Training  |  Module 6 of 6  |  11 Slides (Capstone)",
    },
    {
      type: "stats",
      eyebrow: "WHY THE FINAL 20% MATTERS MOST",
      title: "Buyers don't convert on the draft. They convert on the close.",
      intro: "You can write a perfectly structured, well-researched page and still lose the sale in the last 200 words. The close is where voice, offer, and CTA compound \u2014 or collapse.",
      stats: [
        { num: "64%", label: "of readers who reach the pricing section never reach the CTA" },
        { num: "3.1\u00D7", label: "higher conversion on pages with a specific, benefit-led CTA vs. generic ones" },
        { num: "82%", label: "of buyers say \"the brand felt like a real person\" about products they chose" },
      ],
      subheading: "What AI Still Can't Do (Reliably)",
      bullets: [
        "Voice: AI blends. A strong brand voice is the most specific, opinionated, recognisable thing you own \u2014 and the hardest to average.",
        "Offer design: AI lists features. Humans construct offers that stack value and reverse risk at the exact moment of commitment.",
        "CTAs: AI defaults to \"Get Started\" and \"Learn More.\" Humans write CTAs that answer the last unspoken objection.",
      ],
    },
    {
      type: "grid",
      eyebrow: "THE THREE PILLARS OF THE CLOSE",
      title: "Voice \u2022 Offer \u2022 CTA",
      subtitle: "Miss any of these and the reader stalls. Nail all three and the page sells itself.",
      items: [
        { num: "01", title: "Voice", desc: "The consistent point-of-view, rhythm, and word choice that makes copy feel like a specific person \u2014 not a brand committee, and not an AI average.", icon: "\u{1F3A4}" },
        { num: "02", title: "Offer", desc: "The stacked, risk-reversed package that turns a price into an obviously-good deal. Not what you sell \u2014 how you sell it.", icon: "\u{1F4E6}" },
        { num: "03", title: "CTA", desc: "The single line and button that moves the reader from \"interested\" to \"clicked.\" Specific, benefit-led, and friction-free.", icon: "\u{1F446}" },
      ],
      footer: "The rest of this module: how to diagnose, construct, and ship all three \u2014 and how to tell when you've failed at each.",
    },
    {
      type: "principle",
      num: "01",
      title: "Voice \u2014 The Thing AI Keeps Averaging Away",
      intro: "Brand voice is the sum of three choices: what you'll say that others won't, what you'll refuse to say, and the rhythm you keep. AI copies voice patterns it has seen; it doesn't originate them. That gap is your moat.",
      sectionTitle: "The 4-Question Voice Diagnostic",
      sections: [
        { heading: "1. What specific opinion does this copy take?", example: "\"Most CRMs are bloated garbage. We built the opposite.\"", note: "Opinionated copy converts. Neutral copy blends. AI almost always blends." },
        { heading: "2. What words does this brand refuse to use?", example: "We don\u2019t say \u2018solutions\u2019, \u2018synergy\u2019, \u2018revolutionise\u2019, \u2018unlock\u2019.", note: "A strong voice is often defined by its blacklist. Write yours down; enforce it ruthlessly." },
        { heading: "3. What's the rhythm? Short? Long? Fragments?", example: "\"Big tools. Big contracts. Big lies about ROI. We do the opposite.\"", note: "AI writes in predictable, medium-length sentences. Humans vary. Fragments. Like this." },
        { heading: "4. Could any competitor\u2019s CEO have written this paragraph?", example: "If yes \u2014 you haven't written in your voice yet.", note: "The final test. Remove the brand name; could Stripe, Twilio, Segment all have written this? Then it's generic." },
      ],
      rule: "Voice is not style. Voice is point of view. AI mimics style fluently; it cannot originate a genuine point of view.",
    },
    {
      type: "comparison",
      eyebrow: "VOICE IN ACTION",
      title: "Two Versions of the Same About Page",
      subtitle: "Fictional: a B2B payments company. The AI-default blends with every competitor. The human voice commits to a worldview.",
      left: {
        title: "AI-Default Voice",
        color: "#EF4444",
        items: [
          { strong: "\"We are a leading payments platform helping businesses scale seamlessly.\"", note: "Generic. Applies to every payments company." },
          { strong: "\"Our innovative solutions empower teams to focus on what matters.\"", note: "\"Innovative solutions empower\" = three tell-tale AI words in one clause." },
          { strong: "\"We believe in excellence and customer success.\"", note: "Nobody disagrees with excellence. No opinion = no voice." },
          { strong: "\"Join the thousands of companies who trust us.\"", note: "No numbers, no names, no specifics, no personality." },
        ],
      },
      right: {
        title: "Human Voice (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: "\"We built a payments API for companies that are allergic to sales calls.\"", note: "Specific audience. Opinionated. Funny. Recognisable." },
          { strong: "\"No demo gates. No \u2018contact us\u2019 pricing. All prices public \u2014 always.\"", note: "Commits to a public stance competitors won\u2019t take." },
          { strong: "\"We don't do synergy. We don't do platforms. We do payments that settle in 47 seconds.\"", note: "The \u201Cthings we refuse\u201D list is itself the voice." },
          { strong: "\"947 companies migrated from Stripe to us in 2025. Here are the 12 who regretted it.\"", note: "Vulnerability + named number + opinion = zero AI would write this." },
        ],
      },
      footer: "Notice how the human version has strong preferences. That's what voice IS \u2014 the sum of your preferences, visible on the page.",
    },
    {
      type: "principle",
      num: "02",
      title: "The Offer \u2014 Stacking Value, Reversing Risk",
      intro: "An offer is not a price. An offer is the complete package of what the buyer gets, what they pay, and what they risk \u2014 arranged so that saying \"yes\" feels obviously rational. AI lists features; humans construct offers.",
      sectionTitle: "The 6 Layers of a Strong Offer (Stack Them)",
      sections: [
        { heading: "1. Core deliverable", example: "What they actually buy: software access, a service, a product SKU.", note: "State it with zero marketing. \"A Slack bot that auto-logs standups.\"" },
        { heading: "2. Price", example: "\"$1,200/mo, billed monthly. Annual saves 2 months.\"", note: "State it directly. No \u201Ctalk to sales\u201D hides \u2014 every hidden price is a friction point." },
        { heading: "3. What's included (the stack)", example: "Unlimited users. All integrations. Dedicated Slack channel. Quarterly strategy reviews.", note: "Bullet the full contents. Each bullet is a value-increase moment." },
        { heading: "4. Guarantee / risk reversal", example: "\"30-day refund. 1-click cancel. If onboarding takes over 48 hrs we pay you $500.\"", note: "Moves risk from buyer to seller. Strongest offers have at least two forms." },
        { heading: "5. Bonuses", example: "\"Signups in April get: a 1:1 workflow audit, 3 months of our copy library, founder DM access.\"", note: "Bonuses tip the scale without cutting the price. AI forgets these; humans remember." },
        { heading: "6. Urgency / scarcity (when real)", example: "\"We onboard 10 new teams each month \u2014 April is 7/10 full.\"", note: "Only real constraints. Fake urgency is the fastest way to kill trust." },
      ],
      rule: "Price is what the buyer pays. Offer is what the buyer gets. A $1,200/mo offer with a real stack can feel like a steal; a $300/mo offer with no stack can feel expensive.",
    },
    {
      type: "table",
      title: "The Offer Stack \u2014 Before & After",
      subtitle: "Same product, same price. The \"After\" version constructs an offer rather than just naming a price.",
      columns: ["Before (just a price)", "After (a constructed offer)", "What Was Added"],
      rows: [
        ["\"$1,200/month. Start your free trial.\"", "\"$1,200/month. Unlimited seats. All integrations. Dedicated Slack channel.\"", "The stack \u2014 makes the price feel earned"],
        ["\"Cancel anytime.\"", "\"30-day money-back. 1-click cancel in settings. No sales-call offboarding.\"", "Specific risk reversal"],
        ["\"Sign up today.\"", "\"Sign up in April \u2014 get a 1:1 workflow audit + 3 mo of our copy library, free.\"", "Bonuses that don\u2019t cut price"],
        ["\"Limited time offer.\"", "\"We onboard 10 teams/month to maintain setup quality \u2014 April is 7/10 full.\"", "Real scarcity with an actual reason"],
        ["\"Free trial available.\"", "\"14 days free. You keep everything you set up, even if you don\u2019t convert.\"", "Removes the \u201Csunk setup time\u201D objection"],
      ],
      footer: "Rule: the offer should be a paragraph, not a line. If your pricing section is one sentence, you haven't built an offer yet.",
    },
    {
      type: "principle",
      num: "03",
      title: "The CTA \u2014 The Last Line Before Conversion",
      intro: "The CTA is the most-read, least-written element on any landing page. Most CTAs are worse than they need to be because AI and template defaults are \"Get Started\" and \"Learn More.\" A good CTA answers the reader\u2019s last objection in 6\u201312 words.",
      sectionTitle: "The 5 Rules of a High-Converting CTA",
      sections: [
        { heading: "1. Name the benefit, not the action", example: "\"See my team's ROI in 30 seconds\" beats \"Get Started\" every time.", note: "The action (\"Submit\") is what they do. The benefit is why they'd do it. Write the why." },
        { heading: "2. Remove friction in the button itself", example: "\"Start free \u2014 no credit card\" vs. \"Start your trial\".", note: "Put the objection-killer inside the CTA. Reader resolves it without scrolling." },
        { heading: "3. Make the outcome specific", example: "\"Import your first team in 90 seconds\" beats \"Sign Up Now.\"", note: "Time + mechanism = picture in the reader's head. AI CTAs are painterly; human CTAs are photographic." },
        { heading: "4. Stack CTAs with intent matching", example: "Primary: \"Start free\". Secondary: \"See a live demo\". Tertiary: \"Read the case study\".", note: "Readers are at different intent levels. Give them all three paths \u2014 don\u2019t force one behaviour." },
        { heading: "5. Pair with risk reversal in the micro-copy", example: "CTA: \"Start free.\" Directly below: \"30-day refund. Cancel in 1 click. No sales call.\"", note: "The button is the commitment; the micro-copy is the safety net. Don\u2019t ship one without the other." },
      ],
      rule: "Write 15 CTA variants. Pick the one that would still work if it were the only line on the page. That's your CTA.",
    },
    {
      type: "table",
      title: "Weak CTAs \u2192 Strong CTAs",
      subtitle: "Same action, rewritten to answer the reader\u2019s last objection inside the button itself.",
      columns: ["Weak CTA", "Strong CTA", "What the Strong Version Adds"],
      rows: [
        ["\"Get Started\"", "\"Start free \u2014 no credit card, 1-min setup\"", "Friction removed + specific setup time"],
        ["\"Learn More\"", "\"See Priya's 14\u2192 2 min workflow in 30 seconds\"", "Named story + specific before/after"],
        ["\"Sign Up\"", "\"Import your first team in 90 seconds\"", "Specific mechanism + time"],
        ["\"Contact Sales\"", "\"Book a 15-min call with a real engineer (not a BDR)\"", "Removes the \"BDR filter\" objection"],
        ["\"Try It Free\"", "\"Try 14 days free. Keep your setup even if you don't convert.\"", "Removes the \"sunk time\" objection"],
        ["\"Request a Demo\"", "\"See a live 3-min demo \u2014 no calendar link\"", "Promises zero scheduling overhead"],
      ],
      footer: "Rule: a strong CTA is a sentence, not a word. One-word CTAs are AI-template defaults \u2014 almost never the best choice.",
    },
    {
      type: "exercise",
      title: "Capstone Challenge \u2014 The Landing Page Close",
      intro: "For each fictional product below, write (a) a 2-sentence voice opener, (b) a 4-layer offer (price + stack + guarantee + bonus), and (c) a strong CTA with risk-reversal micro-copy.",
      items: [
        { num: "1", copy: "Product: a $49/mo pricing tool for freelance designers.", answer: "Voice: \u201CFreelance designers shouldn't need a spreadsheet to quote a logo. We built the tool we wished existed in 2019.\u201D  Offer: $49/mo. Unlimited quotes. Template library. 2 client portals. 30-day refund. April signups: free 1:1 pricing audit.  CTA: \u201CQuote your next project in 2 min \u2014 no card required.\u201D  Micro: \u201C30-day refund, 1-click cancel.\u201D" },
        { num: "2", copy: "Product: a $2,400/mo compliance dashboard for 50\u2013200 person SaaS companies.", answer: "Voice: \u201CSOC 2 audits still take 6 months because your compliance tool is a glorified spreadsheet. We rebuilt it for companies that ship on Fridays.\u201D  Offer: $2,400/mo. Auto-evidence collection. Live auditor portal. Unlimited policies. 48-hr setup or we pay $500. Free 3-month Vanta migration for April.  CTA: \u201CSee your SOC 2 readiness score \u2014 in 90 seconds, no demo required.\u201D  Micro: \u201C30-day refund. Cancel in settings. Export all evidence anytime.\u201D" },
        { num: "3", copy: "Product: a $39 ebook + templates bundle for copywriting.", answer: "Voice: \u201CMost copywriting books are 200 pages telling you that specificity matters. This one is 40 pages of actual specifics \u2014 plus the 74 templates we used to write this page.\u201D  Offer: $39 one-time. 40-page PDF. 74 templates (Notion + Google Docs). Bonus: a 30-min voice-audit recording. 30-day refund.  CTA: \u201CGet the templates I used to close $180K last month.\u201D  Micro: \u201C30-day refund, just reply \u2018refund\u2019 to the email.\u201D" },
      ],
    },
  ],
};
