// Frameworks & The Human Edge - Module 3 for Copywriting
// AIDA, PAS, and critical-thinking techniques that beat AI-default copy

export const frameworksModule = {
  id: "frmk01",
  title: "AIDA, PAS & The Human Edge",
  type: "Rich Module",
  duration: "90 min",
  desc: "Master the two copy structures behind every high-converting page \u2014 and learn how to write copy AI cannot replicate by thinking deeper than a prompt.",
  topics: ["AIDA Framework", "PAS Framework", "Critical Thinking Prompts", "Spotting AI Slop", "Specificity & Proof", "Voice & Insight"],
  quiz: [
    { q: "AIDA stands for:", opts: ["Attention, Intent, Demand, Action", "Attention, Interest, Desire, Action", "Authority, Insight, Decision, Acceptance", "Audience, Intent, Device, Ad"], correct: 1 },
    { q: "The Agitation step in PAS is designed to:", opts: ["List all product features in detail", "Push on the reader's pain so the solution feels urgent", "Apologise for the problem existing", "Introduce the brand's backstory"], correct: 1 },
    { q: "Which of these is a tell-tale sign of AI-generated copy?", opts: ["A specific dollar figure", "A named customer and outcome", 'Vague adjectives like "cutting-edge", "seamless", "powerful"', "A counterintuitive claim"], correct: 2 },
    { q: 'The test "If I removed the product name, would it still be distinct?" is designed to catch:', opts: ["Spelling errors", "Interchangeable, generic copy that could apply to any competitor", "Overly long headlines", "Missing calls-to-action"], correct: 1 },
    { q: "The best way to use AI inside a copywriting workflow is to:", opts: ["Accept the first draft as final", "Use it for structure, then replace every vague line with specificity, proof, and a claim only you would know", "Use it only for grammar checks", "Avoid it entirely in all cases"], correct: 1 },
    { q: "Which landing page opener shows the strongest human edge?", opts: ['"Revolutionise the way your team works"', '"Unlock the full potential of your business"', '"Your team loses 4.2 hours a week to status meetings. We cut that to 12 minutes."', '"The best project tool for modern companies"'], correct: 2 },
  ],
  slides: [
    {
      type: "cover",
      module: "MODULE 3",
      title: "AIDA, PAS",
      titleAccent: "& The Human Edge",
      subtitle: "Two copy structures that power every high-converting page \u2014 and the critical-thinking moves that make your copy beat anything AI can generate.",
      meta: "Advanced Copywriting Training  |  Module 3 of 6  |  14 Slides",
    },
    {
      type: "stats",
      eyebrow: "WHY MOST AI COPY FAILS",
      title: "AI gives you the structure. It cannot give you the edge.",
      intro: "The frameworks are free. Specificity, tension, and insider knowledge are not. That's where your critical thinking becomes the competitive advantage.",
      stats: [
        { num: "73%", label: "of readers can identify AI-written copy within 3 lines" },
        { num: "3.2\u00D7", label: "higher engagement on human-insight copy vs templated output" },
        { num: "12%", label: "average CTR lift from replacing one generic line with one specific claim" },
      ],
      subheading: "What This Means for You",
      bullets: [
        "AI writes from the statistical average of the internet \u2014 generic by design.",
        "Readers trust specificity. AI defaults to abstractions (\"cutting-edge\", \"seamless\", \"powerful\").",
        "Your competitive advantage is not the framework \u2014 it's the thinking you do before you fill it in.",
        "Used well: AI is scaffolding. Used lazily: AI is a ceiling you never notice you're hitting.",
      ],
    },
    {
      type: "grid",
      eyebrow: "CORE FRAMEWORK",
      title: "Two Structures + The Edge That Makes Them Work",
      subtitle: "Master the two structures behind every high-converting page. Then learn what to put inside them that AI cannot.",
      items: [
        { num: "01", title: "AIDA", desc: "Attention \u2022 Interest \u2022 Desire \u2022 Action. The classic funnel for ads, landing pages, and cold outreach.", icon: "\u{1F3AF}" },
        { num: "02", title: "PAS", desc: "Problem \u2022 Agitation \u2022 Solution. The emotional structure behind B2B pain-selling and high-converting emails.", icon: "\u{1F525}" },
        { num: "03", title: "The Human Edge", desc: "Specificity + Tension + Voice. The three things AI consistently misses \u2014 and what critical thinking adds.", icon: "\u{1F9E0}" },
      ],
      footer: "The frameworks are cheap. The human edge is what makes them convert.",
    },
    {
      type: "principle",
      num: "01",
      title: "AIDA \u2014 The Classic Funnel",
      intro: "AIDA is the most-used structure in advertising for a reason: it mirrors how attention flows. But AI-generated AIDA is transparently AI. The magic is in what you put inside each step.",
      sectionTitle: "The Four Stages \u2014 And What to Think About at Each",
      sections: [
        { heading: "Attention", example: '"Your team loses 4.2 hrs/wk in status meetings."', note: "Open with a surprise, a specific stat, or a pattern interrupt \u2014 never a pleasantry." },
        { heading: "Interest", example: '"Here\'s what we learned analysing 1,847 engineering teams..."', note: "Offer proof, data, or insider knowledge. This is where AI goes vague \u2014 and you get specific." },
        { heading: "Desire", example: '"Imagine reclaiming 3+ hours every week without a single Zoom call."', note: "Paint the outcome \u2014 what their life looks like after. Be concrete, not aspirational." },
        { heading: "Action", example: '"Start your 14-day trial \u2014 import your first team in 90 seconds."', note: "One action. Specific timeframe. Remove friction in the CTA itself." },
      ],
      rule: "AI fills every slot. Your job is to make every slot specific enough that it could only come from you.",
    },
    {
      type: "comparison",
      eyebrow: "AIDA IN ACTION",
      title: "Same Product, Two AIDAs \u2014 Spot the Difference",
      subtitle: "Both versions use the exact same framework. One was generated by AI. One was written with critical thinking applied.",
      left: {
        title: "AI-Default AIDA",
        color: "#EF4444",
        items: [
          { strong: "A: \"Revolutionise how your team communicates.\"", note: "Vague verb, no specifics, no pain identified." },
          { strong: "I: \"Our cutting-edge platform streamlines workflows.\"", note: '"Cutting-edge", "streamlines" \u2014 could describe any SaaS product.' },
          { strong: "D: \"Unlock unprecedented productivity and collaboration.\"", note: "Aspirational jargon. No concrete outcome visible." },
          { strong: "A: \"Get started today and transform your business.\"", note: "No mechanism, no timeframe, no friction removed." },
        ],
      },
      right: {
        title: "Human-Edge AIDA (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: "A: \"Status meetings cost your team 4.2 hrs/week.\"", note: "Specific pain, cited hours, immediate tension." },
          { strong: "I: \"We analysed 1,847 eng teams. 94% hit this wall by Year 2.\"", note: "Real data, authority signal, insider knowledge." },
          { strong: "D: \"Reclaim 3+ hours every week. No daily Zooms, no Slack pings.\"", note: "Concrete outcome + what you're removed from." },
          { strong: "A: \"Try 14 days free. Your team is importable in 90 seconds.\"", note: "Specific duration + friction obliterated." },
        ],
      },
      footer: "The structure is identical. The thinking is not. Readers feel the difference instantly \u2014 and convert accordingly.",
    },
    {
      type: "principle",
      num: "02",
      title: "PAS \u2014 The Emotional Structure",
      intro: "PAS (Problem \u2022 Agitate \u2022 Solve) is the workhorse of B2B emails, sales pages, and cold outreach. It works because it mirrors how a reader already thinks about their pain \u2014 if you name the pain precisely enough.",
      sectionTitle: "The Three Steps \u2014 And the Trap AI Falls Into at Each",
      sections: [
        { heading: "Problem", example: '"Your sales team is spending 11 hrs/week manually logging CRM data."', note: "AI names the category (\"CRM inefficiency\"). You name the exact behaviour and cost." },
        { heading: "Agitate", example: '"That\'s 572 hours a year. One full-time headcount \u2014 lost to data entry."', note: "AI adds adjectives (\"frustrating\", \"inefficient\"). You do the maths and make the pain visible." },
        { heading: "Solve", example: '"Our Gmail plugin auto-logs every email. Setup in 4 minutes. No rep training needed."', note: "AI describes features. You name the mechanism, the speed, and the objection it removes." },
      ],
      rule: "Agitation is not negativity \u2014 it's precision. Name the cost in hours, dollars, or headcount. AI will not.",
    },
    {
      type: "comparison",
      eyebrow: "PAS IN ACTION",
      title: "Two PAS Emails \u2014 Written for the Same Prospect",
      subtitle: "Cold outbound to a VP of Sales at a 200-person SaaS company.",
      left: {
        title: "AI-Default PAS",
        color: "#EF4444",
        items: [
          { strong: "P: \"CRM data entry is a pain point for many sales teams.\"", note: "Generic. Applies to every company in existence." },
          { strong: "A: \"This can be frustrating and inefficient, costing you time.\"", note: 'Vague agitation. "Frustrating" is not a cost.' },
          { strong: "S: \"Our solution helps automate this process seamlessly.\"", note: '"Seamlessly" does no work. No mechanism. No speed.' },
          { strong: "Subject: Transform your sales productivity", note: "Zero specificity \u2014 looks like spam." },
        ],
      },
      right: {
        title: "Human-Edge PAS (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: "P: \"Your reps spend ~11 hrs/week logging CRM data manually.\"", note: "Role-specific. Quantified. Feels researched." },
          { strong: "A: \"That's 572 hrs/yr \u2014 roughly one full SDR headcount.\"", note: "Maths = visceral. Pain converted to headcount cost." },
          { strong: "S: \"Our Gmail plugin auto-logs every email. 4-min setup. No training.\"", note: "Mechanism + setup time + objection-killer in one line." },
          { strong: "Subject: 11 hrs/wk your reps aren't selling", note: "Numeric + pain-led \u2014 open rate ~3-5\u00D7 the generic version." },
        ],
      },
      footer: "Notice: the Human-Edge version has zero adjectives. It's all nouns, verbs, and numbers. That's the tell.",
    },
    {
      type: "table",
      title: "Tell-Tale Signs of AI Slop",
      subtitle: "Every line of copy you publish should pass this check. If it has these patterns, rewrite.",
      columns: ["Tell", "Why It Fails", "Human Fix"],
      rows: [
        ["Vague power adjectives", '"cutting-edge", "seamless", "powerful", "robust" \u2014 carries no information', "Replace with a number, a verb, or a named mechanism"],
        ["No proper nouns", "Reader can't tell if it's written for them or for a template", "Name the industry, role, tool, or stage"],
        ["Feature list dressed as benefits", '"Our AI-powered engine enables..." \u2014 describes the seller, not the buyer', "Rewrite as outcome: \"Your team gets X in Y time\""],
        ["Hedging language", '"can help", "may improve", "often results in" \u2014 AI hedges by default', "State a specific claim. Add a case study if needed"],
        ["Parallel sentence structure", "Three sentences, same length, same rhythm \u2014 a classic AI tell", "Vary length. Use fragments. Break. Rhythm."],
        ["Cliché openers", '"In today\'s fast-paced world", "Let\'s face it", "We all know"', "Open with a stat, a question, or a pattern interrupt"],
        ["Interchangeable copy", "Swap your brand name for a competitor's and nothing changes", "Add something only YOUR company/customer would say"],
      ],
      footer: "The fastest audit: remove your product name. If the copy still makes sense for any competitor, it's generic.",
    },
    {
      type: "grid",
      eyebrow: "BEFORE YOU WRITE A WORD",
      title: "6 Critical-Thinking Prompts",
      subtitle: "Ask these six questions before you open a blank doc. They are the work AI cannot do for you.",
      items: [
        { num: "01", title: "What's the specific tension?", desc: "What does the reader feel right now, in the body \u2014 not in the abstract? \"Anxious about end-of-month numbers\" not \"wants growth\".", icon: "\u26A1" },
        { num: "02", title: "What would only I know?", desc: "What insider fact, customer quote, or internal data do you have that no competitor could write?", icon: "\u{1F511}" },
        { num: "03", title: "What's the concrete number?", desc: "Every section should earn one real number \u2014 hours, dollars, percentage, headcount. Abstract claims lose.", icon: "\u{1F522}" },
        { num: "04", title: "Remove the brand name \u2014 does it still fit?", desc: "If the copy describes your competitor equally well, it's generic. Add the distinguishing angle.", icon: "\u{1F50D}" },
        { num: "05", title: "What's the ONE belief they need?", desc: "If the reader only believed one thing from this copy, what would it be? Write that line first.", icon: "\u{1F3AF}" },
        { num: "06", title: "What's the AI-default version \u2014 and where can I go further?", desc: "Imagine the generic AI version. Write one level deeper: more specific, more contrarian, more earned.", icon: "\u{1F680}" },
      ],
      footer: "If you cannot answer questions 1, 2, and 5 in a single sentence each, you are not ready to write \u2014 no matter how good your AI prompt is.",
    },
    {
      type: "table",
      title: "Before (AI-Default) \u2192 After (Critical Thinking Applied)",
      subtitle: "Same product, same framework. The only thing that changed: the thinking before the writing.",
      columns: ["AI-Default Copy", "After Critical Thinking", "What Changed"],
      rows: [
        ['"Streamline your workflow with our cutting-edge AI tool"', '"Your PM spends 6.3 hrs/wk reformatting Jira tickets. We cut it to zero."', "Specificity + named role + quantified pain"],
        ['"Discover a better way to manage projects"', '"Most PM tools have 47 tabs. We built one. Here\'s why."', "Contrarian insight + visual contrast"],
        ['"Unlock the full potential of your business"', '"1,847 Shopify stores used us to cut cart abandonment by 34% last year."', "Proof + social + specific outcome"],
        ['"Transform your customer experience"', '"Customers churn at renewal, not signup. We\'re built for month 11, not month 1."', "Counterintuitive positioning + specific timing"],
        ['"Revolutionise how your team communicates"', '"Your average Slack message is read 2.4 min after it\'s sent. Ours: 14 seconds."', "Head-to-head claim + specific comparison"],
        ['"The leading solution for modern businesses"', '"We lost our first 3 enterprise deals because of SOC 2. Now we have it. Here\'s the audit."', "Vulnerability + proof + earned credibility"],
      ],
      footer: "Each \"After\" version contains at least one thing only the company itself could know. That's unreplicable.",
    },
    {
      type: "principle",
      num: "03",
      title: "The Hybrid Workflow \u2014 AI as Scaffolding, Not Ceiling",
      intro: "AI is not the enemy. Laziness is. Here's how top copywriters use AI to move faster without handing over the critical work.",
      sectionTitle: "The 5-Step Human + AI Workflow",
      sections: [
        { heading: "1. Prompt AI for structure", example: '"Draft AIDA copy for a project mgmt tool for 200-person eng teams"', note: "Let AI give you the skeleton. This saves 20 minutes of staring at a blank doc." },
        { heading: "2. Kill every vague adjective", example: "Delete: cutting-edge, seamless, powerful, robust, innovative", note: "These are the fingerprints. Remove them. Rewrite without them." },
        { heading: "3. Insert one specific in every section", example: "A number, a name, a named tool, a time frame", note: "Every paragraph must earn one specific. No exceptions." },
        { heading: "4. Add the one thing only you know", example: "A customer quote, an internal stat, a counterintuitive lesson", note: "This is the unreplicable layer. AI cannot generate this." },
        { heading: "5. Read it aloud", example: "If it sounds like a brochure, rewrite. If it sounds like a human, ship it.", note: "Rhythm is the final test. AI output has a tell-tale cadence \u2014 human speech doesn't." },
      ],
      rule: "Use AI for the 80% that's commodity. Spend your energy on the 20% that's irreplaceable.",
    },
    {
      type: "exercise",
      title: "Copy Diagnostic Challenge",
      intro: "Each line below is real AI-generated output. Diagnose what's missing, then rewrite it using one specific insight or data point you could plausibly have.",
      items: [
        { num: "1", copy: '"Revolutionise your email marketing with our powerful AI-driven platform."', answer: 'Missing: specificity, pain, mechanism. Fix: "Your last campaign hit 18% open rate. Here\'s the 3 subject-line tweaks that took our customers to 34%."' },
        { num: "2", copy: '"The best CRM for modern, forward-thinking teams."', answer: 'Missing: named audience, proof, differentiation. Fix: "The CRM 400+ outbound SDRs switched to after Salesforce quoted them $180K/yr."' },
        { num: "3", copy: '"Unlock unprecedented growth with our cutting-edge solution."', answer: 'Missing: mechanism, number, any real content. Fix: "The 9 onboarding tweaks that took us from 12% to 38% trial-to-paid in 90 days."' },
        { num: "4", copy: '"Transform your customer experience and drive real results."', answer: 'Missing: the actual problem, the actual result. Fix: "Customers churn at month 11 \u2014 not month 1. We rebuilt our playbook around that. Here\'s what happened."' },
      ],
    },
  ],
};
