// Headline Mastery - Module 2 for Copywriting
// Rich slide data with layout types for the RichSlide renderer

export const headlinesModule = {
  id: "hdln01",
  title: "Headline Mastery",
  type: "Rich Module",
  duration: "90 min",
  desc: "Proven formulas that turn scrollers into readers — with real examples from top-performing brands, blogs, and ad campaigns.",
  topics: ["4U Formula", "How-To Formula", "Number + Adjective", "Power Words", "A/B Testing", "Email Subject Lines"],
  quiz: [
    { q: '"How to Double Your Leads Without Spending More on Ads" uses which formula?', opts: ["4U Formula", "Number + Adjective", "How-To Formula", "Curiosity Gap"], correct: 2 },
    { q: "Which headline scores highest on the 4U Formula?", opts: ['"Great Marketing Tips for Your Business"', '"5 Marketing Hacks That Work"', '"Boost Email Opens by 47% This Week With 3 Free Templates"', '"Learn to Market Better"'], correct: 2 },
    { q: "Why do odd numbers outperform even numbers in headlines?", opts: ["They're easier to read", "They feel more authentic and less manufactured", "They look more attractive visually", "Search engines prefer them"], correct: 1 },
    { q: "Which email subject line would likely get the highest open rate?", opts: ['"Monthly Newsletter — April Edition"', '"You\'re losing $47/day to this common SEO error"', '"Update from our team"', '"New blog post available"'], correct: 1 },
    { q: "David Ogilvy's rule about headlines suggests:", opts: ["Headlines should always be short (under 6 words)", "Headlines account for 80 cents of every advertising dollar spent", "Never use numbers in headlines", "Always use questions as headlines"], correct: 1 },
    { q: "When A/B testing headlines, which element should you test FIRST?", opts: ["Font size and color", "The core promise (benefit vs feature, gain vs loss framing)", "Punctuation choices", "The author byline"], correct: 1 },
  ],
  slides: [
    {
      type: "cover",
      module: "MODULE 2",
      title: "Headline",
      titleAccent: "Mastery",
      subtitle: "Proven formulas that turn scrollers into readers — with real examples from top-performing brands, blogs, and ad campaigns.",
      meta: "Advanced Copywriting Training  |  Module 2 of 6  |  17 Slides",
    },
    {
      type: "stats",
      eyebrow: "WHY HEADLINES ARE EVERYTHING",
      title: "Your headline does 80% of the work",
      intro: '"On the average, five times as many people read the headline as read the body copy. When you have written your headline, you have spent eighty cents out of your dollar." — David Ogilvy, Father of Advertising',
      stats: [
        { num: "80%", label: "of readers never get past the headline" },
        { num: "5\u00D7", label: "more people read headlines than body copy" },
        { num: "500%", label: "difference in results between best & worst headlines" },
      ],
      subheading: "What This Means for You",
      bullets: [
        "Your headline is your first impression, your ad, and your filter — all in one line.",
        "A great headline on mediocre copy outperforms a mediocre headline on great copy every time.",
        "Headlines are testable — you can (and should) A/B test every headline you write.",
      ],
    },
    {
      type: "grid",
      eyebrow: "CORE FRAMEWORK",
      title: "The 3 Headline Formulas",
      subtitle: "Master these three frameworks and you'll never stare at a blank headline field again.",
      items: [
        { num: "01", title: "The 4U Formula", desc: "Useful \u2022 Urgent \u2022 Ultra-Specific \u2022 Unique. Score any headline 1\u20134 on each U.", icon: "\u{1F9EE}" },
        { num: "02", title: "How-To Formula", desc: "How To [Desired Result] Without [Pain Point]. The problem-solver.", icon: "\u{1F6E0}\uFE0F" },
        { num: "03", title: "Number + Adjective", desc: "[Number] + [Adjective] + [Keyword] + [Promise]. Odd numbers outperform even.", icon: "\u{1F522}" },
      ],
      footer: "We'll now deep-dive into each formula with real-world examples and scored headlines.",
    },
    {
      type: "principle",
      num: "01",
      title: "The 4U Formula \u2014 Score Every Headline You Write",
      intro: "Score your headline 1\u20134 on each of the four Us. If it scores below 3 on any, rewrite it.",
      sectionTitle: "The Four Us",
      sections: [
        { heading: "Useful", example: '"Save time" \u2713  |  "We\'re excited" \u2717', note: "Does it promise a clear benefit? What does the reader GET?" },
        { heading: "Urgent", example: '"This week" \u2713  |  "Someday" \u2717', note: "Is there a reason to act NOW? Does time matter?" },
        { heading: "Ultra-Specific", example: '"47% in 14 days" \u2713  |  "Improve results" \u2717', note: "Are there concrete numbers, timeframes, or details?" },
        { heading: "Unique", example: '"Counterintuitive" \u2713  |  "Best practices" \u2717', note: "Is it different from everything else on the page? Does it surprise?" },
      ],
      example: {
        brand: "4U SCORING IN ACTION",
        label: "WORKED EXAMPLE",
        heading: '"7 Proven Email Subject Lines That Doubled Our Open Rate in 14 Days"',
        bullets: [
          "Useful: 4/4 (actionable subject lines)",
          "Urgent: 3/4 (14-day timeframe)",
          "Ultra-Specific: 4/4 (7 lines, doubled, 14 days)",
          "Unique: 3/4 (\"proven\" implies tested)",
        ],
        result: "14/16 \u2014 Strong headline",
      },
      rule: "Score every headline on all four Us. A score below 12/16 means rewrite.",
    },
    {
      type: "table",
      title: "4U in the Wild \u2014 Real Blog Headlines Scored",
      subtitle: "Real headlines from top blogs, graded with the 4U method.",
      columns: ["Source", "Headline", "Why It Works", "Score"],
      rows: [
        ["HubSpot Blog", '"21 Email Marketing Tips That Actually Increased Our Click Rate by 93%"', "Ultra-specific (21 tips, 93%), useful, unique (\"actually\")", "14/16 \u2013 A"],
        ["Neil Patel", '"How I Grew My Traffic by 195% in 30 Days (Step-by-Step Blueprint)"', "Specific growth (195%), time-bound, actionable, personal case study", "16/16 \u2013 A+"],
        ["Backlinko", '"We Analyzed 11.8 Million Google Search Results. Here\'s What We Learned About SEO"', "Massive specificity (11.8M), authority signal, curiosity gap", "14/16 \u2013 A"],
        ["Generic Blog", '"Some Tips for Better Marketing"', "Vague (\"some\"), no urgency, no specificity, completely generic", "4/16 \u2013 F"],
      ],
      footer: "The gap between A+ and F is measured in millions of views. Specificity and unique angles win every time.",
    },
    {
      type: "principle",
      num: "02",
      title: "How-To Formula \u2014 Make the Reader the Hero",
      intro: 'The structure: How To [Desired Result] Without [Biggest Pain Point / Objection]. "How to" signals actionable content. The "without" removes the main objection before the reader even has it.',
      sectionTitle: "Formula Variations",
      sections: [
        { heading: "Classic", example: '"How to Double Your Leads Without Spending More on Ads"', note: "How To + Result + Without Pain" },
        { heading: "Objection Buster", example: '"How to Write Copy That Converts Even If You\'re Not a Writer"', note: "How To + Result + Even If Objection" },
        { heading: "Time-Bound", example: '"How to Build a 6-Figure Freelance Business in 12 Months"', note: "How To + Result + In Timeframe" },
        { heading: "Case Study", example: '"How Airbnb Went From 3 Guests to a $100B Valuation"', note: "How [Subject] + Achieved Result" },
        { heading: "Proprietary Method", example: '"How to Get 10K Followers Using the Content Ladder Method"', note: "How To + Result + Using Method" },
      ],
      rule: "Always make the reader the hero. \"How to\" > \"We help you\" every time.",
    },
    {
      type: "principle",
      num: "03",
      title: "Number + Adjective \u2014 The Listicle Powerhouse",
      intro: "The structure: [Odd Number] + [Surprising Adjective] + [Keyword] + [Promise/Benefit]. Odd numbers feel more authentic than round even numbers.",
      sectionTitle: "The Science of Numbers in Headlines",
      sections: [
        { heading: "Odd numbers outperform even", example: "7, 11, 13 beat 8, 10, 14", note: "Odd numbers feel more authentic and less manufactured." },
        { heading: "Use digits, not words", example: '"7 Tips" > "Seven Tips"', note: "Digits get ~20% more clicks \u2014 they pop visually." },
        { heading: "Specific > round", example: '"11 tactics" > "10 tactics"', note: "Specificity signals thoroughness and deeper research." },
        { heading: "Higher numbers = more value", example: '"37 Ways", "101 Ideas"', note: "Bigger numbers imply comprehensive resources." },
      ],
      example: {
        brand: "POWER ADJECTIVES THAT BOOST CTR",
        label: "CHEAT SHEET",
        bullets: [
          "Curiosity: Surprising \u2022 Counterintuitive \u2022 Unexpected \u2022 Little-Known \u2022 Hidden",
          "Value: Proven \u2022 Essential \u2022 Actionable \u2022 Effortless \u2022 Science-Backed",
          "Urgency: Critical \u2022 Urgent \u2022 Must-Know \u2022 Time-Sensitive \u2022 Limited",
        ],
      },
    },
    {
      type: "table",
      title: "Number Headlines in the Wild",
      subtitle: "Analyzing top-performing headlines across industries.",
      columns: ["Category", "Headline", "Performance"],
      rows: [
        ["Marketing", "37 Counterintuitive SEO Tactics That Tripled Our Organic Traffic", "47K shares"],
        ["Productivity", "11 Surprising Morning Habits of Billionaire CEOs", "128K views"],
        ["Finance", "9 Hidden Investment Strategies Wall Street Doesn't Want You to Know", "89K shares"],
        ["Health", "21 Science-Backed Foods That Actually Boost Brain Function", "62K shares"],
        ["Tech", "13 Little-Known Chrome Extensions That Will Save You 5 Hours Per Week", "93K views"],
      ],
      footer: "Pattern: Every headline uses an odd number, a surprising adjective, and a specific promise. Zero are generic.",
    },
    {
      type: "grid",
      eyebrow: "VOCABULARY OF PERSUASION",
      title: "Power Words That Trigger Emotion",
      subtitle: "Strategic use of power words increases CTR by 12\u201336%. Use 1\u20132 per headline \u2014 more feels manipulative.",
      items: [
        { num: "01", title: "Fear / Urgency", desc: "Warning \u2022 Deadline \u2022 Limited \u2022 Mistake \u2022 Avoid \u2022 Don't \u2022 Hurry", icon: "\u26A0\uFE0F" },
        { num: "02", title: "Greed / Value", desc: "Free \u2022 Bonus \u2022 Exclusive \u2022 Secret \u2022 Insider \u2022 Save \u2022 Discount", icon: "\u{1F48E}" },
        { num: "03", title: "Curiosity", desc: "Surprising \u2022 Strange \u2022 Hidden \u2022 Shocking \u2022 Reveal \u2022 Little-known", icon: "\u{1F50D}" },
        { num: "04", title: "Trust / Safety", desc: "Proven \u2022 Guaranteed \u2022 Scientific \u2022 Research-backed \u2022 Tested", icon: "\u{1F6E1}\uFE0F" },
        { num: "05", title: "Identity / Belonging", desc: "You \u2022 Your \u2022 Insider \u2022 Member \u2022 Elite \u2022 Smart \u2022 Savvy", icon: "\u{1F465}" },
        { num: "06", title: "The #1 Rule", desc: "\"You\" is the single most powerful word in copywriting. Always make it about the reader.", icon: "\u{1F3AF}" },
      ],
      footer: "Rule of thumb: Use 1\u20132 power words per headline. More than 2 feels manipulative.",
    },
    {
      type: "table",
      title: "Before & After \u2014 Headline Transformations",
      subtitle: "Each weak headline rewritten using one of the three formulas.",
      columns: ["Weak Original", "Strong Rewrite", "Formula Used"],
      rows: [
        ['"Our Software Is Really Good"', '"Cut Your Invoicing Time by 74% \u2014 Join 12,000+ Freelancers Who Switched"', "4U \u2014 specific, social proof"],
        ['"Tips for Better Email Marketing"', '"9 Surprising Email Tweaks That Lifted Revenue 31% in 30 Days"', "Number + Adj \u2014 odd number, specific"],
        ['"We Help Small Businesses Grow"', '"How to Double Your Local Leads Without Spending More on Ads"', "How-To \u2014 reader is hero"],
        ['"New Features Available Now"', '"Your Reports Now Build Themselves \u2014 3 Features Saving Teams 5 Hrs/Week"', "Benefit-Led \u2014 benefit first"],
        ['"Read Our Blog About SEO"', '"We Analyzed 1M Search Results. Here Are the 7 SEO Tactics That Still Work."', "Data + Number \u2014 authority, curiosity"],
        ['"Our Prices Are Affordable"', '"How 847 Startups Cut Their Software Costs by 40% (Without Losing Features)"', "How-To + Number \u2014 social proof"],
      ],
      footer: "Notice the pattern: every rewrite adds a specific number, a clear benefit, and removes vague language.",
    },
    {
      type: "table",
      title: "Email Subject Line Teardown",
      subtitle: "Real subject lines and their open rates \u2014 pattern-matched.",
      columns: ["Sender", "Subject Line", "Open Rate", "Why"],
      rows: [
        ["HubSpot", "You're leaving $4,300/yr on the table (here's proof)", "47%", "Loss Aversion + Curiosity"],
        ["Shopify", "The 3-minute fix that doubled this store's revenue", "42%", "Time + Result"],
        ["Copyblogger", "Why your headlines fail (and the 1 formula that fixes them)", "39%", "Pain + Number"],
        ["Stripe", "9 checkout tweaks that added $127K in recovered revenue", "51%", "Number + Specific $"],
        ["ConvertKit", "Don't send another email before reading this", "44%", "Urgency + Curiosity"],
        ["Mailchimp", "Our latest newsletter", "12%", "Generic \u2014 No hook"],
        ["Acme Corp", "Monthly update from us", "8%", "Zero benefit"],
      ],
      footer: "Specific numbers, loss aversion, and curiosity gaps achieve 3\u20135\u00D7 higher open rates vs generic alternatives.",
    },
    {
      type: "comparison",
      eyebrow: "DATA DECIDES",
      title: "A/B Testing \u2014 Let Your Audience Tell You",
      subtitle: 'Never rely on gut feeling. Real test: "Improve Your Marketing Today" vs "How 847 Startups Cut Ad Costs 40% in 30 Days"',
      left: {
        title: "Variant A (Control)",
        color: "#EF4444",
        items: [
          { strong: '"Improve Your Marketing Today"', note: "Conversion rate: 2.3%" },
          { strong: "Vague promise", note: "No numbers, no specificity" },
          { strong: "No urgency", note: '"Today" is weak without a deadline' },
        ],
      },
      right: {
        title: "Variant B (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: '"How 847 Startups Cut Ad Costs 40% in 30 Days"', note: "Conversion rate: 8.7% (+278%)" },
          { strong: "Social proof (847 startups)", note: "Specific, verifiable result" },
          { strong: "Specific outcome + timeframe", note: "40% in 30 days \u2014 testable" },
        ],
      },
      footer: "Test: Number vs no number \u2022 Question vs statement \u2022 Length \u2022 Power word variations.",
    },
    {
      type: "table",
      title: "Headline Mastery \u2014 Cheat Sheet",
      subtitle: "Pin this. Score every headline before publishing.",
      columns: ["Formula", "Structure", "Best For", "Example"],
      rows: [
        ["4U Formula", "Useful + Urgent + Ultra-Specific + Unique", "All types", '"7 Proven Tactics That Doubled Revenue in 14 Days"'],
        ["How-To", "How To [Result] Without [Pain]", "Tutorials, guides", '"How to Grow Traffic Without Hiring an Agency"'],
        ["Number + Adj", "[Odd #] + [Power Adj] + [Keyword] + [Promise]", "Lists, roundups", '"11 Surprising Hacks That Save 5 Hrs/Week"'],
        ["Question", "Are You [Making Mistake]?", "Emails, ads", '"Are You Making These 5 Landing Page Mistakes?"'],
        ["Negative", "Stop/Don't/Avoid [Bad Thing]", "B2B, fear-based", '"Stop Losing $47/Day to This Common SEO Error"'],
        ["Curiosity Gap", "[Statement]. Here's Why / What.", "Content, social", '"We Analyzed 1M Emails. Here\'s What Actually Works."'],
      ],
      footer: "Golden rule: Write 25+ headline variants for every piece of content. David Ogilvy wrote 104 headlines for a single Rolls-Royce ad.",
    },
    {
      type: "exercise",
      title: "Headline Rewrite Challenge",
      intro: "Rewrite each weak headline using a different formula. Score each with the 4U method.",
      items: [
        { num: "1", copy: '"Our Software Is Good For Your Business"', answer: 'Apply 4U. Sample: "Slash Your Invoicing Time by 74% This Week \u2014 The Free Tool 12,000 Freelancers Trust" (15/16)' },
        { num: "2", copy: '"Tips For Better Marketing"', answer: 'Number + Adjective. Sample: "11 Counterintuitive Marketing Moves That Cut Our CAC by 43%"' },
        { num: "3", copy: '"We Help Companies Grow"', answer: 'How-To. Sample: "How to Grow Your B2B Revenue 3\u00D7 Without Hiring a Sales Team"' },
        { num: "4", copy: '"New Features Available Now"', answer: 'Benefit-led. Sample: "Build Reports in 30 Seconds \u2014 3 New AI Features That Auto-Draft Everything"' },
      ],
    },
    {
      type: "quiz",
      title: "Module 2 Knowledge Check",
      questions: [
        { q: '"How to Double Your Leads Without Spending More on Ads" uses which formula?', opts: ["4U Formula", "Number + Adjective", "How-To Formula", "Curiosity Gap"], correct: 2 },
        { q: "Which headline scores highest on the 4U Formula?", opts: ['"Great Marketing Tips for Your Business"', '"5 Marketing Hacks That Work"', '"Boost Email Opens by 47% This Week With 3 Free Templates"', '"Learn to Market Better"'], correct: 2 },
        { q: "Why do odd numbers outperform even numbers in headlines?", opts: ["They're easier to read", "They feel more authentic and less manufactured", "They look more attractive visually", "Search engines prefer them"], correct: 1 },
        { q: "Which email subject line would likely get the highest open rate?", opts: ['"Monthly Newsletter \u2014 April Edition"', '"You\'re losing $47/day to this common SEO error"', '"Update from our team"', '"New blog post available"'], correct: 1 },
        { q: "David Ogilvy's rule about headlines suggests:", opts: ["Headlines should always be short (under 6 words)", "Headlines account for 80 cents of every advertising dollar spent", "Never use numbers in headlines", "Always use questions as headlines"], correct: 1 },
        { q: "When A/B testing headlines, which element should you test FIRST?", opts: ["Font size and color", "The core promise (benefit vs feature, gain vs loss framing)", "Punctuation choices", "The author byline"], correct: 1 },
      ],
      scoring: "6/6 = Expert  |  5/6 = Advanced  |  4/6 = Proficient  |  3/6 = Review  |  \u22642 = Re-study this module",
    },
    {
      type: "takeaways",
      title: "Module 2 \u2014 Key Takeaways",
      items: [
        "80% of readers never get past the headline \u2014 it's your single most important line of copy.",
        "Use the 4U Formula as a diagnostic tool: score every headline on Useful, Urgent, Ultra-Specific, and Unique.",
        "The How-To Formula makes the reader the hero and pre-empts their biggest objection.",
        "Odd numbers outperform even numbers. Use digits (7) not words (seven). Specificity wins (11 not 10).",
        "Power words trigger emotional responses \u2014 use 1\u20132 per headline from the fear, greed, or curiosity categories.",
        "Write 25+ variants for important headlines. Ogilvy wrote 104 for a single ad. Your first idea is never your best.",
        "A/B test everything \u2014 the difference between a good and great headline can be 278% more conversions.",
      ],
      next: "NEXT UP: Module 3 \u2014 AIDA & PAS Frameworks  |  The two copy structures that power every high-converting page.",
    },
  ],
};
