// Objection Handling & Proof - Module 5 for Copywriting
// Name the reason the reader is about to say no, then give them the specific proof that changes their mind

export const objectionsModule = {
  id: "objc01",
  title: "Objection Handling & Proof",
  type: "Rich Module",
  duration: "90 min",
  desc: "Every unanswered objection is a sale you lose. Learn the 4 objection categories, the 5 forms of proof, and how to weave both into copy that converts skeptics \u2014 without AI-slop claims.",
  topics: ["Price Objections", "Trust Objections", "Fit Objections", "Time Objections", "5 Forms of Proof", "Risk Reversal"],
  quiz: [
    { q: "A landing page says: \"We offer great value\" next to a $1,200/mo price point. A buyer with a \u201Ctoo expensive\u201D objection reads it. What\u2019s wrong and what\u2019s the fix?", opts: ["Nothing wrong", "Unfalsifiable claim next to a high price \u2014 replace with the math: \u201C$1,200/mo; teams recover this in the first 8 days via reclaimed AE time. Past that it\u2019s pure margin.\u201D", "Increase the price", "Remove the price"], correct: 1 },
    { q: "Rank these by proof strength: (A) \"Trusted by leading companies\" (B) \"Industry-recognised\" (C) \"1,847 Shopify Plus merchants used us in Q3 2025 \u2014 up from 1,122 in Q1\" (D) \"The #1 tool in our category\"", opts: ["A > D > C > B", "C >> A, B, D \u2014 specific segment + specific number + specific timeframe + growth direction; the rest are unfalsifiable marketing claims", "All equal", "D > A > B > C"], correct: 1 },
    { q: "A \u201Cfit\u201D objection on a B2B page should most convincingly be resolved by:", opts: ["Claiming to work for everyone", "Explicitly stating who you\u2019re NOT for + the exact profile you ARE built for (\u201Cif under 10 people, don\u2019t buy; if 50\u2013500 eng, here\u2019s why you win\u201D)", "Adding more testimonials", "Lowering the price"], correct: 1 },
    { q: "Ranked by strength of proof: (1) named customer + specific outcome, (2) audited numbers, (3) third-party certification, (4) live demo/screen recording, (5) risk reversal. The common mistake on sales pages is:", opts: ["Using too much of Rank 1", "Leading with Rank 5 (refund guarantees) or Rank 3 (compliance badges) when a single piece of Rank 1 or Rank 2 would do more work than all of them combined", "Using Rank 2", "Skipping all proof"], correct: 1 },
    { q: "A product page hides the price behind \u201Ctalk to sales.\u201D What objection is this creating for everyone who doesn\u2019t immediately book a call?", opts: ["None", "\u201CIt must be expensive + I have to run the gauntlet before I can know\u201D \u2014 hiding price creates a higher objection than whatever number would have appeared", "Fit objection", "Time objection"], correct: 1 },
    { q: "Placement decision: you have a pricing objection to address. Where should the answering copy live?", opts: ["In an FAQ at the bottom of the page", "Directly next to the price on the pricing section \u2014 objections dissolve best at the point where they naturally arise", "On a separate \u201CWhy Us\u201D page", "Never mention it \u2014 mentioning creates it"], correct: 1 },
  ],
  slides: [
    {
      type: "cover",
      module: "MODULE 5",
      title: "Objection Handling",
      titleAccent: "& Proof",
      subtitle: "Every unanswered objection is a sale you lose. Learn to name the reader's hesitation in their own words \u2014 and give them the specific proof that makes \"no\" feel irrational.",
      meta: "Advanced Copywriting Training  |  Module 5 of 6  |  10 Slides",
    },
    {
      type: "stats",
      eyebrow: "WHY OBJECTION COPY MATTERS",
      title: "Readers argue with your copy in their head the whole way down",
      intro: "They're not reading. They're prosecuting. Every paragraph is evaluated against an unspoken objection. If you don't answer it, they assume you can't.",
      stats: [
        { num: "4.3", label: "average number of objections a B2B buyer raises before deciding" },
        { num: "27%", label: "conversion lift from addressing the top objection directly in landing-page copy" },
        { num: "63%", label: "of lost deals cite an objection the sales team never saw the buyer raise" },
      ],
      subheading: "The AI Problem With Objection Copy",
      bullets: [
        "AI hedges. Humans commit. Buyers trust committed copy and dismiss hedged copy as marketing.",
        "AI answers objections with generalities. Buyers need a specific name, number, or screenshot to believe you.",
        "The best objection copy names the exact thought the reader is having. AI writes the average objection; you write the real one.",
      ],
    },
    {
      type: "grid",
      eyebrow: "THE 4 OBJECTION CATEGORIES",
      title: "Every \"no\" falls into one of four buckets",
      subtitle: "Name the bucket. Address it in copy. Move on.",
      items: [
        { num: "01", title: "Price", desc: "\"It costs too much\" / \"I don't see the ROI yet.\" Resolve with math, comparison, and time-to-payback.", icon: "\u{1F4B0}" },
        { num: "02", title: "Trust", desc: "\"I don't know if you're real / credible / safe.\" Resolve with named customers, numbers, compliance docs.", icon: "\u{1F91D}" },
        { num: "03", title: "Fit", desc: "\"Will this work for ME specifically?\" Resolve with role/industry/stage-specific proof, not generic claims.", icon: "\u{1F3AF}" },
        { num: "04", title: "Time / Effort", desc: "\"Implementation sounds painful.\" Resolve with specific setup time, named integrations, done-for-you options.", icon: "\u23F1\uFE0F" },
      ],
      footer: "Before you write any sales page: write the top 3 objections as one-sentence quotes \u2014 in the reader's voice. Then address each one.",
    },
    {
      type: "principle",
      num: "01",
      title: "The Objection Inversion Method",
      intro: "Every strong objection contains the seed of a reason to buy. The inversion method: surface the objection in the buyer's own words, then flip it into the exact reason they should say yes. This beats ignoring the objection AND beats dismissing it.",
      sectionTitle: "How to Invert Each Objection Type",
      sections: [
        { heading: "Price \u2192 Cost-of-inaction", example: "\"Yes, it's $1,200/mo. Your team is losing $4,300/mo to the problem it solves. Payback: 8 days.\"", note: "Name the price. Name the number. Do the maths. Don't hide the cost." },
        { heading: "Trust \u2192 Specific proof", example: "\"No, we're not the biggest. But 847 Shopify Plus stores switched to us from Klaviyo in 2025 \u2014 the customer list is here.\"", note: "Vulnerability + specificity = more trust than any \"industry leader\" claim." },
        { heading: "Fit \u2192 Disqualify publicly", example: "\"If your team is under 10 people, don't buy this. If you're 50\u2013500 eng, here's why every company at your stage chooses us.\"", note: "Telling someone who isn't a fit to NOT buy is the strongest signal to those who are." },
        { heading: "Time \u2192 Specific setup promise", example: "\"Setup in 4 minutes. No integrations team required. If it takes longer, we'll refund the month.\"", note: "Replace \"quick and easy\" with exact time + risk reversal. AI won't commit; you must." },
      ],
      rule: "If your copy avoids the top objection, the reader assumes you know it's a problem. If you name it directly, they assume you've solved it.",
    },
    {
      type: "comparison",
      eyebrow: "WEAK PROOF vs STRONG PROOF",
      title: "Both claims are \"true.\" Only one is believable.",
      subtitle: "Same company, same month, same result \u2014 written two ways.",
      left: {
        title: "AI-Default Proof",
        color: "#EF4444",
        items: [
          { strong: "\"Trusted by leading companies worldwide.\"", note: "Unfalsifiable, unspecific, applies to any competitor." },
          { strong: "\"Proven to deliver results.\"", note: "No number, no timeframe, no case. Reader ignores it." },
          { strong: "\"Industry-recognised solution.\"", note: "Marketing words for \"we have nothing specific to say.\"" },
          { strong: "\"Our customers love us.\"", note: "Zero signal. Every company claims this." },
        ],
      },
      right: {
        title: "Specific Proof (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: "\"1,847 Shopify Plus merchants used us in Q3 2025 \u2014 up from 1,122 in Q1.\"", note: "Specific segment + specific number + growth direction." },
          { strong: "\"Median customer: 34% lift in recovered revenue within 42 days.\"", note: "Median (not average) + specific outcome + specific timeframe." },
          { strong: "\"Featured in Shopify's official integration spotlight, Oct 2025. Link \u2192\"", note: "Named authority + dated + verifiable." },
          { strong: "\"G2 rating 4.8 across 412 reviews. NPS +62 (Q3).\"", note: "Specific platform, specific review count, specific score." },
        ],
      },
      footer: "Rule of specific proof: a number, a name, or a date in every line. If you can't point to one, the claim isn't proof.",
    },
    {
      type: "principle",
      num: "02",
      title: "The 5 Forms of Proof \u2014 Ranked by Strength",
      intro: "Not all proof is equal. Buyers weight these 5 categories very differently. The stronger forms dominate the weaker ones \u2014 so when you have a strong form, lead with it.",
      sectionTitle: "Ranked by How Much They Shift a Buyer",
      sections: [
        { heading: "1. Named customer with specific outcome", example: "\"Zendesk cut triage time from 14 min to 2 min in 3 weeks \u2014 Priya Sharma, VP Ops.\"", note: "Single strongest form. Real name + real outcome + role = immediate credibility." },
        { heading: "2. Independent data / audited numbers", example: "\"Stripe processed $47B on infra that never exceeded 12ms p99 in 2025.\"", note: "Numbers the reader could verify externally. AI can't produce these convincingly." },
        { heading: "3. Third-party authority / certification", example: "\"SOC 2 Type II. ISO 27001. HIPAA. Report link \u2192\"", note: "Compliance badges plus a link to the actual report \u2014 not just the logo." },
        { heading: "4. Live demo / screenshot / screen recording", example: "\"Here\u2019s a 47-second Loom of the full backfill running on a 4.2M-row table.\"", note: "Seeing is heavier than hearing. A real screen recording beats 20 testimonials." },
        { heading: "5. Risk reversal", example: "\"Full refund for 30 days. We pay you $500 if setup takes longer than 48 hrs.\"", note: "Not technically \"proof\" but functions as proof: you wouldn't offer it if you didn't believe it." },
      ],
      rule: "One piece of Form-1 proof beats ten pieces of Form-5. If you have a named customer with numbers, put them at the top of the page.",
    },
    {
      type: "table",
      title: "Objection \u2192 The Exact Copy Line That Resolves It",
      subtitle: "Copy-paste-adjust for your own product. Each line names the objection in the reader's voice, then dissolves it with a specific.",
      columns: ["Reader\u2019s Real Objection", "Weak Response", "Strong Copy Line"],
      rows: [
        ["\"This looks expensive.\"", "\"We offer great value.\"", "\"Yes, $1,200/mo. Teams that adopt us recover that in the first 8 days of recovered revenue. Past that, it's pure margin.\""],
        ["\"I don't recognise you.\"", "\"We're a trusted brand.\"", "\"We launched in 2023. 1,847 Shopify Plus stores. Acquired by Pipe Oct 2025. Here's the deal announcement.\""],
        ["\"Will it work for me?\"", "\"It works for everyone.\"", "\"Built specifically for 50\u2013500-seat CS teams using Zendesk + Salesforce. Not for you if you're under 25 seats.\""],
        ["\"Implementation sounds painful.\"", "\"Easy to set up.\"", "\"4-min setup. Average time-to-first-value: 11 minutes. If you're not live in 48 hrs, we refund the month.\""],
        ["\"What if we hate it?\"", "\"We have a satisfaction guarantee.\"", "\"30-day full refund. No \u2018talk to sales\u2019 to cancel \u2014 a single button in settings. 7 customers used it last quarter; we shipped the features they cited.\""],
        ["\"What if you shut down?\"", "\"We are committed long-term.\"", "\"We raised a $24M Series A in Sept 2025, 18-month runway post-round. All exports are CSV/JSON on demand \u2014 your data is yours, always.\""],
      ],
      footer: "Notice every \"Strong\" line contains at least one number, one name, or one specific mechanism. That's the entire trick.",
    },
    {
      type: "table",
      title: "Before \u2192 After: A Pricing Section With Objection Handling",
      subtitle: "Same pricing. Same features. The \"After\" version addresses the 3 objections buyers raise at the commitment moment.",
      columns: ["Before (No Objections Answered)", "After (Objections Answered In Line)", "Objection Handled"],
      rows: [
        ["\"$1,200/month. Start your free trial.\"", "\"$1,200/month \u2014 the average team recovers this in 8 days via reclaimed AE time. See the 30-sec calculator \u2192\"", "Price / ROI"],
        ["\"Get started today.\"", "\"Setup in 4 minutes. Live integrations with HubSpot, Salesforce, Pipedrive. Zero engineering required.\"", "Time / Effort"],
        ["\"Trusted by leading teams.\"", "\"1,847 teams on the plan. 94% NPS after 60 days. Full customer list \u2192\"", "Trust / Credibility"],
        ["\"Cancel anytime.\"", "\"Cancel from settings in one click \u2014 not a sales call. First 30 days: full refund, no questions.\"", "Risk / Commitment fear"],
        ["\"Questions? Contact sales.\"", "\"Common questions: SOC 2 (yes, link), SSO (yes, on all plans), GDPR DPA (auto-signed at checkout).\"", "Procurement / Compliance"],
      ],
      footer: "Objection handling isn't an FAQ at the bottom \u2014 it's a sentence next to the thing being objected to.",
    },
    {
      type: "grid",
      eyebrow: "TRUST SIGNALS THAT ACTUALLY WORK",
      title: "6 Trust Signals, Ranked by Credibility Earned",
      subtitle: "Most pages use all six. Only a few of these actually move buyers. Know the difference.",
      items: [
        { num: "01", title: "Named case study", desc: "Real customer name + real metric + link to a long-form write-up. Single highest-value trust signal on any page.", icon: "\u{1F451}" },
        { num: "02", title: "Audited compliance docs", desc: "SOC 2 Type II, ISO 27001, HIPAA \u2014 with the report link, not just the logo. Procurement teams verify.", icon: "\u{1F510}" },
        { num: "03", title: "Real usage numbers", desc: "\"1,847 teams. 2.4M messages processed this week.\" Live counters are stronger than static claims.", icon: "\u{1F4C8}" },
        { num: "04", title: "Media mentions with dates", desc: "\"TechCrunch, Oct 2025 \u2192\". Dated + linked. A naked logo grid with no links is a negative signal to sophisticated buyers.", icon: "\u{1F4F0}" },
        { num: "05", title: "Specific risk reversal", desc: "\"30-day refund, 1-click, no sales call.\" Generic guarantees are ignored; specific guarantees convert.", icon: "\u{1F6E1}\uFE0F" },
        { num: "06", title: "Public changelog / incidents page", desc: "Transparency about outages and shipped fixes signals a real, operating company. AI-generated pages never have these.", icon: "\u{1F4DC}" },
      ],
      footer: "A single piece of #01 or #02 outranks every logo grid on the internet. Hunt one down before you ship the page.",
    },
    {
      type: "exercise",
      title: "Objection Mapping Challenge",
      intro: "For each vague marketing claim below: (a) name the specific objection it leaves unanswered, (b) write the single copy line that would resolve it with real proof.",
      items: [
        { num: "1", copy: '"Our platform is trusted by thousands of businesses worldwide."', answer: "Unanswered objection: \"What kind of businesses? Anything like me?\" Fix: \"2,400+ DTC brands on Shopify Plus, average store doing $4M\u2013$40M ARR. Full customer list \u2192\"" },
        { num: "2", copy: '"Get started quickly with our easy setup process."', answer: "Unanswered objection: \"How long will this actually take me, realistically?\" Fix: \"Setup in 11 minutes on average. You connect HubSpot, we backfill 12 months of data, you\u2019re live before your next standup. If it takes over 48 hrs, we pay you $500.\"" },
        { num: "3", copy: '"We\'re fully secure and compliant with industry standards."', answer: "Unanswered objection: \"Which standards? Who audited? Can procurement verify?\" Fix: \"SOC 2 Type II (auditor: Prescient Assurance, Oct 2025). ISO 27001 renewed Q3. GDPR DPA auto-signs at checkout. Full reports here \u2192\"" },
        { num: "4", copy: '"Our customers love us and see great results."', answer: "Unanswered objection: \"Which customers? What results? Can you name one?\" Fix: \"Priya at Zendesk cut triage time from 14 min to 2 min in 3 weeks. Case study + her 7-min Loom \u2192.\"" },
      ],
    },
  ],
};
