// Psychology of Persuasion - Module 1 for Copywriting
// Rich slide data with layout types for the RichSlide renderer

export const psychologyModule = {
  id: "psych01",
  title: "The Psychology of Persuasion",
  type: "Rich Module",
  duration: "90 min",
  desc: "Master the cognitive biases, emotional triggers, and decision-making science behind every high-converting piece of copy.",
  topics: ["Reciprocity", "Scarcity & Urgency", "Social Proof", "Anchoring", "Loss Aversion", "Authority"],
  slides: [
    {
      type: "cover",
      module: "MODULE 1",
      title: "The Psychology",
      titleAccent: "of Persuasion",
      subtitle: "The cognitive biases, emotional triggers, and decision-making science that power every high-converting piece of copy ever written.",
      meta: "Advanced Copywriting Training  |  Module 1 of 6  |  18 Slides",
    },
    {
      type: "stats",
      eyebrow: "WHY PSYCHOLOGY?",
      title: "Before you write a single word",
      intro: "You need to understand how people make decisions.",
      stats: [
        { num: "95%", label: "of purchasing decisions are subconscious" },
        { num: "8 sec", label: "average attention span of online readers" },
        { num: "70%", label: "of buying experiences are based on feeling" },
      ],
      subheading: "What This Means for Copywriters",
      bullets: [
        "Logical arguments alone don't convert — you must trigger emotional responses first, then justify with logic.",
        "Readers make split-second judgments about your copy — your first line does 80% of the work.",
        "Persuasion isn't manipulation — it's aligning your message with how the human brain naturally processes decisions.",
        "The same principles used by Booking.com, Apple, and Amazon are available to every copywriter who studies them.",
      ],
    },
    {
      type: "grid",
      eyebrow: "CORE FRAMEWORK",
      title: "The 6 Core Principles",
      subtitle: "Based on Robert Cialdini's research + modern neuromarketing findings",
      items: [
        { num: "01", title: "Reciprocity", desc: "Give value first to create obligation", icon: "\u{1F381}" },
        { num: "02", title: "Scarcity & Urgency", desc: "Limited supply or time drives action", icon: "\u23F3" },
        { num: "03", title: "Social Proof", desc: "People follow what others are doing", icon: "\u{1F465}" },
        { num: "04", title: "Anchoring", desc: "First number frames all that follow", icon: "\u2693" },
        { num: "05", title: "Loss Aversion", desc: "Fear of losing > desire to gain", icon: "\u{1F6E1}\uFE0F" },
        { num: "06", title: "Authority", desc: "Experts and credentials build trust", icon: "\u{1F3C5}" },
      ],
      footer: "We'll now deep-dive into each principle with real-world examples and UI screenshots.",
    },
    {
      type: "principle",
      num: "01",
      title: "Reciprocity — Give First, Sell Second",
      intro: "When someone gives us something of value, we feel psychologically obligated to give something back. In marketing: give free value, earn attention, convert.",
      sectionTitle: "How to Apply in Your Copy",
      sections: [
        { heading: "Lead Magnets", example: '"Download our free 47-page SEO checklist"', note: "Free high-value content creates obligation" },
        { heading: "Free Tools", example: '"Grade your website for free — no signup"', note: "Utility builds goodwill before the pitch" },
        { heading: "Valuable Content", example: '"Here are 5 strategies we used to grow 300%"', note: "Sharing proprietary knowledge earns trust" },
        { heading: "Free Trials", example: '"Try everything free for 14 days"', note: "Experiencing value makes cancelling feel like loss" },
      ],
      example: {
        brand: "HubSpot",
        label: "REAL EXAMPLE",
        bullets: [
          "Website Grader (free, no signup)",
          "Email Signature Generator",
          "Blog Ideas Generator",
          "Invoice Template Generator",
          "Marketing Plan Template",
        ],
        result: "HubSpot generates 6M+ monthly visitors with free tools. These users convert to paid CRM customers at 3–5x the rate of cold traffic.",
      },
      rule: "The value of your free content should be so high that people feel guilty NOT buying from you.",
    },
    {
      type: "principle",
      num: "02",
      title: "Scarcity & Urgency — The FOMO Engine",
      intro: "When something is limited in quantity or time, its perceived value increases. We fear missing out more than we desire gaining.",
      sectionTitle: "Two Types of Scarcity",
      twoCol: {
        left: {
          title: "Quantity Scarcity",
          items: [
            '"Only 3 left in stock"',
            '"Limited to the first 100 signups"',
            '"Only 2 rooms left at this price"',
          ],
        },
        right: {
          title: "Time Urgency",
          items: [
            '"Sale ends midnight Friday"',
            '"Early bird pricing expires in 48 hours"',
            '"This offer won\'t last"',
          ],
        },
      },
      example: {
        brand: "Booking.com",
        label: "LIVE EXAMPLE",
        heading: "Grand Hotel Amsterdam",
        price: "$189/night",
        oldPrice: "$249",
        bullets: [
          "🔥 Only 2 rooms left at this price!",
          "👁 43 people looking at this right now",
          "✓ Booked 6 times in the last 24 hours",
          "⏱ Last booked 12 minutes ago",
        ],
        result: "These triggers increase booking conversions by 2.5–4x",
      },
    },
    {
      type: "example",
      title: "Scarcity in Action",
      subtitle: "Amazon's Product Page Anatomy",
      product: {
        brand: "amazon",
        name: "Bose QuietComfort 45 Headphones",
        rating: "12,847 ratings",
        price: "$279.00",
        oldPrice: "$329.00",
        discount: "-15%",
        stock: "Only 4 left in stock — order soon.",
        delivery: "FREE delivery Wednesday, April 16",
        urgency: "Order within 2 hrs 14 min",
        badges: ["Amazon's Choice", "#1 Best Seller in Headphones"],
      },
      triggersTitle: "Psychology Triggers Identified",
      triggers: [
        { name: "Anchoring", desc: "Struck-through $329 makes $279 feel like a deal. The -15% badge reinforces savings." },
        { name: "Scarcity", desc: "\"Only 4 left\" triggers loss aversion. Creates urgency to buy before stock runs out." },
        { name: "Urgency", desc: "\"Order within 2 hrs 14 min\" creates a ticking clock. Countdown = action pressure." },
        { name: "Social Proof", desc: "12,847 ratings + \"Amazon's Choice\" + \"#1 Best Seller\" = mass validation." },
      ],
    },
    {
      type: "principle",
      num: "03",
      title: "Social Proof — The 5 Types Every Copywriter Must Know",
      sectionTitle: "The 5 Types",
      sections: [
        { heading: "User Numbers", example: '"Join 2M+ professionals who use Slack daily"', note: "Massive numbers = safety in numbers. If millions trust it, it must work." },
        { heading: "Testimonials", example: '"This tool saved us $43,000 in Q3 alone" — Sarah K., CMO at Acme', note: "Named, titled, specific testimonials with numbers are 3x more credible." },
        { heading: "Expert Endorsement", example: '"Recommended by 9/10 dermatologists"', note: "Authority figures lend their credibility. Works in B2B and B2C." },
        { heading: "Media Logos", example: '"As featured in Forbes, TechCrunch, WSJ"', note: "Brand association — their reputation transfers to your product." },
        { heading: "Case Studies", example: '"How Company X grew revenue 412% in 6 months"', note: "Detailed proof with a narrative arc. The most convincing form of social proof." },
      ],
      rule: "Always use the most specific proof available. \"10,847 users\" beats \"thousands of users\" every time.",
    },
    {
      type: "comparison",
      eyebrow: "TESTIMONIAL BEST PRACTICES",
      title: "Social Proof in Action",
      subtitle: "What makes a testimonial convert vs. fall flat",
      left: {
        title: "Effective",
        color: "#10B981",
        items: [
          { strong: '"This tool saved us $43,000 in Q3"', note: "Specific numbers > vague praise" },
          { strong: "— Sarah K., CMO at Acme Inc.", note: "Full name + title + company = credible" },
          { strong: '"We tried 6 alternatives before..."', note: "Journey context makes it relatable" },
          { strong: '"Revenue grew 412% in 6 months"', note: "Measurable outcomes beat feelings" },
        ],
      },
      right: {
        title: "Weak",
        color: "#EF4444",
        items: [
          { strong: '"Great product, love it!"', note: "No specificity or proof" },
          { strong: "— S.K.", note: "Anonymous = no credibility transfer" },
          { strong: '"We needed a tool and found one"', note: "No journey, no emotion" },
          { strong: '"Our business improved"', note: "Feelings without measurement" },
        ],
      },
    },
    {
      type: "principle",
      num: "04",
      title: "Anchoring — The First Number Wins",
      intro: "The first piece of information we receive becomes the reference point for all subsequent judgments. In pricing: show the expensive option first.",
      pricing: {
        label: "REAL PATTERN: SaaS Pricing Page (3-Tier Anchoring)",
        tiers: [
          { name: "Basic", price: "$29", period: "/month", features: ["5 projects", "10 GB storage", "Email support", "Basic analytics"] },
          { name: "Professional", price: "$79", period: "/month", badge: "MOST POPULAR", highlight: true, features: ["Unlimited projects", "100 GB storage", "Priority support", "Advanced analytics", "Team collaboration", "API access"] },
          { name: "Enterprise", price: "$249", period: "/month", features: ["Everything in Pro", "Unlimited storage", "Dedicated account mgr", "Custom integrations", "SLA guarantee"] },
        ],
      },
      rule: "$249/mo makes $79/mo feel like a bargain. The \"Most Popular\" badge uses social proof to nudge users to the middle tier.",
    },
    {
      type: "comparison",
      num: "05",
      eyebrow: "LOSS AVERSION",
      title: "Fear of Missing > Desire for Gaining",
      subtitle: "People feel the pain of losing something 2x as strongly as the pleasure of gaining something of equal value.",
      left: {
        title: "Gain Framing (Weaker)",
        color: "#999",
        items: [
          { strong: '"Save 20% with our annual plan"' },
          { strong: '"Get faster page load times"' },
          { strong: '"Earn more with our investment tools"' },
          { strong: '"Improve your team\'s productivity"' },
        ],
      },
      right: {
        title: "Loss Framing (Stronger)",
        color: "#7C3AED",
        items: [
          { strong: '"Stop wasting $1,200/yr — switch to annual"' },
          { strong: '"Every slow second costs you 7% in conversions"' },
          { strong: '"You\'re leaving $4,300/yr on the table"' },
          { strong: '"Your team loses 6 hrs/week to this problem"' },
        ],
      },
      footer: "Reframe every benefit as a loss avoided. \"Save time\" → \"Stop losing 6 hours every week\" | \"Make more money\" → \"Stop leaving $4,300/year on the table\"",
    },
    {
      type: "principle",
      num: "06",
      title: "Authority — Trust Signals That Convert",
      intro: "People defer to experts and authority figures. Position your brand, product, or content as the credible, trusted choice.",
      sectionTitle: "Trust Signal Toolkit",
      grid: [
        { heading: "Credentials & Certifications", example: '"ISO 27001 Certified  |  SOC 2 Compliant"', note: "Footer, security pages, checkout" },
        { heading: "Expert Endorsements", example: '"Recommended by Dr. Sarah Lin, Stanford"', note: "Hero section, product pages" },
        { heading: "Media Mentions", example: '"As featured in Forbes, WSJ, TechCrunch"', note: "Below hero, trust bar" },
        { heading: "Data & Research", example: '"Based on 14,000+ user studies"', note: "Feature descriptions, claims" },
        { heading: "Years of Experience", example: '"Serving 200,000+ customers since 2009"', note: "About page, footer, hero" },
        { heading: "Guarantees", example: '"30-day money-back guarantee — no questions"', note: "CTAs, checkout, pricing page" },
      ],
      rule: "Trust signals work best at decision points — near CTAs, on pricing pages, and during checkout.",
    },
    {
      type: "comparison",
      title: "Emotional vs Rational Triggers",
      subtitle: "The best copy uses BOTH — emotion to trigger action, logic to justify it.",
      left: {
        title: "Emotional Triggers",
        color: "#EC4899",
        items: [
          { strong: "Fear", note: '"Don\'t let hackers steal your customers\' data"' },
          { strong: "Desire", note: '"Imagine waking up to sales while you sleep"' },
          { strong: "Belonging", note: '"Join the community of top 1% marketers"' },
          { strong: "Pride", note: '"Build something your team will be proud of"' },
          { strong: "Frustration", note: '"Tired of tools that overpromise and underdeliver?"' },
          { strong: "Aspiration", note: '"Become the leader your team deserves"' },
        ],
      },
      right: {
        title: "Rational Justifiers",
        color: "#2563EB",
        items: [
          { strong: "Data", note: '"97% uptime SLA with 24/7 monitoring"' },
          { strong: "ROI", note: '"Average customer sees 312% ROI in 90 days"' },
          { strong: "Comparison", note: '"50% faster than Competitor X at half the price"' },
          { strong: "Specs", note: '"256-bit encryption, GDPR compliant, SOC 2"' },
          { strong: "Process", note: '"3 simple steps: Import → Configure → Launch"' },
          { strong: "Guarantee", note: '"30-day money-back guarantee. Zero risk."' },
        ],
      },
      footer: "FORMULA: Lead with emotion (headline, opening) → Back with logic (features, data, guarantees) → Close with emotion (CTA, urgency)",
    },
    {
      type: "exercise",
      title: "Practical Exercise — Identify the Triggers",
      intro: "Read each piece of copy below and identify which psychological principle(s) are being used.",
      items: [
        { num: 1, copy: '"Join 847,000+ designers who get our weekly newsletter — free forever."', answer: "Social Proof (847,000+) + Reciprocity (free)" },
        { num: 2, copy: '"Was $199/year — now $99/year. This price disappears Friday at midnight."', answer: "Anchoring ($199→$99) + Scarcity (Friday deadline)" },
        { num: 3, copy: '"Every day without this tool, you\'re losing $47 in wasted ad spend."', answer: "Loss Aversion ($47/day) + Urgency (every day)" },
        { num: 4, copy: '"Recommended by Harvard Business Review. Try risk-free for 30 days."', answer: "Authority (HBR) + Loss Aversion reversal (risk-free)" },
      ],
    },
    {
      type: "table",
      title: "Persuasion Psychology — Cheat Sheet",
      subtitle: "Pin this. Reference it before writing every piece of copy.",
      columns: ["Principle", "Trigger", "Copy Example", "Best Placement"],
      rows: [
        ["Reciprocity", "Give first", '"Download our free 47-page guide"', "Lead magnets, content, free trials"],
        ["Scarcity", "Limit supply/time", '"Only 4 left" / "Ends Friday"', "CTAs, product pages, emails"],
        ["Social Proof", "Show others doing it", '"Join 50,000+ marketers"', "Hero, testimonials, trust bars"],
        ["Anchoring", "Set price reference", '"Was $497 — Now $197"', "Pricing pages, offers, ads"],
        ["Loss Aversion", "Frame as loss avoided", '"Stop losing $47/day"', "Headlines, PAS agitation, CTAs"],
        ["Authority", "Show credentials", '"Recommended by Forbes"', "Trust bars, checkout, footer"],
      ],
      footer: "GOLDEN RULE: Never use just one principle. The most powerful copy layers 2-3 triggers in every section. Scarcity + Social Proof + Anchoring is the classic conversion trifecta.",
    },
    {
      type: "quiz",
      title: "Module 1 Quiz — Part 1",
      questions: [
        { q: 'Which principle does "Only 2 seats remaining" leverage?', opts: ["Reciprocity", "Scarcity", "Anchoring", "Social Proof"], correct: 1 },
        { q: "A company offers a free SEO audit before pitching their $2,000/mo service. Which principle?", opts: ["Anchoring — high price first", "Scarcity — limited audit", "Reciprocity — free value creates obligation", "Social Proof — others used it"], correct: 2 },
        { q: '"Stop losing $47/day in wasted ad spend" uses which framing technique?', opts: ["Gain framing", "Authority signaling", "Loss aversion framing", "Social proof"], correct: 2 },
      ],
    },
    {
      type: "quiz",
      title: "Module 1 Quiz — Part 2",
      questions: [
        { q: "On a pricing page, showing the $249/mo plan first before the $79/mo plan uses:", opts: ["Scarcity", "Loss Aversion", "Anchoring", "Reciprocity"], correct: 2 },
        { q: "Which testimonial is most effective?", opts: ['"Great product, love it!" — S.K.', '"This tool saved us $43,000 in Q3 alone" — Sarah K., CMO at Acme', '"5 stars, would recommend" — Anonymous', '"It works pretty well for what we need" — Marketing Dept.'], correct: 1 },
        { q: "The formula for persuasive copy structure is:", opts: ["Logic → Emotion → Logic", "Emotion → Logic → Emotion (lead with feeling, justify, close with feeling)", "All emotion, no logic", "All logic, no emotion"], correct: 1 },
      ],
      scoring: "6/6 = Expert  |  5/6 = Advanced  |  4/6 = Proficient  |  3/6 = Review  |  ≤2 = Re-study this module",
    },
    {
      type: "takeaways",
      title: "Module 1 — Key Takeaways",
      items: [
        "95% of decisions are subconscious — your copy must trigger emotional responses before logical justification.",
        "Layer 2-3 psychological principles per section. Scarcity + Social Proof + Anchoring is the conversion trifecta.",
        "Specificity is persuasion: \"12,847 users\" beats \"thousands\" every time. Real numbers = real trust.",
        "Reframe every benefit as a loss avoided — \"Stop losing $47/day\" outperforms \"Save money\" by 2x.",
        "Authority signals belong at decision points — near CTAs, pricing pages, and checkout flows.",
        "Give before you ask. The more valuable your free content, the stronger the reciprocity obligation.",
        "Test everything. Psychology gives you hypotheses; data gives you answers.",
      ],
      next: "NEXT UP: Module 2 — Headline Mastery  |  Proven formulas that turn scrollers into readers",
    },
  ],
};
