// Sales Fundamentals — Module 12: Sales Career & Leadership
export const sellCareerModule = {
  id: "sell12",
  title: "Sales Career & Leadership",
  type: "Rich Module",
  duration: "90 min",
  desc: "The long-game capstone. The four stages of a sales career, what compounds, when to move and when to stay, the manager transition, and the moves that separate a 3-year rep from a 30-year sales career that compounds.",
  topics: ["Career Stages (SDR → CRO)", "What Compounds in Sales", "The Manager Transition", "Reputation Management", "When to Move vs Stay", "Leading a Team"],
  quiz: [
    { q: "3-year top-AE. VP offers you: (A) Senior AE at 110% OTE + bigger accounts, or (B) Sales Manager at 100% OTE + 6 reports. Which compounds more over 10 years?", opts: ["A always — bigger accounts = bigger deals = more career IP", "It's conditional. B compounds more IF you genuinely prefer coaching over closing — the rep-to-manager transition is the hardest to make later, so earlier is leverage. But if you don't prefer coaching, B is a career trap and A is the right call", "A always — money", "B always — leadership track"], correct: 1 },
    { q: "You left Company A after 4 strong years. At Company B in Year 2, a Company A customer reaches out asking about your new product. The highest-compounding move:", opts: ["Sell fast — warm lead", "Move fast AND deliberately document this as a pattern: \"customer relationships travel across employers.\" This is the compound you want to replicate 10 more times over 10 years. Naming the pattern lets you build habits that produce it repeatedly", "Decline — potential conflict", "Refer internally without claiming credit"], correct: 1 },
    { q: "A first-time Sales Manager is personally closing 30% of their team's deals in Q1. The CRO's correct diagnosis:", opts: ["Great hire — pitching in", "Red flag. The Manager is still in rep identity — doing the team's work instead of developing the team. In 6 months, team attainment will be LOWER, not higher, than if the Manager had stepped back and coached. Manager productivity ≠ team productivity compounding", "Normal — new managers over-contribute", "Wait and see"], correct: 1 },
    { q: "6-year AE, considering a move for 40% more base. The first question to ask yourself:", opts: ["What's the territory?", "What will I know how to do in Year 10 in each scenario — stay vs move? And specifically: who will I work FOR (manager) and WITH (peers)? Comp is a floor; skill acquisition and network are the real compound", "What's the product?", "What's the quota attainment rate?"], correct: 1 },
    { q: "Your personal playbook (templates, ROI math, discovery scripts) lives scattered across Google Docs, Notion, and memory. Over a 20-year career the real cost is:", opts: ["Minor — you remember what you need", "Every company change, you lose ~3-4 months recreating IP. Across 4-5 company moves = 1.5-2 years of net-lost productivity, plus a visible signal to future managers that your craft isn't systematized. Documented + version-controlled IP is the single highest-ROI habit a long-career seller can build", "Some inconvenience", "Keep it unorganized — it's a trade secret"], correct: 1 },
    { q: "You're offered: CRO at a $40M ARR company vs VP Sales at a $200M ARR company — same base, similar comp trajectory. The harder-but-often-better-for-compounding choice is:", opts: ["CRO at the smaller — bigger title wins", "VP at the larger. CRO-at-$40M typically means doing many functions poorly due to company scale. VP-at-$200M means mastering a specific function at scale. Next-move optionality is broader from domain depth than from an earlier title — titles can always be acquired later; deep, at-scale skill can't be retrofitted", "Always take the higher title", "Always take the larger company"], correct: 1 },
  ],
  slides: [
    { type: "cover", module: "MODULE 12", title: "Sales Career", titleAccent: "& Leadership", subtitle: "The long-game capstone. Four stages, what compounds, the manager transition, the moves that separate a 3-year rep from a 30-year career.", meta: "Sales Fundamentals  |  Module 12  |  7 Slides" },
    { type: "stats", eyebrow: "THE COMPOUNDING SALES CAREER", title: "A 20-year sales career earns 8× a 5-year sales career — when built deliberately", intro: "Most sales careers are a series of disconnected jobs. A compounding career is different: each role is a capstone on the last, each customer relationship travels with you, each playbook refines. The top 1% of sellers plan their career like their best deals — with intent.", stats: [
      { num: "8×", label: "earnings delta between a 20-yr sales career built on compounding reputation + relationships vs a 5-yr career reset by poor transitions" },
      { num: "43%", label: "of senior AE roles are filled by internal or referred candidates — which is why reputation + network matter more than job boards" },
      { num: "67%", label: "of first-time sales managers fail within 18 months — almost always from continuing to sell instead of coaching" },
    ], subheading: "What Compounding Sellers Do Differently", bullets: [
      "Treat every customer, every colleague, every lost deal as a long-term reputation deposit",
      "Choose next roles based on who they’ll work with + what they’ll learn, not title",
      "Build personal IP — playbooks, templates, frameworks — that travel across employers",
      "Stay technically sharp even as they move into leadership",
      "Invest in the next generation of sellers as a multiplier, not a cost",
    ] },
    { type: "grid", eyebrow: "THE 4 STAGES OF A SALES CAREER", title: "What each stage actually requires — and what to optimise for", subtitle: "Every stage is about a different skill. Reps who stall usually haven’t made the skill transition the next stage demands.", items: [
      { num: "01", title: "SDR / BDR (Yr 0–2)", desc: "Volume, resilience, basic outreach mechanics. Optimise for reps (activity) + habits. Move up when you’re in the top quartile of team activity + conversion.", icon: "\u{1F331}" },
      { num: "02", title: "AE (Yr 2–6)", desc: "Closing, deal craft, quota attainment. Optimise for reputation inside the company + a book of customer relationships. The money years.", icon: "\u{1F3AF}" },
      { num: "03", title: "Senior AE / Strategic AE (Yr 6–10)", desc: "Complex deals, multi-stakeholder, enterprise motion. Optimise for deal sophistication + peer mentorship. Earnings peak for ICs here.", icon: "\u{1F3C6}" },
      { num: "04", title: "Manager → Director → VP → CRO (Yr 8+)", desc: "Leading teams, building systems, hiring. Optimise for team attainment + people development. Hardest identity transition in sales.", icon: "\u{1F451}" },
    ], footer: "Rule: most reps stall between AE and Senior AE. The jump is from closing well to running complex enterprise committees well — different skill, different habits." },
    { type: "principle", num: "01", title: "What Actually Compounds in a Sales Career", intro: "Most careers feel like a series of resets — new company, new product, new territory, start over. Compounding careers don’t reset because the core assets travel with you. Here are the four that actually compound.", sectionTitle: "The 4 Compounding Assets", sections: [
      { heading: "1. Customer Relationships — they hire you at their next company", example: "VP Ops you closed in 2019 moves to a new company in 2024 → you get the warm intro. Over 20 years, this is most of your top-of-funnel.", note: "Every deal closed is not just revenue — it’s a future relationship asset. Treat the customer post-close, not just pre-close." },
      { heading: "2. Reputation — the quiet referential network", example: "CS teams, legal teams, SEs, peers who worked with you now recommend you for roles you never applied to.", note: "Poor reputation compounds faster than good reputation — one “scorched earth” deal outweighs ten clean ones in internal word-of-mouth." },
      { heading: "3. Personal IP — playbooks, templates, frameworks", example: "Your discovery template, your ROI calculator, your champion-letter playbook — refined over 10 years. Each new role imports it. Onboarding to a new company takes 3 months instead of 12.", note: "Write it down. Keep it in Notion / Drive. Version-control it. This is the real portable asset." },
      { heading: "4. Network across functions — not just customers", example: "Your Year 3 SE is a VP of Product in Year 10; your legal counterpart becomes a CFO; your CS lead becomes a CRO. These people recruit you.", note: "Invest in every function, not just the customer. The people who sit next to you become the people who hire you." },
    ], rule: "The career is a compounding asset — but only if you build deliberately. Sellers who treat every deal as transactional lose compounding power. Sellers who treat every interaction as long-term deposit outearn them 5–10× over 20 years." },
    { type: "comparison", eyebrow: "PLATEAU vs COMPOUND", title: "Two careers after 15 years", subtitle: "Same starting point, same intelligence, same quota. Different trajectories. The difference is the habits compounded by each.", left: { title: "The Plateau Rep", color: "#EF4444", items: [
      { strong: "Year 3: top AE at Company A. Closed $4M. Got a 10% raise.", note: "Strong IC year. Same IC role available at Company B for 30% more comp." },
      { strong: "Year 5: jumped to Company B for +30% base. Reset territory, reset playbook.", note: "First year at B: 68% attainment. Lost momentum. Earnings net-down year over year." },
      { strong: "Year 9: third company jump. Still an AE. Plateaued at mid-AE comp tier.", note: "Industry sees a “good closer who can’t make the senior AE jump.” Recruited less aggressively." },
      { strong: "Year 15: still an AE at company #5. Earnings lower (in real terms) than year 5.", note: "Each job hop reset relationships, reputation, and IP. 15 years of work, 5 years of compounding." },
    ] }, right: { title: "The Compound Rep", color: "#10B981", items: [
      { strong: "Year 3: same $4M at Company A. Stayed one extra year to mentor 2 SDRs + document their playbook.", note: "Same income, but now has personal IP + internal reputation + two junior relationships that will matter in year 8." },
      { strong: "Year 5: moved to Company B — but specifically chose a role working with a CRO who was a Year 3 customer. Mutual trust on day 1.", note: "Onboarding is 90 days instead of 9 months. First year at B: 112% attainment. Compounds from here." },
      { strong: "Year 9: promoted to Senior AE at a new company after a warm customer referral. Running $12M+ deals.", note: "Industry sees a “senior operator with a real book of business.” Recruited aggressively for leadership tracks." },
      { strong: "Year 15: VP of Sales at a company where 4 customers from Year 3 still do business with them. Earnings 5–8× Year 5.", note: "Compound. The career IS the asset. Relationships from Year 1 still paying dividends in Year 15." },
    ] }, footer: "Rule: every decision about the next 18 months should be weighed against the next 15 years. The job that pays 30% more but resets your compounding assets is usually the worse choice." },
    { type: "table", title: "The Manager Transition — What Actually Changes", subtitle: "The rep-to-manager jump is the hardest identity shift in a sales career. These are the 5 specific things that must change in the first 90 days.", columns: ["Dimension", "As a Rep", "As a Manager"], rows: [
      ["Scorecard", "Personal attainment", "Team attainment — your number is the sum of theirs"],
      ["Time allocation", "80% in live deals, 20% admin", "20% in live deals (only when escalated), 60% coaching, 20% recruiting + ops"],
      ["Deal urge", "Close it yourself when it’s stuck", "Coach the rep to close it — even when it costs you a deal you could have saved"],
      ["Recognition", "Hitting the board with your name", "Watching the team hit the board with their names, not yours"],
      ["IP use", "Your own playbooks", "Your playbooks become the team’s; you systematise, not just execute"],
    ], footer: "Rule: if after 90 days as a manager you’re still the team’s top closer, you’re failing at management. The job has changed." },
    { type: "exercise", title: "Plan Your 10-Year Arc", intro: "Most sellers plan the next 12 months. Compound sellers plan the next 10 years backward from the career they want.", items: [
      { num: "1", copy: "Write your 10-year aspiration in one sentence. Role, company-type, team-size, approximate comp band.", answer: "Example: “In 10 years I want to be VP of Sales at a $50–200M ARR B2B company, leading a team of 15–25 AEs, earning $450K–700K OTE.” Specific beats aspirational." },
      { num: "2", copy: "Work backward: what 3 roles get you there? What skill does each role teach?", answer: "Example: Year 3–6: Enterprise AE (complex deal skill). Year 6–9: Sales Manager (team-leading skill). Year 9+: Director/VP (org-building skill). Each role chosen for the skill transition, not just the title / money." },
      { num: "3", copy: "Identify the people you already know who have done this path. Reach out to 3 of them in the next 2 weeks — not to ask for a job, just for a 20-min conversation.", answer: "You’ll get one thing wrong in your plan. Each conversation corrects one. Three conversations = a much sharper plan. Repeat quarterly." },
      { num: "4", copy: "Identify the one compounding asset you are NOT currently investing in (customer relationships post-close, personal IP documentation, cross-function network). Build the habit this quarter.", answer: "Most sellers are solid on 2 of the 4 compounding assets and weak on 2. The weakest one is usually the highest-leverage to invest in. Start with one weekly habit — 30 min a week compounds over a decade." },
    ] },
  ],
};
