// Social Media Marketing — Day 3: Content Strategy & Planning
export const smmDay3Module = {
  id: "smm03",
  title: "Day 3 — Content Strategy & Planning",
  type: "Rich Module",
  duration: "5h",
  desc: "From the daily “what should I post?” panic to a 30-day plan that runs itself. Pillars, the 80/20 value rule, a real content calendar, and a batch creation workflow that survives a busy week.",
  topics: ["Content Pillars", "The 80/20 Rule", "The Five Content Types", "30-Day Calendar", "Batch Creation Workflow", "Posting Frequency Mistakes"],
  quiz: [
    { q: "Isatu, a Freetown bakery owner, plans her week as: Mon — “20% off sourdough”. Tue — “New weekend menu, order now”. Wed — “Last slots for Eid orders”. Thu — “DM us for bulk discount”. Fri — “Flash sale, 6 hours only.” Apply the 80/20 rule. What’s wrong and what’s the fix?", opts: ["The week is fine — 5 posts is the right cadence; just add a Saturday promo too", "She’s posting at the wrong times of day — fix the schedule, not the content", "Her ratio is reversed — 100% ask, 0% value. Followers will unfollow within a week. Replace 4 of the 5 posts with value (sourdough science, 5am bakery footage, customer story, seasonal tip), keep one promo — the value posts earn the right to sell", "She needs more discounts to compete — the content is right, the prices are wrong"], correct: 2 },
    { q: "On Day 3, Hawa brainstorms 10 things she could teach about her catering business. Day 3 says: group them into 3 themes, name each in two words — those become her pillars. Why does this method work, vs simply picking pillars off a generic list?", opts: ["Pillars are random — the list method is just as good", "Generic lists are faster and produce identical pillars anyway", "Because pillars aren’t invented; they’re discovered. Pillars pulled from her own 10 ideas reflect what her business actually owns and what she can sustainably create about — generic pillars produce generic content because they were never tied to her specifics", "Generic lists work better — they’re proven across industries"], correct: 2 },
    { q: "A trainee says: “I’ll post once a day for 30 days straight — maximum reach.” Looking at her current cadence (about 3 posts a month) and her workload (full-time job, two children), Day 3’s most accurate response is:", opts: ["Daily is the only frequency the algorithm rewards — commit", "Daily ambition is the #1 calendar killer. She’s promising daily when she can sustain 3 a week. Pick a frequency she can actually hold for 90 days, batch-create on weekends, and add a buffer — a sustained 3/week beats an abandoned 7/week every time", "Frequency doesn’t matter as long as content quality is high", "She should outsource posting to free up the time"], correct: 1 },
    { q: "Mariama spent Saturday morning writing one caption, then stopped to take one photo, then opened Canva to design one graphic, then wrote the next caption, then took the next photo… four hours later she’s produced 3 posts and is exhausted. What does Day 3’s batch creation workflow say she should have done?", opts: ["Started earlier in the morning when she’s fresher", "Hire someone to do the content for her", "Block the same Saturday morning into four sequential blocks — WRITE all 30 captions in one sitting, then SHOOT all 30 photos in one session (same lighting), then EDIT all together in Canva, then SCHEDULE everything in Meta Business Suite. Context-switching kills consistency — doing one thing 30 times beats doing 30 things once", "Spread the work across 30 short daily sessions instead of one Saturday"], correct: 2 },
    { q: "Looking at the calendar template column — Date, Pillar, Format, Hook Idea, Visual, Status — a trainee wants to drop the “Pillar” column to simplify her sheet. What’s the strongest argument from Day 3 for keeping it?", opts: ["The Pillar column is just admin — she’s right to drop it", "It’s the column that turns the calendar from a posting list into a balanced strategy. Without it, she can’t tell at a glance whether the month is leaning too hard on one theme; pillar tagging is what makes the 80/20 rule and pillar balance enforceable across 30 days", "Keeping it lets her look professional", "It helps Instagram’s algorithm rank her posts higher"], correct: 1 },
    { q: "A trainee writes a beautiful 30-day calendar on Sunday, then by Wednesday she’s already posted off-script three times because something “more exciting came up.” What does Day 3’s mindset say is happening, and what’s the fix?", opts: ["Strategy beats inspiration. ‘Something more exciting’ is the same reactive instinct that produced the original ‘what should I post today?’ panic. The calendar exists to override that instinct — either the new idea fits a pillar (slot it in next week), or it doesn’t (drop it)", "She’s right to follow inspiration — calendars are too rigid", "She should build a separate calendar for spontaneous posts", "The calendar should be redone every Wednesday"], correct: 0 },
  ],
  slides: [
    { type: "cover", module: "DAY 3", title: "Content Strategy &", titleAccent: "Planning", subtitle: "From the daily “what should I post?” panic to a 30-day plan that runs itself.", meta: "Regium Touch × Aurora Foundation  |  Day 3  |  7 Slides" },
    { type: "stats", eyebrow: "WHY CONTENT STRATEGY DECIDES CONSISTENCY", title: "When “what should I post today?” stops being a question, you’ve graduated from posting to marketing", intro: "The daily “what should I post?” question is the single biggest reason small businesses give up on social media. Today, we make sure you never have to ask it again — by replacing the question with pillars, a ratio, and a 30-day calendar.", stats: [
      { num: "83%", label: "of small business owners say their biggest social media struggle is consistency — not creativity, not platforms, consistency" },
      { num: "80/20", label: "the value-to-ask ratio that keeps followers and earns the right to sell" },
      { num: "30 Days", label: "of content planned in one Sunday afternoon — then forget the question ‘what should I post?’ for a month" },
    ], subheading: "What Strong Content Planners Do Differently", bullets: [
      "Run on 3–5 named pillars — every post answers ‘which pillar does this support?’",
      "Hold the 80/20 rule deliberately — most posts give, some posts ask",
      "Mix all five content types (educational, behind-the-scenes, social proof, promotional, entertaining) across the month",
      "Plan the whole month on one Sunday and batch-create in 4 sequential blocks (write, shoot, edit, schedule)",
      "Pick a posting frequency they can sustain for 90 days, not the one that sounds impressive on Day 1",
    ] },
    { type: "grid", eyebrow: "THE FOUR PIECES OF A WORKING STRATEGY", title: "The system that replaces ‘what should I post today?’", subtitle: "Pillars decide the themes. The ratio decides the mix. The calendar decides the schedule. Batch creation decides whether it actually gets done.", items: [
      { num: "01", title: "Content Pillars", desc: "The 3–5 themes your business owns. Discovered by brainstorming 10 things you could teach, then grouping into 3 two-word themes — not picked off a generic list.", icon: "\u{1F3DB}️" },
      { num: "02", title: "The 80/20 Rule", desc: "80% value (educational, behind-the-scenes, social proof, entertaining) — 20% ask (offers, launches, sales). Reverse this and you’ll be unfollowed within a week.", icon: "⚖️" },
      { num: "03", title: "30-Day Calendar", desc: "Date, Pillar, Format, Hook Idea, Visual, Status — six columns, one row per post. Spend a Sunday afternoon filling it; forget ‘what to post’ for a month.", icon: "\u{1F4C5}" },
      { num: "04", title: "Batch Creation", desc: "Write all 30 captions in one block. Shoot all photos in one session. Edit together in Canva. Schedule in Meta Business Suite. Context-switching is the silent killer.", icon: "⚡" },
    ], footer: "Rule: skip any of these four and the system collapses by week three. The whole point is to survive busy weeks without going dark." },
    { type: "principle", num: "01", title: "The 80/20 Value Rule — The Ratio That Decides Whether You Keep Followers", intro: "Most posts give. Some posts ask. Reverse the ratio and followers leave inside a week; hold it correctly and they actively wait for your sales posts. The rule is simple to state and ruthless to break — here’s the breakdown.", sectionTitle: "The Five Content Types — and How They Map to 80/20", sections: [
      { heading: "1. Educational — builds authority (VALUE)", example: "How-to posts, tips, explainers. “Why our sourdough takes 24 hours.” “Three signs your skin barrier is damaged.” Teaches before it sells.", note: "The strongest pillar for service businesses and any premium positioning. Educational content earns trust the fastest." },
      { heading: "2. Behind-the-scenes — builds trust (VALUE)", example: "Process, people, place. “5am at the bakery — first bake of the day.” “Meet Aminata, who packs every order by hand.”", note: "Cheap to produce (the work is already happening) and disproportionately effective — humans connect to humans, not products." },
      { heading: "3. Social proof — builds credibility (VALUE)", example: "Reviews, testimonials, before/after, customer stories. “Adama’s Friday bread tradition.” “How Mariama dropped 3 dress sizes with our 6-week plan.”", note: "The post that closes hesitant buyers. Capture proof actively — don’t wait for it to fall in your DMs." },
      { heading: "4. Promotional — drives revenue (ASK)", example: "Offers, launches, sales. “20% off whole-grain loaves this week.” “Eid week orders open — tap to book.”", note: "This is the 20%. Earned by the value posts that came before. Done well, followers wait for these. Done as 100% of your feed, they unfollow." },
      { heading: "5. Entertaining — builds reach (VALUE)", example: "Memes, trends, humour, light personality content. “When the bakery WiFi goes down on a Saturday morning…”", note: "The cheapest reach there is on Instagram and TikTok. Mix sparingly — over-rely and you become a meme account, not a business." },
    ], rule: "Mix all five across the month. Never lean on just one. Most posts give. Some posts ask. The ones that ask only work because of the ones that gave." },
    { type: "comparison", eyebrow: "AMBITION vs SUSTAINABILITY", title: "What a weak content plan looks like vs a strong one", subtitle: "Most calendars fail in week three because they were written for an aspirational version of you, not the real one. Here’s the difference — and the fix.", left: { title: "Weak Plan (Abandoned by Week 3)", color: "#EF4444", items: [
      { strong: "Daily ambition — promises 7 posts a week from a standing start", note: "She can sustain 3. By week 3 she’s missed 4 days, feels guilty, and the whole calendar collapses. Daily ambition is the #1 calendar killer." },
      { strong: "Same time blindness — posts at 6am because that’s when SHE is free", note: "Her customer scrolls at 9pm. The reach is structurally capped before the content quality even gets a chance to matter." },
      { strong: "All formats at once — reels, carousels, stories, lives, all from week one", note: "Master none. Quality drifts on every format. Better to nail one format for 30 days, then add the next — not all four at once." },
      { strong: "No buffer — schedules exactly when she needs the post", note: "One bad week — sick child, power cut, bad-light day — and the queue runs dry. Burnout follows; abandonment follows that." },
    ] }, right: { title: "Strong Plan (Survives Real Life)", color: "#10B981", items: [
      { strong: "Sustainable cadence — picks 3/week and holds for 90 days", note: "3 posts a week she actually publishes beats 7 posts a week she sometimes does. Algorithm rewards consistency over volume — every time." },
      { strong: "Customer-time aware — posts when her customer scrolls, not when she’s free", note: "Captures peak attention. The same post at the right time can do 4× the engagement of the same post at the wrong time." },
      { strong: "One format mastered — nails carousels for 30 days, then adds reels", note: "Quality compounds. By month 3 she’s genuinely good at one format — worth more than being mediocre at four." },
      { strong: "Buffer of 3–5 posts ahead — always", note: "Bad week, sick day, power cut — the queue keeps running. Buffer is what separates a system from a hope." },
    ] }, footer: "Rule: pick the cadence the realistic version of you can sustain for 90 days. Then build the buffer. Ambition without sustainability is just a slow path to abandonment." },
    { type: "table", title: "The 30-Day Calendar Template — Six Columns That Run a Month", subtitle: "This is the Google Sheets template you’ll fill in today. Every column has one job. Spend one Sunday afternoon on it; forget ‘what should I post?’ for a month.", columns: ["Date / Pillar", "Format & Hook", "Visual / Status"], rows: [
      ["Mon 1 Jun — The craft", "Carousel: “Why our sourdough takes 24 hours”", "Photo: dough rising / Drafted"],
      ["Wed 3 Jun — Behind counter", "Reel: “5am at the bakery — first bake of the day”", "Video: 30-sec process / Filmed"],
      ["Fri 5 Jun — Customer stories", "Single post: “Adama’s Friday bread tradition”", "Photo: customer + bread / Scheduled"],
      ["Mon 8 Jun — Promotional", "Single post: “20% off whole-grain loaves this week”", "Flat lay: discounted bread / Scheduled"],
      ["Wed 10 Jun — Seasonal", "Story: “Eid week orders open — tap to book”", "Graphic: Eid greeting / Idea"],
    ], footer: "Tip: spend one Sunday afternoon filling 30 days. Then forget the question ‘what should I post?’ for a month." },
    { type: "exercise", title: "Today’s Assignment — Pillars, One Live Week, and a Booked Batch Session", intro: "Theory ends here. By the end of Day 3 you have your pillars on paper, week one of your calendar filled in for real posts you’ll publish next week, and a batch creation session booked in your phone calendar.", items: [
      { num: "1", copy: "Find your three pillars. Write your business in one sentence at the top of a blank page. Brainstorm 10 things you could teach about your product, industry, or customer’s life. Group them into 3 themes. Name each theme in two words — those are your pillars.", answer: "You have 3 named pillars on paper. From now on, ‘what should I post?’ becomes ‘which pillar needs a post this week?’ If a future post idea doesn’t fit a pillar, the post is wrong — not the pillar." },
      { num: "2", copy: "Plan one week, live. Open the Google Sheets template in the WhatsApp group. For each of 7 days fill in: pillar, format, hook idea, visual idea. Apply the 80/20 rule — 5–6 value posts, 1–2 promotional. Trade laptops with your partner; she reviews for balance and calls out gaps.", answer: "Week 1 of your 30-day calendar is filled in — not as theory, as a plan you’ll actually post next week. If your partner spots three promotional posts in seven days, the ratio is broken — fix it before lunch." },
      { num: "3", copy: "Book the batch creation session in your phone calendar before you leave today. 3 hours this weekend. Block it as four sequential phases: WRITE all captions (2h), SHOOT all photos (2h — yes the maths is real, you’re working faster on Saturday), EDIT in Canva (1h), SCHEDULE in Meta Business Suite (30 min).", answer: "A batch session that exists in your calendar gets done. One that lives in your head doesn’t. Tell one classmate the time — social accountability lifts completion rates by ~40%. Bring 3 product/service ideas you’ll photograph on Day 4." },
      { num: "4", copy: "Tonight, finish weeks 2, 3, and 4 of your 30-day content calendar at home. Apply the same 80/20 ratio. Cross-check that all 3 of your pillars appear in roughly equal frequency across the month — no pillar should carry more than half the calendar.", answer: "A complete 30-day calendar in writing. From here, the question stops being ‘what should I post?’ and becomes ‘is the photo for Tuesday’s post ready?’ — a logistical question, not an existential one. That shift is the whole point of Day 3." },
    ] },
  ],
};
