// Social Media Marketing — Day 2: Brand Identity & Positioning
export const smmDay2Module = {
  id: "smm02",
  title: "Day 2 — Brand Identity & Positioning",
  type: "Rich Module",
  duration: "5h",
  desc: "The foundation document every post for the next year will sit on top of. Brand voice, one-page customer profile, and a positioning statement that becomes the test for every piece of content you make.",
  topics: ["Brand vs Branding vs Identity", "The Five Components", "Voice in Action", "One-Page Customer Profile", "Positioning Formula", "Common Identity Traps"],
  quiz: [
    { q: "A trainee in Lagos spent NLe 3,000 on a logo and colours and has NLe 2,000 left of her brand budget. She has no written voice, no customer profile, no positioning statement. Brand equity is built across all five components — which allocation of the remaining NLe 2,000 has the highest long-term ROI?", opts: ["Spend it on a second logo variant for stories", "Save it; the logo is the brand", "Spend zero — invest the time instead in a written voice doc, a one-page customer profile, and a positioning statement. Brand is what customers FEEL; a logo edits that feeling marginally, while voice + positioning + customer clarity decide every caption, every ad, every DM reply for the next year. The components with no marginal cost are the ones with the highest ROI", "Hire the designer to write her captions too"], correct: 2 },
    { q: "Three captions for the same fresh-bread post in Freetown: (A) \"Bread emergency? 50 fresh loaves and bad jokes — DM before they're gone.\" (B) \"Slow-fermented overnight. Baked at 4am. Twelve loaves left at 9:30. Order before noon.\" (C) \"Started baking at 4 today, thinking about families like yours.\" If your customer is a 38-year-old premium-skewed professional in Aberdeen, which voice converts her — and why does that map to positioning?", opts: ["A — Playful builds love and works for everyone", "B — Expert. The premium customer pays for proof, not personality; specifics (slow-fermented, 4am, 12 left) signal craft and scarcity, which is the trust currency for a higher price point. Voice and positioning move together — you can't position premium with playful copy", "All three are the same — voice doesn't change conversion much", "C — Warm always wins for food"], correct: 1 },
    { q: "Mariama defines her customer as \"women 18–45 who like fashion\" — a TAM of ~400,000 in Lagos. Her engagement rate is 0.6% (industry average 1.5%), DM enquiries 4/month. The targeting fix that lifts conversion is:", opts: ["Broaden further to capture more potential customers", "Run paid ads to push the same posts to a wider audience", "Replace the category with one real persona — \"Adaeze, 32, Lekki, two children, office job, wants workwear under NGN 25,000, scrolls late at night.\" Specific personas raise message-market fit because copy can name her actual fears and budget; segmentation tightens conversion even when reach drops, because the people who DO see it are the people who buy", "Drop demographic targeting entirely"], correct: 2 },
    { q: "Apply the positioning formula: \"For [target] who [need], we are the [category] that [unique benefit] — unlike [alternative].\" A Freetown lunch-delivery business is choosing between four drafts. Which one is differentiated enough that a competitor can't copy it without changing their actual business?", opts: ["\"We sell the best food in Freetown at amazing prices.\"", "\"Mama Foods — healthy, fast, affordable, premium meals for everyone.\"", "\"For working mothers in Freetown who want healthy school lunches but no time to cook, Mama Foods is the daily delivery service that drops fresh meals at the school gate by 11:45am — unlike supermarket ready-meals full of preservatives.\" — the school-gate delivery and the 11:45 cutoff are operationally specific; competitors must rebuild logistics to match", "\"Good food, delivered. Try us today.\""], correct: 2 },
    { q: "A boutique owner in Nairobi: last 9 posts read like 9 different writers — jokey, corporate, preachy, emoji-heavy, austere. Brand recall in her audience (measured: \"can you describe this brand in one word?\") is 8%. Brand equity compounds when voice is consistent. The fastest lift comes from:", opts: ["Logo redesign", "Smaller audience", "ONE written voice document — one personality, three rules, three banned phrases — applied to every caption going forward. Consistency is the prerequisite for recall, and recall is the prerequisite for unaided brand equity. Voice drift is the silent cause of low recall even when reach is fine", "Copy a competitor's voice"], correct: 2 },
    { q: "Your skincare line is debating positioning: \"premium\" (target: 28–45 professionals, willing to pay NLe 800/unit) or \"affordable\" (target: 18–28 students, NLe 200/unit). Both segments are real. Picking BOTH means:", opts: ["Pick both and alternate by post — widens reach", "Pick one and own it. The two segments require opposite voice, opposite price, opposite distribution, opposite proof points — running them in parallel halves your message-market fit and confuses the algorithm about who to serve. Premium AND affordable is the classic positioning hedge that produces a category-of-none, not a category-of-one. Pick the segment with better LTV and own it", "Positioning doesn't affect conversion", "Lead with affordable; switch to premium when you grow"], correct: 1 },
  ],
  slides: [
    { type: "cover", module: "DAY 2", title: "Brand Identity &", titleAccent: "Positioning", subtitle: "The foundation document that every post for the next year will sit on top of.", meta: "Regium Touch × Aurora Foundation  |  Day 2  |  7 Slides" },
    { type: "stats", eyebrow: "WHY BRAND BEATS LOGO", title: "Brand isn’t a logo. Brand is every interaction.", intro: "Day 1 named the gap between where you are and where you want to be. Day 2 builds the document that closes it: the brand identity every future post will be tested against. Most businesses skip this step — and then wonder why their content never quite lands.", stats: [
      { num: "5", label: "components every brand identity is made of — voice, tone, values, visual identity, personality" },
      { num: "3", label: "foundation documents you leave today with: brand voice, customer profile, positioning statement" },
      { num: "1", label: "real customer your profile is built around — not a category, not ‘women aged 25–45’, one person" },
    ], subheading: "What Strong Brand-Builders Do Differently", bullets: [
      "Treat brand as what people FEEL — and brand identity as the deliberate tools they use to shape that feeling",
      "Pick ONE voice (playful, expert, or warm) and own it — not a different tone every post",
      "Write to one specific real customer with a name, age, neighbourhood, and routine — never to ‘everyone’",
      "Carry a written positioning statement they can recite in one breath",
      "Document the brand on paper — because brand ‘in your head’ is brand at risk every time you hire help",
    ] },
    { type: "grid", eyebrow: "THE FIVE COMPONENTS", title: "What brand identity is actually made of", subtitle: "A logo is one artefact of a brand — not the whole thing. The brand lives in five components, and only when all five are decided does branding become consistent.", items: [
      { num: "01", title: "Voice", desc: "How you sound. Playful, expert, or warm — pick one and own it. Voice is a decision, not a vibe; written down, it stops drifting.", icon: "\u{1F5E3}️" },
      { num: "02", title: "Tone & Values", desc: "Tone is how voice flexes by context — same voice on a sale post vs a complaint reply. Values are what you stand for and what you refuse, visible in every decision.", icon: "⚖️" },
      { num: "03", title: "Visual Identity", desc: "Three colours, two fonts. Photo style, layout patterns. The pieces a stranger recognises before they see your handle.", icon: "\u{1F3A8}" },
      { num: "04", title: "Personality", desc: "If your brand were a person, who would she be? How does she dress, greet a stranger, what annoys her? Write it down — it forces decisions you’ve been avoiding.", icon: "\u{1F464}" },
    ], footer: "Rule: brand identity is the lens for every decision from here. Without it, every post is a fresh argument with yourself." },
    { type: "principle", num: "01", title: "Brand vs Branding vs Brand Identity — The Three Words People Confuse", intro: "These three words get used interchangeably, and businesses lose money on the confusion. Day 2 separates them clearly so you know what you’re actually building when you sit down to design, write, or post.", sectionTitle: "The Three Words — Decoded", sections: [
      { heading: "1. BRAND — what people FEEL about your business", example: "When a customer thinks of your business, what comes up in her chest — trust, excitement, premium, friendly, sketchy, slow? That feeling IS your brand.", note: "It lives in their heads, not yours. You don’t own it — you influence it. Every interaction edits it, intentionally or not." },
      { heading: "2. BRANDING — the ACT of shaping that feeling", example: "Every post you publish, every DM reply, every customer interaction, every photo — all of it is branding, whether you meant it to be or not.", note: "You’re branding constantly. The only question is whether you’re doing it deliberately or by accident. Day 2 makes it deliberate." },
      { heading: "3. BRAND IDENTITY — the TOOLS you use to brand", example: "Voice, visuals, values, tone, personality. The deliberate written choices that make your branding consistent across 30 posts and 6 staff members.", note: "Brand identity is what you’re actually building today. It’s the toolkit — not the feeling, not the act, but the equipment." },
      { heading: "4. Why this matters in practice", example: "A trainee who thinks “my logo is my brand” will overspend on logos and underspend on voice and customer clarity — the things customers actually feel.", note: "Get the definitions right and the budget allocation fixes itself. Voice + customer profile + positioning > another logo redesign, every time." },
    ], rule: "Brand isn’t a logo. Brand is every interaction. Brand identity is the toolkit you use to keep those interactions consistent." },
    { type: "comparison", eyebrow: "TOO BROAD vs ONE REAL PERSON", title: "What a weak customer profile looks like vs a strong one", subtitle: "When you write for everyone, you connect with nobody. The most powerful posts feel like they were written for one specific person.", left: { title: "Too Broad (Connects With Nobody)", color: "#EF4444", items: [
      { strong: "“Women aged 18–45 who like fashion.”", note: "Could be a teenager OR a grandmother. The two have nothing in common; you can’t write a caption that lands for both." },
      { strong: "No idea what she earns or where she lives", note: "Pricing, language, and references all become guesses — the post sounds generic because it has to be." },
      { strong: "Don’t know what she fears or wants", note: "You can’t hook a post on a problem you can’t name. Captions default to product features, which is the weakest possible angle." },
      { strong: "Impossible to write a post she’ll stop for", note: "The scroll wins because the post wasn’t written for anyone in particular — and that’s exactly what it feels like." },
    ] }, right: { title: "One Real Person (Posts Write Themselves)", color: "#10B981", items: [
      { strong: "“Adama, 32, Freetown, Aberdeen. Two children. Office job by day.”", note: "You can picture her face. Specificity is what makes the writing land — generic profiles produce generic copy." },
      { strong: "“Wants smart-but-comfortable workwear under NLe 500.”", note: "You know what she searches for and what she can afford — every product, price, and visual decision becomes obvious." },
      { strong: "“Shops late at night on Instagram before bed.”", note: "You know when to post and what kind of content fits that scroll — quiet, calm, easy to read in low light." },
      { strong: "Every post writes itself — for her", note: "Counter-intuitively, writing for one person makes more strangers stop — because real specificity reads as truth." },
    ] }, footer: "Rule: ‘Women aged 25–45’ is a category. Adama is a person. Build the profile around the person; the category will follow." },
    { type: "table", title: "The Voice Decision Matrix — Pick One and Own It", subtitle: "All three voices below sell the same fresh bread. The voice you pick decides who buys it — and who doesn’t. Use this matrix to choose deliberately for your business.", columns: ["Voice", "Sample Caption (Same Product)", "What It Builds"], rows: [
      ["Playful", "“Bread emergency? We’ve got 50 fresh loaves and bad jokes. DM us before they’re gone.”", "Personality-led — builds love. Best for fashion, lifestyle, food, youth-skewed brands."],
      ["Expert", "“Slow-fermented overnight. Baked at 4am. Twelve loaves left as of 9:30. Order before noon.”", "Authority-led — builds respect. Best for skincare, finance, B2B services, premium positioning."],
      ["Warm", "“Started baking at 4 today, thinking about families like yours. Fresh bread, ready when you are.”", "Story-led — builds trust. Best for family businesses, wellness, services tied to home and care."],
      ["Common trap", "Switching between all three across the same week", "Reads as five different writers — trust never builds. Voice is a decision, not a mood."],
    ], footer: "Rule: pick one voice, write three rules and three banned phrases for it, and check every future caption against the document." },
    { type: "exercise", title: "Today’s Assignment — Build Your Three Foundation Documents", intro: "By the end of Day 2 you leave with three written documents that the rest of the programme — and the rest of your year — sits on top of: brand voice, customer profile, and positioning statement.", items: [
      { num: "1", copy: "Voice translation drill. Take the neutral caption “We have new bread today. Come buy.” Rewrite it in three voices — Playful, Expert, Warm — each under 30 words. Read all three aloud to your partner. Your partner picks the strongest for YOUR brand.", answer: "You can feel — not just understand — how voice changes everything. The voice your partner picked is your brand voice direction. Write it down with three rules and three banned phrases tonight." },
      { num: "2", copy: "One-page customer profile. Close your eyes and picture ONE real customer who has bought from you (or who you wish would). Give her a name. Fill in: demographics, daily routine, fears and frustrations, desires and goals, where she finds you online.", answer: "You have a one-page profile of a person, not a category. Pin it above your desk. From now on, every post is written to her by name — not to ‘everyone’. If you cannot picture her face, the profile isn’t specific enough yet." },
      { num: "3", copy: "Positioning statement. Fill in the formula: “For [target customer] who [need], we are the [category] that [unique benefit] — unlike [alternative].” One sentence. No hedges. Test it on someone who doesn’t know your business — they should understand exactly what you do.", answer: "The sentence becomes the test for every piece of content you produce. If a planned post doesn’t support the positioning, the post is wrong, not the positioning. Refine it tonight — read it aloud until it sounds like one breath." },
      { num: "4", copy: "Tonight, read your brand voice document aloud — does it sound like you? Add one more detail to your customer profile to make her even more specific. Bring 10 product or service ideas you could create content about to Day 3 — we use them tomorrow to build pillars.", answer: "Reading aloud catches voice drift faster than reading silently. The 10 content ideas are the raw material we’ll group into your 3–5 content pillars on Day 3 — don’t skip it; tomorrow’s exercise depends on it." },
    ] },
  ],
};
