// Social Media Marketing — Day 9: Capstone & Graduation
export const smmDay9Module = {
  id: "smm09",
  title: "Day 9 — Capstone & Graduation",
  type: "Rich Module",
  duration: "5h",
  desc: "Your day. Present what you’ve built, hear what your peers built, and take your next step. Eight days of work synthesised into a 10-minute presentation, a structured peer-feedback loop, and a personal 30-day plan you commit to in writing.",
  topics: ["The Nine-Day Synthesis", "10-Minute Presentation Structure", "Peer Feedback Loop", "Post-Programme 30-Day Plan", "First-30-Days Pitfalls", "The Written Commitment"],
  quiz: [
    { q: "Adama is up first to present. She opens with: ‘I started Adama Designs in 2019 after my second child was born. Originally it was just bracelets, then I added necklaces…’ The room glazes over by minute 2. Where did she go wrong?", opts: ["She should have skipped the introduction entirely", "She opened with company history instead of the customer. The Day 9 framework is explicit: open with the customer — ‘Adama is 32. Two children. Wants jewellery for office that doesn’t feel like office.’ The room leans in when they recognise a real human, not a founding story", "She should have shown her logo first", "She should have read directly off the slides"], correct: 1 },
    { q: "Fatou finishes her presentation. Mariama’s turn to give peer feedback. Mariama says: ‘Honestly, the whole thing was great, you’re doing amazing!’ Why is this — despite being kind — actually unhelpful, and what should the structure be?", opts: ["Add a long list of every weakness she noticed", "Use the Day 9 structure: one thing working (specific — ‘the way you described Adama, I could picture her exactly’), one question (‘what’s an example of a value post for your business?’), one challenge (‘your CTA was generic — what specific action would Adama take?’). Specific, structured, kind, useful", "Stay silent and let the trainer give all feedback", "Only mention what was bad — that’s the only useful feedback"], correct: 1 },
    { q: "Hawa drafts her 30-day commitment: ‘I will post more often, engage with my audience, and grow my business in the next 30 days.’ Looking at the Day 9 commitment template, what’s structurally wrong with this?", opts: ["It should be longer", "It’s vague on every dimension. The template demands a specific outcome with a number, action, or milestone (‘By 22 June 2026, I will have published 20 posts and earned my first 10 paying customers from Instagram’), protected time blocks, and a stuck-point protocol. Vague commitments don’t survive Week 2", "It should mention competitors", "She should commit to 90 days instead"], correct: 1 },
    { q: "It’s the second Monday after graduation. Isatu hasn’t posted since Friday. She’s scrolling Instagram and feeling small watching @bigaccountSL hit 50K followers. She’s about to skip today too. Which Day 9 pitfall is this, and what’s the protocol?", opts: ["The comparison spiral combined with the Monday slump and the start of calendar abandonment. Protocol: post in the alumni WhatsApp group within 48 hours, return to the Sunday batch session, and remind herself her goal is her customer — not a stranger’s follower count", "Take a 2-week break to recover energy", "Switch platforms entirely — Instagram clearly isn’t working", "Buy followers to feel competitive"], correct: 0 },
    { q: "Mariama is presenting. She’s 6 minutes in and realises she’s only on section 2 of 6. The trainer signals 4 minutes left. What’s the right adjustment in the moment?", opts: ["Speed-read through every remaining section to fit", "Skip straight to section 5 (30-day plan) and section 6 (the ad), naming the cut: ‘I’m going to jump to my 30-day plan to respect the time.’ The structure’s job is to land the most decision-relevant content, not to recite every section equally. End on time", "Stop, apologise for going over, and sit down", "Continue at full pace and let the next person have less time"], correct: 1 },
    { q: "Three weeks post-graduation, Aminata is debating whether to post a Reel she’s been editing for 5 days. She keeps tweaking. It’s ‘almost ready.’ Which Day 9 pitfall is this — and what’s the cure?", opts: ["The Monday slump", "Calendar abandonment — she should skip the Reel", "The ‘tweaking forever’ trap. Endlessly perfecting before posting. Cure: done is better than perfect — publish today, learn from the data, refine version 2 next week. Imperfect content that ships beats perfect content that never does", "She should stay silent in the alumni group until it’s ready"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 9", title: "Capstone", titleAccent: "& Graduation", subtitle: "Your day. Present what you’ve built, hear what your peers built, and take your next step.", meta: "Regium Touch × Aurora Foundation  |  Day 9  |  7 Slides" },
    { type: "stats", eyebrow: "THE NINE-DAY JOURNEY", title: "Look at what you built", intro: "Nine days ago, ‘social media’ was a vague pressure. Today, it’s a system you can run. Foundations, brand, strategy, visuals, words, platforms, ads, analytics — every layer in place.", stats: [
      { num: "10 min", label: "your capstone presentation — six sections, one business, your voice" },
      { num: "30 days", label: "the post-programme plan you’ll sign in writing today and pin where you’ll see it daily" },
      { num: "25", label: "women who showed up, did the work, and built something real over nine days" },
    ], subheading: "What Today Actually Is", bullets: [
      "Synthesise 8 days of learning into a coherent 10-minute business case",
      "Show — not tell — using real photos, real captions, the real 30-day calendar, and the real ad draft",
      "Give and receive peer feedback in a structured, specific format that actually helps",
      "Sign a personal 30-day commitment with date, outcome, protected time, and a stuck-point protocol",
      "Walk into the alumni WhatsApp group on Monday morning, not alone",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF GRADUATION DAY", title: "What today is built around", subtitle: "Today is a synthesis day, not a teaching day. Four moves in sequence — each one harder to do without the day before.", items: [
      { num: "01", title: "Synthesis", desc: "Eight days of work pulled into one coherent narrative — business + customer, brand, strategy, content, plan, ad. The whole journey on one page, in one voice.", icon: "\u{1F9E9}" },
      { num: "02", title: "Presentation", desc: "10 minutes, six sections, your business in your words. You’re not pitching strangers — you’re catching up with friends who watched you build this.", icon: "\u{1F399}️" },
      { num: "03", title: "Peer Feedback", desc: "After every presentation: one thing working, one question, one challenge. Specific. Structured. Kind. The format that turns peers into a board of advisors.", icon: "\u{1F4AC}" },
      { num: "04", title: "30-Day Commitment", desc: "Written, dated, signed. Specific outcome by 22 June 2026. Protected weekly time. A stuck-point protocol. Pinned where you’ll see it every morning.", icon: "✍️" },
    ], footer: "Rule: today is not the end. Today is the start of the part where it actually matters." },
    { type: "principle", num: "01", title: "Don’t Read Slides. Tell Us What You Built and What You’ll Do With It.", intro: "The trainees who land their capstone aren’t the most polished — they’re the most specific. They open with the customer, not the company. They show, not tell. They name what surprised them and what they’re still stuck on. They end with the next 30 days. Here’s the structure that does the work for you.", sectionTitle: "The 4 Moves That Make a 10-Minute Capstone Land", sections: [
      { heading: "1. Open with the customer, not company history", example: "Bad: ‘I started this business in 2019…’  Good: ‘Adama is 32. Two children. Office worker. Wants jewellery that feels like her, not like the office.’", note: "The room leans in when they recognise a real human. Founding stories belong in slide 6, not slide 1." },
      { heading: "2. Show, don’t tell — open the actual files", example: "Open the Canva file. The 30-day calendar. The ad draft. The captions. Not screenshots — the real thing.", note: "Real artefacts prove you did the work. Polished slides describing the work prove only that you have a slide template." },
      { heading: "3. Name what surprised you and where you’re stuck", example: "‘I learned my customer wasn’t who I thought she was.’ ‘I still don’t know how to read TikTok analytics — can the room help?’", note: "Vulnerability + specificity = trust. Asking the room turns peers into advisors. The stuck-point question is often the most useful 30 seconds of the whole presentation." },
      { heading: "4. End with the next 30 days, not a thank-you", example: "‘Mondays I batch. Fridays I review. By 22 June 2026 I will have published 20 posts and earned my first 10 Instagram customers.’", note: "The last words are the ones the room remembers. Specific actions + specific date + specific outcome. Make it impossible to forget." },
    ], rule: "You’re not pitching a stranger. You’re catching up with friends who watched you build this. Time yourself once at home tonight — that’s the difference between calm and chaos in the morning." },
    { type: "comparison", eyebrow: "THE FIRST 30 DAYS — TWO PATHS", title: "Same graduate. Same skills. Different month one.", subtitle: "The work doesn’t stop today. The pitfalls in column one sabotage Week 2 onwards. The protocols in column two are how graduates actually compound.", left: { title: "The Pitfall Path (Most Graduates)", color: "#EF4444", items: [
      { strong: "The Monday slump — first Monday alone, all the energy drops", note: "No cohort, no trainer, no one watching. Skipping one day becomes skipping one week becomes giving up by Week 3." },
      { strong: "Calendar abandonment — ‘I’ll post when inspired’", note: "Inspiration is unreliable. The 30-day calendar from Day 3 was the entire point — the moment you abandon it, you’re back to vague pressure." },
      { strong: "Comparison spiral — watching @bigaccountSL hit 50K", note: "Their numbers are not your numbers. Your goal is your customer, not a stranger’s follower count. Spiral kills consistency faster than failure does." },
      { strong: "Tweaking forever and going silent on the group", note: "Endlessly perfecting before posting + disappearing from the alumni WhatsApp = the slow exit. Done is better than perfect; visible is better than gone." },
    ] }, right: { title: "The Compound Path (Real Graduates)", color: "#10B981", items: [
      { strong: "Sunday batch session protected on the calendar", note: "Two hours every Sunday afternoon. Captions written, photos staged, posts scheduled. Monday energy doesn’t matter when Sunday already shipped the week." },
      { strong: "Friday 5-minute review every week without fail", note: "Open insights. Answer the four prompts. Note what to repeat next week. Tiny ritual, compounding return — the graduates who do this for 12 weeks have a content playbook." },
      { strong: "Goal is the customer, not the stranger’s follower count", note: "When the comparison spiral hits, return to your customer profile from Day 2. Adama doesn’t care that someone else has 50K followers. She cares that you serve her well." },
      { strong: "Done > perfect. Stuck-point posted in the group within 48 hours", note: "Imperfect content that ships beats perfect content that never does. And the alumni group is where you stay accountable — silence is the slow exit; asking is the fast lane." },
    ] }, footer: "Rule: most graduates know what to do. The challenge is doing it consistently. Pick your column today, in writing, with a date." },
    { type: "table", title: "The 6-Section Capstone Structure", subtitle: "10 minutes. Six sections. Your business. Time it once tonight at home — phone timer running, out loud.", columns: ["Section", "Time", "What to Show / Source"], rows: [
      ["1. Business + customer", "60 sec", "Who you serve, what you sell, why now. Open with the customer (Day 2)."],
      ["2. Brand identity", "60 sec", "Voice, values, visual style. Show one real example (Day 2)."],
      ["3. Content strategy", "2 min", "Pillars, 80/20 ratio, the actual 30-day calendar (Day 3)."],
      ["4. Sample content", "3 min", "Show 2 real posts. Walk through hook, body, CTA (Days 4–5)."],
      ["5. 30-day plan", "2 min", "What you’ll do every week for the next month. Specific actions (tonight’s homework)."],
      ["6. Your one ad", "1 min", "The first paid ad you’ll run, and why (Day 7)."],
    ], footer: "Rule: if you go over, the next person loses time. End on time — that’s the only inviolable rule of today." },
    { type: "exercise", title: "Sign Your 30-Day Commitment", intro: "Your final assignment isn’t a tactical task — it’s the commitment that keeps every tactic alive after today. Fill this in tonight. Sign it. Take a photo. Pin it where you’ll see it daily. The graduates who write this down and look at it weekly are the ones still posting in 90 days.", items: [
      { num: "1", copy: "Write the opening line: ‘I am [your name], founder of [business name].’ Then the outcome line: ‘By 22 June 2026, I will have ___.’ Fill in a SPECIFIC outcome — a number, an action, a milestone (‘published 20 posts and earned my first 10 paying customers from Instagram’).", answer: "Vague commitments don’t survive Week 2. ‘I will post more’ is a wish. ‘By 22 June 2026, I will have published 20 posts and earned my first 10 paying customers from Instagram’ is a contract with yourself. Numbers + dates make it real. Wishes don’t make it past the first Monday alone." },
      { num: "2", copy: "Protect two weekly time blocks in writing: ‘Every Sunday afternoon for batching. Every Friday afternoon for the 5-minute review.’ Add them to your phone calendar as recurring events with reminders 30 minutes before.", answer: "The Sunday batch is what makes Monday irrelevant — your week ships before the slump arrives. The Friday review is what makes the next week smarter than the last. Two non-negotiable blocks. Everything else flexes around them. Without protected time, you’ll find an excuse by Week 2." },
      { num: "3", copy: "Write the stuck-point protocol: ‘When I get stuck, I will post in the alumni WhatsApp group within 48 hours.’ Save the group as a pinned chat. Set a personal rule: silence longer than a week = a check-in DM to your accountability partner.", answer: "Going silent is the slow exit. Most graduates who quit don’t announce it — they just stop showing up in the group. The 48-hour rule prevents that drift. Asking out loud is what turns a stuck point into the next breakthrough. The alumni group only works if you actually use it." },
      { num: "4", copy: "Sign and date it. Take a photo on your phone. Set the photo as your phone wallpaper OR pin it on the wall above where you work. Read it once every Monday morning before opening Instagram.", answer: "Visible commitments outperform invisible ones by every measure ever studied. Your phone wallpaper is the surface you see 80+ times a day. Your wall is the surface you see at the start of every work session. Either way: the commitment lives where the temptation to skip lives. Today is not the end — today is the start of the part where it actually matters." },
    ] },
  ],
};
