// Social Media Marketing — Day 1: Foundations & Mindset
export const smmDay1Module = {
  id: "smm01",
  title: "Day 1 — Foundations & Mindset",
  type: "Rich Module",
  duration: "5h",
  desc: "The four pillars that turn random posting into real marketing. Audit where your business actually stands today, name the gap, and write one SMART goal that decides everything else.",
  topics: ["The Four Pillars", "Posting vs Marketing", "The Five Traps", "SMART Goals", "Honest Brand Audit", "Mindset Shift"],
  quiz: [
    { q: "Aminata's soap business in Freetown has 240 followers after 6 months. Her competitor Hawa has 1,800 followers in the same time. Aminata's posts: 7 last week, 0 the prior 18 days, no measurement. Hawa: 3/week without fail, tracks DM-to-sale conversion at 4%. Aminata says: \"Social media doesn't work for my kind of business.\" The marketing diagnosis is:", opts: ["Soap is saturated in Freetown — Aminata should pivot products", "Aminata is posting; Hawa is marketing. Without cadence, positioning, or a tracked conversion metric, Aminata has no way to optimise — Hawa's 4% DM-to-sale rate is the lever, not the follower count; the problem is the operating system, not the platform", "Instagram favours larger accounts — Aminata should switch to TikTok", "Aminata's content quality is probably fine; she just needs follower ads"], correct: 1 },
    { q: "Fatu, a tailor in Lagos, writes her annual goal as: \"Grow my Instagram and get more sales.\" A SMART goal must tie to a revenue-relevant outcome with a deadline. Which rewrite passes the test AND maps cleanest to a measurable funnel metric?", opts: ["\"Get a lot more enquiries from Instagram by the end of 2026\"", "\"Grow my Instagram followers to 10,000 as soon as possible\" — followers are the scoreboard", "\"Get 50 qualified DM enquiries that convert at 20% to paid orders by 30 June 2026\" — specific, measurable, tied to revenue, attributable to one platform, time-bound", "\"Become the most followed tailor in Lagos this year\""], correct: 2 },
    { q: "You audit your page: 4/12 Yeses. The gaps: no consistent voice, no measurement, last post 14 days ago, no contact details in bio. You have NLe 200 and 8 days. Your shop currently gets ~12 DM enquiries/month at a 25% close rate (3 sales). The highest-ROI first move is:", opts: ["Spend NLe 200 on a logo redesign — visual identity drives everything", "Spend NLe 200 boosting last week's post for reach", "Fix the bio contact details first — it's free and removes the conversion blocker on every existing enquiry; 25% close on 12 enquiries becomes 25% close on 18+ once strangers can find your WhatsApp directly. Cheapest fix with the largest funnel-stage lift", "Post 3 times today to make the page look active"], correct: 2 },
    { q: "Hawa's Accra catering page: gorgeous photos, every caption ends \"DM to order — limited slots!\" After 3 months: engagement collapsed 60%, 40 unfollows, DM enquiries dropped from 22/week to 6/week. The 80/20 rule says value content earns the right to sell. Which trap is she in, and what does the math reveal?", opts: ["All-sell, no value — 100% of her posts are bottom-funnel asks aimed at an audience she hasn't warmed up; the unfollow rate (-40 in 3 months) and the 73% drop in DMs are the activation cost of skipping the brand-equity layer. Fix: 4-of-5 posts give value, 1-of-5 asks", "Inconsistent posting", "No clear customer", "No measurement"], correct: 0 },
    { q: "Two boutique owners in Aberdeen post the same dress photo on the same day. Six months later: Owner A has 3× the enquiries and predictable monthly revenue; Owner B is flat. Owner A's spend: NLe 0/month on ads, NLe 0/month on agencies — same as Owner B. The single explanation that fits the data is:", opts: ["Owner A got lucky with the algorithm", "Owner A is treating social as a system — fixed cadence, consistent positioning, 80/20 value-to-ask mix, weekly insights review tied to enquiries — while Owner B posts reactively. Same product, same budget, opposite operating model — and the operating model is the entire ROI gap", "Owner B is in a tougher pricing tier", "Owner A is secretly running paid ads"], correct: 1 },
    { q: "A trainee: \"Skip the audit — I know my page is bad. Just post better content.\" In marketing terms, why is this the wrong move before any new content goes live?", opts: ["Audits are only useful for businesses over a certain size", "She has a point — audits are a vanity exercise", "Without a baseline of current reach, engagement rate, and DM-conversion, she has no attribution for whether \"better content\" actually moved a metric — \"my page is bad\" isn't a diagnosis, and improvements that aren't measured can't be repeated. The audit is the control group for everything she's about to test", "She should outsource the audit to an agency"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 1", title: "Foundations &", titleAccent: "Mindset", subtitle: "The four pillars that turn random posting into real marketing.", meta: "Regium Touch × Aurora Foundation  |  Day 1  |  7 Slides" },
    { type: "stats", eyebrow: "WHERE YOUR CUSTOMERS ACTUALLY ARE", title: "The question is no longer whether your business should be online — it’s whether you’ll do it well or poorly", intro: "More Sierra Leoneans are online than ever. Over the next nine days you will move from posting occasionally to marketing strategically — a shift small in language, enormous in business outcome. Day 1 sets the foundation everything else sits on.", stats: [
      { num: "9 Days", label: "of intensive training across the full programme" },
      { num: "45 Hours", label: "of hands-on practice — not theory, real reps on your real business" },
      { num: "9 in 10", label: "customers check your page before buying — your profile is doing the selling whether you tend it or not" },
    ], subheading: "What Strong Marketers Do Differently", bullets: [
      "Post on a schedule they actually follow — not when they remember",
      "Carry one recognisable voice and visual style across every post",
      "Mix value posts with promotions instead of selling in every caption",
      "Read insights weekly and adjust based on what the data shows",
      "Keep posting when life gets busy — because it’s a system, not a mood",
    ] },
    { type: "grid", eyebrow: "THE FOUR PILLARS", title: "The foundation of every session in this programme", subtitle: "Most small businesses fail at social media because they only invest in one or two of these. Over the next nine days, we build all four.", items: [
      { num: "01", title: "Strategy", desc: "Brand, customer, positioning, content pillars. The lens every post is tested against — written down, not held in your head.", icon: "\u{1F3AF}" },
      { num: "02", title: "Content", desc: "Visuals, copywriting, formats, platform-specific creation. The craft of making the post itself — photo, caption, reel, carousel.", icon: "✍️" },
      { num: "03", title: "Engagement", desc: "DMs, community, complaints, customer service. Marketing is a conversation; ignored DMs cost more sales than weak posts do.", icon: "\u{1F4AC}" },
      { num: "04", title: "Measurement", desc: "Analytics, the four metrics that matter, paid ads performance. Without data you have no idea what to repeat or change.", icon: "\u{1F4CA}" },
    ], footer: "Rule: invest in all four. A weakness in any single pillar quietly caps the return on the others." },
    { type: "principle", num: "01", title: "From Posting to Marketing — The Mindset Shift", intro: "Two activities look identical from the outside — a woman with her phone, putting something on Instagram. They are not the same thing, and the difference shows up in your bank account. Day 1’s work is to make sure you leave today on the marketing side of the line.", sectionTitle: "The Four Shifts That Separate Posters From Marketers", sections: [
      { heading: "1. Reactive becomes strategic", example: "Poster: “What should I post today?” Marketer: “Which pillar needs a post this week, and what’s my SMART goal for the month?”", note: "The question changes because there’s a written plan, customer, and goal already in place." },
      { heading: "2. Random becomes consistent", example: "Poster: a different filter, font, and tone every week. Marketer: same three colours, two fonts, one voice across all 30 posts in the calendar.", note: "Consistency is what makes a stranger recognise your post in a feed without seeing your handle." },
      { heading: "3. All-sell becomes value-led", example: "Poster: every caption ends in “DM to order.” Marketer: 80% of posts educate, entertain, or build trust; the 20% sales posts are earned by the value that came before.", note: "Followers stay for value, then convert on the asks. Reverse the ratio and they unfollow." },
      { heading: "4. Mood becomes system", example: "Poster: stops when life gets busy. Marketer: keeps posting because the calendar is filled, the photos are batch-shot, and the captions are scheduled.", note: "Systems survive bad weeks. Motivation doesn’t — which is why most small business pages go quiet by month three." },
    ], rule: "Posting is a verb you do to your phone. Marketing is a system you run for your business. Today, you cross the line." },
    { type: "comparison", eyebrow: "BUSINESS A vs BUSINESS B", title: "What weak social media looks like vs strong social media", subtitle: "Same product. Same neighbourhood. Same starting followers. After 12 months: completely different businesses.", left: { title: "Business A — The Hustler (Posting)", color: "#EF4444", items: [
      { strong: "Posts when she remembers — sometimes 4 in a week, then 18 days silent", note: "The algorithm reads silence as inactivity and stops showing her to followers; bursts can’t recover the lost reach." },
      { strong: "Different style every time — new filter, new font, new voice", note: "Strangers scrolling can’t tell two of her posts come from the same business; recognition never builds." },
      { strong: "Posts only when she has stock to sell", note: "Followers feel sold-at, not served; engagement collapses and unfollows climb every promotion week." },
      { strong: "Doesn’t know what’s working — never opens insights", note: "After 12 months: same business size. Quietly wonders if social media is worth it. It is — her use of it isn’t." },
    ] }, right: { title: "Business B — The Marketer (Marketing)", color: "#10B981", items: [
      { strong: "Posts on a schedule she follows — same days, same times, every week", note: "Predictable cadence trains both the algorithm and her customer’s habit; she earns a regular slot in the feed." },
      { strong: "Recognisable voice and visual style across every post", note: "Followers recognise her posts before they see her handle. Brand recall is the cheapest growth lever there is." },
      { strong: "Mixes value posts with promotions — 80/20 by design", note: "She earns the right to sell. Followers actively wait for her promotion posts because the value posts already paid them back." },
      { strong: "Reads insights weekly and adjusts based on what the data shows", note: "After 12 months: 3× the enquiries, regular customers, predictable revenue. Same product — different operating model." },
    ] }, footer: "Rule: it isn’t a content problem. It’s a system problem. Build the system once; the content gets easier every month." },
    { type: "table", title: "The Honest Audit Checklist — Where You Stand Today", subtitle: "Twelve questions about your page. Tick yes or no. You cannot fix what you have not named — today, just record the truth. Aim for 12 yeses by Day 9.", columns: ["#", "Question", "What a “Yes” Means"], rows: [
      ["1", "Profile picture is recognisable at thumbnail size", "Strangers can identify your brand in a tiny circle on a stranger’s phone"],
      ["2", "Bio explains what you do and who you serve in one line", "A first-time visitor knows in 3 seconds whether you’re for her"],
      ["3", "Contact details (phone, WhatsApp, email) are visible", "An interested buyer can reach you without DMing — the cheapest enquiry path is open"],
      ["4", "Last post was within the past 7 days", "Algorithm and customers both read your account as active and worth showing"],
      ["5", "Visual style is consistent across the last 9 posts", "Your grid recognisable — same palette, same vibe — not nine different brands"],
      ["6", "DMs are answered within 24 hours", "Engagement pillar is alive; warm leads aren’t cooling because of you"],
      ["7", "There’s a clear call-to-action somewhere on the page", "You’re telling visitors what to do next — not leaving them to guess"],
    ], footer: "Rule: a 4-out-of-12 audit isn’t a verdict; it’s a roadmap. The gaps you name today are your priority list for the next 8 days." },
    { type: "exercise", title: "Today’s Assignment — Audit, Reverse-Engineer, and Set Your SMART Goal", intro: "Three pieces of work, all done today, all in writing. By the end of Day 1 you have an honest baseline, a model you’re studying, and a single-sentence goal the rest of the programme will sharpen.", items: [
      { num: "1", copy: "Pick one Sierra Leonean business you actually follow on social media — not one you think you should follow. Write down 3 specific things their content does that makes you stop scrolling, and match each to one of the Four Pillars (Strategy, Content, Engagement, Measurement).", answer: "You can name what works — not just feel that it works. That’s the start of being able to do it yourself. If all 3 things land in one pillar, that’s your strongest model for that pillar; go to a second business for the others." },
      { num: "2", copy: "Run the 12-question audit on your own Facebook, Instagram, and WhatsApp Business profiles. Be honest — a generous 9/12 today helps no one. Write down your top 3 strengths to keep building on, and your top 3 weaknesses to fix in the next 8 days.", answer: "A clear picture of where your business stands today, in writing. Most trainees score 3–6 on Day 1 — that’s normal. The score isn’t the point; the named gaps are." },
      { num: "3", copy: "Write your programme goal in the SMART format. Specific (which platform, which outcome). Measurable (a number, not a feeling). Achievable (stretching, not impossible). Relevant (tied to a business outcome you actually need). Time-bound (by a specific date).", answer: "Read it aloud. If it sounds achievable in 30 days, you’ve got it. Example: “Get 50 product enquiries from Instagram DMs by 30 June 2026.” Not “grow my followers.”" },
      { num: "4", copy: "Tonight, refine the SMART goal and read it to one trusted person who knows your business. Bring your business name, logo, and 5 product photos to Day 2 — we build brand identity on top of today’s baseline.", answer: "Reading it aloud to another human is the cheapest test there is. If they ask “by when?” or “how many?” the goal isn’t SMART yet — fix it tonight, not tomorrow. The goal is the rail every Day 2–9 decision runs on." },
    ] },
  ],
};
