// Social Media Marketing — Day 5: Copywriting for Social Media
export const smmDay5Module = {
  id: "smm05",
  title: "Day 5 — Copywriting for Social Media",
  type: "Rich Module",
  duration: "5h",
  desc: "Words that stop the scroll, build trust, and turn followers into enquiries. Hook patterns, caption structures, calls-to-action, and a 2026-honest take on hashtags — written for women running businesses in West Africa.",
  topics: ["The First-Line Problem", "7 Hook Patterns", "Caption Structures", "CTA Hierarchy", "Hashtag Strategy", "Before & After Rewrites"],
  quiz: [
    { q: "A trainee posts: 'Hi everyone, hope you're well. Today we wanted to share that we have new products in the shop and we're excited about it. Come and check us out!' Reach is dismal. The single biggest fix — before touching anything else — is:", opts: ["Replace the generic, polite first line with a specific, urgent hook (e.g. 'Three women asked for this exact bag yesterday — we made one, it's gone in 24 hours'); algorithms decide whether to push the post within seconds, and that decision rests heavily on the first line", "Add 25 hashtags so the post gets discovered", "Post at a different time of day", "Add three more emojis to make it feel friendlier"], correct: 0 },
    { q: "You write a caption opening with: 'Stop trying to grow your followers. Here's what to do instead.' Which of the seven hook patterns is this — and why does it work for a small business with 380 followers?", opts: ["Question hook — it lifts because it asks the reader something directly", "Statistic hook — it works because it cites a number", "Contrarian hook — it works because most followers expect 'grow your followers' advice from business pages, so subverting the expected message creates a pattern interrupt that earns the second line", "Direct address hook — it works because it names a city"], correct: 2 },
    { q: "A trainee's caption ends: 'Tag a friend, share to your story, follow us, DM us to order, and click the link in bio!' Engagement is near zero on every metric. The principle she's broken is:", opts: ["She forgot to add hashtags", "One CTA per post — two CTAs equal zero CTAs; when you ask for five things at once, customers freeze and do none. Pick the single highest-value action and ask only for that", "She used too few emojis to signal each ask", "The caption is the wrong length"], correct: 1 },
    { q: "A baker in Freetown is choosing hashtags for a sourdough post. She's about to paste in the same 30 generic tags (#bread #food #foodie #yummy ...) she copies from a template every time. Better strategy:", opts: ["Use 3–8 specific tags, mix sizes (some large, some tiny like #FreetownBaker), favour local + niche over generic; spammy 30-tag stacks now trigger algorithm penalties, and tiny tags surface posts faster than competitive ones", "Use 30 hashtags every time — more tags equal more reach, that rule hasn't changed", "Skip hashtags entirely; they don't work on any platform anymore", "Only use the single most popular tag in her category"], correct: 0 },
    { q: "You're writing a caption to announce a Friday restock of one specific dress. You want the customer to commit to the early-access list. Which structure fits the goal best?", opts: ["List structure — 'Five reasons our dresses are great: 1...' — lists work for every situation", "Story-arc structure — 'Three customers asked us this week: when are you restocking the green linen dress? Answer: Friday, 4pm, sizes 8 to 14. Last restock sold out in 2 hours. DM us GREEN to be on the early-access list.' — the setup→tension→resolution arc with a single specific CTA matches a restock announcement perfectly", "Generic announcement — 'Hello our lovely customers! We hope you are having a great week...'", "Question-only structure with no answer in the post"], correct: 1 },
    { q: "A trainee says: 'I've been told to put a CTA on every post, so I'm asking strangers who just discovered me yesterday to DM me to order.' Conversion is zero. The CTA-hierarchy mistake is:", opts: ["She's not using enough emojis around the CTA", "She's matching a high-commitment ask (DM to order) to a low-commitment audience (cold strangers); CTAs ladder — cold viewers respond to like / save / one-word comment; warm followers respond to tag a friend / follow / link click; the buying-ready respond to DM / call / buy. Match the ask to where she is", "DMs don't work for sales — only website links convert", "The post needs more CTAs to give the customer options"], correct: 1 },
  ],
  slides: [
    { type: "cover", module: "DAY 5", title: "Copywriting", titleAccent: "for Social Media", subtitle: "Words that stop the scroll, build trust, and turn followers into enquiries.", meta: "Regium Touch × Aurora Foundation  |  Day 5  |  7 Slides" },
    { type: "stats", eyebrow: "THE FIRST-LINE PROBLEM", title: "Most captions die in line one — and the algorithm is watching", intro: "Algorithms decide whether to push your post within seconds of publishing, and that decision rests heavily on whether viewers stop and engage with the very first line. Photos earn attention; captions earn trust. Both have to land or the post is invisible.", stats: [
      { num: "3 sec", label: "average attention given to a caption's first line before the viewer scrolls or stays" },
      { num: "1 hook", label: "is the difference between a post that reaches 200 people and the same post reaching 2,000" },
      { num: "1 CTA", label: "per post — not zero, not three. Two CTAs reliably equal zero CTAs in measured engagement" },
    ], subheading: "What Today's Module Will Install Into Your Writing", bullets: [
      "Write hooks using 7 proven patterns — you'll never be stuck for a first line again",
      "Structure captions using story, list, question, and contrast formats — pick one per post",
      "Write calls-to-action that drive specific responses, matched to where the reader actually is",
      "Use hashtags strategically (3–8 specific tags, local + niche) without over-relying on them",
      "Spot the difference between an 80-word polite caption and a 38-word caption that converts",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF DAY 5", title: "Hooks, structures, CTAs, and a hashtag strategy that's not from 2019", subtitle: "Master these four and every caption you write from tomorrow onwards starts with a hook, ends with one clear ask, and never wastes the first three seconds.", items: [
      { num: "01", title: "The 7 Hook Patterns", desc: "Question, bold claim, statistic, direct address, story opening, contrarian, and curiosity. Memorise the seven — you have a first line for every post.", icon: "🎯" },
      { num: "02", title: "Caption Structures", desc: "Story arc, list, question-answer, contrast. Pick one per post. The structure carries the message so you can stop staring at a blank caption box.", icon: "📝" },
      { num: "03", title: "CTA Hierarchy", desc: "Match the ask to the reader's commitment level. Strangers like; warm followers tag and follow; buyers DM and call. One CTA per post.", icon: "👉" },
      { num: "04", title: "Hashtag Reality (2026)", desc: "3–8 specific tags, local + niche, mix sizes. Skip on Facebook. No more 30-tag spam stacks — they trigger penalties now.", icon: "#️⃣" },
    ], footer: "Rule: photos earn attention, captions earn trust. The hook is where you spend your effort — the body matters far less if the first line fails." },
    { type: "principle", num: "01", title: "The 7 Hook Patterns — First Lines That Earn the Second Line", intro: "Master these seven openings and you'll never be stuck for a hook again. Every successful caption you've ever scrolled past was running one of these patterns. Pick the one that matches the post's job; write a single sharp version; never default to 'Hi everyone, hope you're well'.", sectionTitle: "The 7 Patterns — With Concrete Lines You Can Adapt Today", sections: [
      { heading: "1. Question hook — ask something the reader has actually thought", example: "'Have you ever wondered why your product photos look amateur even though you used the same phone as the brand you envy?'", note: "Works because the brain cannot stop itself from answering a well-posed question. Avoid yes/no questions — ask ones that earn a thought." },
      { heading: "2. Bold claim hook — say something most readers will instinctively challenge", example: "'Most small businesses are using Instagram completely wrong — and it costs them more than they realise.'", note: "Works because the reader stays to find out whether they're in the 'most' or in the exception. Don't bluff — your post must back the claim." },
      { heading: "3. Story-opening hook — start mid-scene", example: "'Last Tuesday, a customer messaged us at midnight asking if we could deliver a cake by 8am the next morning…'", note: "Works because narrative pulls readers forward. The mid-scene start (no preamble) is the trick — don't 'set up' the story; drop them inside it." },
      { heading: "4. Contrarian / direct-address hook — break a default expectation or name the reader directly", example: "Contrarian: 'Stop trying to grow your followers — here's what to do instead.' Direct: 'If you sell food in Freetown, read this before the weekend.'", note: "Both work for the same reason: pattern interrupt. The reader expected the average page; you didn't sound like the average page; she stays to find out why." },
    ], rule: "These seven patterns are the entire toolkit. Build a personal swipe file: every time a hook stops your scroll in the wild, paste it into a notes app and label which of the seven it is. Within a month you'll have hundreds." },
    { type: "comparison", eyebrow: "THE BEFORE & AFTER", title: "One restock announcement, two completely different captions", subtitle: "The same business, the same product, the same Friday restock. The difference is hook, structure, and number of asks. Read both aloud — you'll feel the gap.", left: { title: "Before — 0 hooks, 5 CTAs, 80 words", color: "#EF4444", items: [
      { strong: "Opens with: 'Hello our lovely customers! We hope you're having a great week.'", note: "Generic, polite, instantly forgettable. The algorithm reads no curiosity signal in line one and starves the post." },
      { strong: "Body lists every category in stock: dresses, tops, bags, accessories, much more", note: "Says nothing specific. Could be any boutique anywhere. Customers can't picture a single item, so they don't desire one." },
      { strong: "Ends with: tag a friend, share, follow, check us out, link in bio, thank you", note: "Five competing asks. The brain freezes. The customer scrolls without doing any of them." },
      { strong: "80 words long, wrapped in pleasantries and emojis", note: "Reads as filler, not content. Trust signals are absent because there's no specific claim to anchor trust to." },
    ] }, right: { title: "After — 1 hook, 1 CTA, 38 words", color: "#10B981", items: [
      { strong: "Opens with: 'Three customers asked us this week: when are you restocking the green linen dress?'", note: "Specific number, specific product, opens a loop. Story-arc hook — the reader has to know the answer." },
      { strong: "Body answers cleanly: 'Friday. 4pm. Sizes 8 to 14. Last restock sold out in 2 hours.'", note: "Concrete time, sizes, and a credibility proof point. Customer can picture acting and can picture missing out." },
      { strong: "Ends with one specific CTA: 'DM us GREEN to be on the early-access list.'", note: "One ask. Low-friction. The 'GREEN' codeword makes the customer's action specific and trackable for the business." },
      { strong: "38 words, zero filler, every line earning its place", note: "Reads as a real human running a real business who knows what she's selling — the trust signal customers actually respond to." },
    ] }, footer: "Rule: hook + structure + single ask. If your caption can't be cut to 40 words without losing meaning, the meaning wasn't there." },
    { type: "table", title: "The CTA Hierarchy — Match the Ask to Where She Is", subtitle: "A stranger won't 'DM us to order' — but she might 'comment YES'. Build the ladder. One CTA per post, picked from the rung that matches the reader's commitment level.", columns: ["Commitment Level", "What She'll Actually Do", "When to Use It"], rows: [
      ["Low (cold viewer)", "Like · Save · Comment one word · React with emoji", "Early-stage content, awareness posts, when the reader hasn't seen you before. Asks 0–2 seconds of effort."],
      ["Medium (warm follower)", "Tag a friend · Share to your story · Follow · Click the link", "Educational content, behind-the-scenes, value posts. The reader knows you exist and likes what she's seeing."],
      ["High (buying-ready)", "DM us to order · Call this number · Visit the shop · Buy now", "Restock posts, offer posts, last-call posts. Save these for warm audiences who already trust the brand."],
      ["Codeword CTAs", "'DM us GREEN' · 'Comment SIZE' · 'Reply READY'", "Trackable, low-friction, gives the business an instant filter on intent. Use on launches and waitlists."],
      ["The trap", "Asking for like AND share AND tag AND follow AND DM in one caption", "Two CTAs equal zero CTAs. Always. Pick the single highest-value action for this post and ask only for that."],
    ], footer: "Rule: one CTA per post. If you genuinely have two asks, you have two posts — publish them on different days." },
    { type: "exercise", title: "The Hook-Swap and Single-Ask Audit", intro: "Two assignments today, both done on real posts from your own business. By the end you'll see the gap in your own writing — and have a swipe file of hooks that work for your voice.", items: [
      { num: "1", copy: "Pull up an old caption from your business — any one. Keep the body exactly the same. Write 3 new opening lines using 3 different hook patterns from today's seven.", answer: "Read all 3 aloud. You'll feel which one earns the second line. From now on, the hook is where you spend your effort — not the body." },
      { num: "2", copy: "Open your last 5 published posts. For each, count: how many things does this post ask the reader to do? Write the number next to each post.", answer: "0 asks = invisible. 3+ asks = ignored. The number you want is exactly 1 — every single time, no exceptions." },
      { num: "3", copy: "Rewrite each of those 5 posts so it has EXACTLY one specific call-to-action. Match the CTA's commitment level to where the average reader of that post actually is.", answer: "Cold-audience post = low-commitment ask. Warm-audience post = medium. Restock or offer post = high. Pick the rung that fits, not the one you wish fit." },
      { num: "4", copy: "Write 3 fresh captions using 3 different structures (story arc, list, question-answer) for the 3 visual assets you produced on Day 4. Add a hook from the seven patterns and one CTA each.", answer: "By the end of today you have 3 fully written, peer-reviewed captions ready to schedule — and the start of a personal swipe file of hooks that work in your voice for your audience." },
    ] },
  ],
};
