// Social Media Marketing — Day 6: Platform Deep Dives
export const smmDay6Module = {
  id: "smm06",
  title: "Day 6 — Platform Deep Dives",
  type: "Rich Module",
  duration: "5h",
  desc: "Choosing your two primary platforms — and learning what wins on each. Facebook, Instagram, TikTok, WhatsApp Business: who uses them, what content lifts, which features actually close sales in Sierra Leone.",
  topics: ["Facebook Pages & Groups", "Instagram & TikTok Optimisation", "WhatsApp Business as Sales Engine", "Profile Anatomy", "The Decision Framework", "Platform-Specific Features"],
  quiz: [
    { q: "A Freetown jeweller targets women 30–55 with disposable income. Her customer profile data: 78% on Facebook + WhatsApp daily, 12% on Instagram, 4% on TikTok. She spends 70% of her content time on TikTok \"because the algorithm is hottest right now.\" Her DM enquiries are flat. The platform-allocation error is:", opts: ["TikTok is wrong for any SL business", "She's allocating effort against algorithm headlines, not customer attention. Platform choice is segmentation — 70% of her time is reaching 4% of her audience. Reallocating to Facebook + WhatsApp (where 78% live) would multiply effective impressions ~10x with the same hours. Platform = where customers are, not where reach is theoretically cheapest", "Be on all four equally", "Wait for TikTok ads in SL"], correct: 1 },
    { q: "A Lagos tailor: 1,200 IG followers, 600 Facebook Page likes, awareness funnel healthy. DM enquiries: 35/month. Order conversion: 8%. She types prices into WhatsApp chats one-by-one, no catalogue. Industry data shows WhatsApp catalogues lift DM-to-order conversion 2-3x in West African markets because friction at the bottom of the funnel drops. The highest-leverage funnel fix is:", opts: ["Buy IG ads to push more traffic", "Open TikTok for younger buyers", "Set up the WhatsApp Business catalogue. Her bottleneck isn't acquisition (35 enquiries is healthy) — it's bottom-funnel conversion. Fixing conversion from 8% to 16-24% on existing DM volume produces more revenue than doubling top-of-funnel reach. Always optimise the leakiest stage of the funnel first", "Switch FB Page to a Group"], correct: 2 },
    { q: "A trainee cross-posts the SAME 60-second vertical video + caption + hashtags to FB, IG Reels, and TikTok. Reach: 280 (FB), 320 (IG), 180 (TikTok) — far below baseline. Each platform's algorithm uses different signals (caption length, hook style, native pacing) to decide amplification. The marketing principle being violated is:", opts: ["Wrong length for all three", "Channel-specific creative is a positioning decision: identical content across platforms ignores that each algorithm has a different audience, retention model, and ranking signal. The same asset with platform-native cuts and captions typically lifts reach 2-4x per platform — the time cost of three edits is the cheapest distribution gain available. Cross-posting identical assets is the equivalent of running the same TV ad on every channel without rights to do so", "Wrong time of day", "Delete two so one keeps it"], correct: 1 },
    { q: "A stale Instagram profile in Accra: faded landscape photo, bio reads \"Living my best life DM for info,\" no contact button, last post 11 weeks ago. Cold-traffic profile-to-follow conversion is currently 0.8% (industry benchmark: 4-6%). Profile is the landing page for every piece of content. Which fix produces the highest follow-rate lift?", opts: ["Buy followers to look established", "Run all four profile-anatomy fixes at once — recognisable thumbnail-scale profile pic, bio that states what + who + action, tappable WhatsApp contact, fresh post within 7 days. Profile is the conversion page for top-of-funnel traffic; fixing all four signals at once compounds because they're read together in 10 seconds. Doing one at a time produces marginal lift; all four is a step-change in cold-traffic conversion", "Start a new account", "Change the username"], correct: 1 },
    { q: "An events planner has 4 hrs/week for social. She currently runs FB + IG + TikTok + LinkedIn at quality 2/10 each. Her customer ROI data: FB drives 60% of bookings, IG 30%, TikTok 5%, LinkedIn 5%. Allocation discipline says invest where the revenue is. The right reallocation is:", opts: ["Add YouTube to round out presence", "Concentrate all 4 hrs on FB + IG (90% of revenue). Two platforms at quality 8/10 produces more bookings than four at 2/10 because algorithm reach scales non-linearly with consistency, AND her time goes to the platforms with proven conversion. Ignoring TikTok + LinkedIn until capacity grows is a portfolio decision: prune the 10% revenue tail to double-down on the 90%", "Outsource all four", "Post faster across all four"], correct: 1 },
    { q: "A boutique owner uses WhatsApp like personal chat — typing prices manually (40 min/day), sending launch messages 1-by-1 to 200 contacts (3 hrs/launch), missing overnight messages (estimated 12 lost enquiries/month at NLe 200 avg = NLe 2,400 lost revenue), unable to find repeat customers. The lifecycle/CRM cost is real. Which feature combination has the highest payback?", opts: ["Switch to Telegram", "Catalogue only — others aren't worth setup", "All four — catalogue (cuts price-typing to zero, frees ~13 hrs/month), broadcast lists (200-person launches in 5 min vs 3 hrs), away messages (recovers the NLe 2,400/month from overnight enquiries), labels (segments repeat customers for lifecycle marketing — the LTV multiplier). Combined ROI dwarfs the 2-hour setup cost; this is the cheapest CRM upgrade available", "Hire someone to reply"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 6", title: "Platform", titleAccent: "Deep Dives", subtitle: "Choosing your two primary platforms — and learning what wins on each.", meta: "Regium Touch × Aurora Foundation  |  Day 6  |  7 Slides" },
    { type: "stats", eyebrow: "FOCUS BEATS SPREAD", title: "Two platforms done well outperform four done poorly", intro: "Each platform rewards different behaviour, and Week 1's content has shown you what your audience actually responds to. Today we narrow the playing field. The platforms you ignore are as important as the ones you choose.", stats: [
      { num: "2 only", label: "primary platforms is the maximum a small-business owner can run well — anything more dilutes everywhere" },
      { num: "90%", label: "of small businesses in Sierra Leone underuse WhatsApp Business — the platform where the sale actually closes" },
      { num: "10 sec", label: "the window in which a stranger landing on your profile decides whether you're a real business worth following" },
    ], subheading: "What Today's Module Will Lock In", bullets: [
      "Optimise Facebook Page and WhatsApp Business profile end-to-end",
      "Optimise Instagram and TikTok profiles end-to-end",
      "Identify which 1–2 platforms deserve your primary focus — based on evidence, not assumption",
      "Use platform-specific features (Marketplace, Catalogue, Highlights) effectively",
      "Pass the four-test profile audit on your chosen primary platform before you leave the room today",
    ] },
    { type: "grid", eyebrow: "THE 4 PLATFORMS — PICK TWO", title: "Each rewards different behaviour. Choose by customer, not by trend.", subtitle: "Don't choose by what's hot in the headlines. Choose by where your customer profile from Day 2 actually spends time, what you can produce, and how much weekly capacity you have.", items: [
      { num: "01", title: "Facebook — Largest Base", desc: "25+ in Sierra Leone, the biggest user base. Wins with Pages, Groups, Marketplace, and longer captions. Hashtags do almost nothing here — don't waste them.", icon: "👥" },
      { num: "02", title: "Instagram — Visual Credibility", desc: "18–35, visual-first. Reels for reach, feed for credibility, Highlights for storefront. Where new customers vet whether you're a real brand.", icon: "📸" },
      { num: "03", title: "TikTok — Algorithm-Driven Growth", desc: "Younger audience plus curious 30+. Hook-led, raw-feel content beats polish. Fast organic growth still possible if your hook lands in second one.", icon: "🎵" },
      { num: "04", title: "WhatsApp Business — Where Sales Close", desc: "Where Sierra Leonean sales actually close. Catalogue, broadcasts, away messages, labels. Underused by 90% of small businesses — your unfair advantage.", icon: "💬" },
    ], footer: "Rule: pick two. Dominate them. Ignore the rest until you have capacity. 'I'm on every platform' usually means 'I'm visible nowhere'." },
    { type: "principle", num: "01", title: "WhatsApp Business — Where the Sale Actually Closes", intro: "Other platforms drive awareness. WhatsApp closes the sale. In Sierra Leone, this is where the money moves — and 90% of small businesses are leaving the four power-features completely unused. Today we install all four. Once they're set up, they pay back forever.", sectionTitle: "The 4 Features That Turn WhatsApp from a Chat App Into a Sales Engine", sections: [
      { heading: "1. Catalogue — your storefront inside the chat", example: "Up to 500 products, each with photo, name, price, description. Customers browse without ever leaving the chat thread.", note: "Set this up once and you stop typing prices into messages 40 times a week. Every reply becomes 'tap the catalogue, the green linen dress is item 12.'" },
      { heading: "2. Broadcast lists — one message to many, individually", example: "Send a Friday restock announcement to 200 customers; each receives it as a private message, not a group chat.", note: "Better than WhatsApp groups for promotions because customers can't see each other and can't leave the conversation public. Avoids the spam-feeling that kills group blasts." },
      { heading: "3. Away messages — the auto-reply that holds trust overnight", example: "'Thanks for your message — we reply within 1 hour during business hours (Mon–Fri 9am–6pm). For urgent orders, please reply URGENT.'", note: "Customers who message at 11pm don't feel ignored. The away message buys you time to sleep without losing the relationship — and the URGENT codeword filters real urgency from politeness." },
      { heading: "4. Labels — your CRM hidden inside WhatsApp", example: "Tag every chat: 'New enquiry', 'Order placed', 'Awaiting payment', 'Delivered', 'Repeat customer'. Filter by label any time.", note: "You stop losing customers in the noise. Find every 'Repeat customer' in 5 seconds for a loyalty broadcast. The single feature that compounds the most over the year." },
    ], rule: "WhatsApp Business is not personal WhatsApp with a green badge. It's a sales engine you've already paid for in installation. Set up all four features in one afternoon — they pay you back every week for the rest of the business's life." },
    { type: "comparison", eyebrow: "SCATTERED PRESENCE vs FOCUSED PRESENCE", title: "Same hours per week, two completely different business outcomes", subtitle: "Most small-business owners have 4–6 hours a week for social media. Where those hours go decides whether the work compounds or evaporates.", left: { title: "Scattered — 'I'm on every platform'", color: "#EF4444", items: [
      { strong: "All four platforms at once — Facebook, Instagram, TikTok, WhatsApp", note: "Each gets one mediocre post a week. Quality drops everywhere. The algorithm starves all four because none gets enough signal to amplify." },
      { strong: "Same content cross-posted identically across every platform", note: "Vertical TikTok-style video on Facebook reads as foreign. Long Facebook caption on TikTok reads as boring. Each platform's algorithm reacts negatively." },
      { strong: "WhatsApp treated as personal chat — no catalogue, no labels, no away message", note: "The platform where Sierra Leonean sales actually close is the one feature she has not set up. Awareness is everywhere; conversion is nowhere." },
      { strong: "Bio frozen from the day the page was created, last post 6 weeks ago on most platforms", note: "Stale signals everywhere. Algorithms penalise dormant pages. New visitors land and bounce within ten seconds." },
    ] }, right: { title: "Focused — Two platforms, dominated", color: "#10B981", items: [
      { strong: "One primary platform (where the customer is) + one secondary (where the content can be repurposed)", note: "Both posted to daily or near-daily. Both fully optimised. Algorithm rewards the consistent signal with reach." },
      { strong: "Content adapted per platform — same idea, different cut, different caption length, different hook style", note: "TikTok edit is hook-led and raw. Instagram edit is paced and aesthetic. Facebook caption is longer. Each algorithm reads native content and amplifies." },
      { strong: "WhatsApp Business set up end-to-end: catalogue, broadcasts, away message, labels", note: "Awareness on the primary platform feeds into the WhatsApp catalogue where the actual sale closes. The funnel is wired correctly." },
      { strong: "Profile audited and refreshed quarterly: bio current, last post within 7 days, contact tappable", note: "Stranger lands on the page and understands what she sells in under ten seconds. The page passes the audition every time." },
    ] }, footer: "Rule: focus beats spread. The platforms you ignore are as important as the ones you choose — they're hours saved for the two that count." },
    { type: "table", title: "The Six-Point Profile Anatomy — Audit Both Your Platforms Today", subtitle: "Optimise these once. Every customer who lands on your page from this Friday onwards benefits forever. The four-test version of this is your exercise; the full six is what every business profile actually needs.", columns: ["Element", "What 'Good' Looks Like", "Why It Matters"], rows: [
      ["Profile picture", "Logo or face. Recognisable at thumbnail size. Identical across all platforms.", "Customers see the picture before they read anything. Recognition at thumbnail decides whether they tap or scroll."],
      ["Bio / About", "What you do · who you serve · what action to take. In one line.", "Stranger should understand the brand in 10 seconds. 'Living my best life 💕' tells her nothing actionable."],
      ["Contact details", "WhatsApp number first. Then phone. Then email. All tappable.", "WhatsApp is where the sale closes — it has to be one tap away. Anything else is friction in the funnel."],
      ["Pinned post / Highlight", "Your best work or your offer. The first thing visitors see after the bio.", "First impression management. The pin is the headline of the entire profile — it should sell, not just exist."],
      ["Posting cadence", "Last post within 7 days. Algorithms penalise stale pages.", "An 11-week-old last post tells the algorithm and the visitor: this business may not exist anymore. Trust evaporates."],
      ["Visual consistency", "First 9 posts look like the same brand. Filter, frame, feel.", "Grid view is the audition. Visitor decides 'real brand or weekend hobby?' from the top three rows of your feed."],
    ], footer: "Rule: a profile is read in grid view first, post-by-post second. Optimise for the ten-second impression — that's the audition every new visitor runs." },
    { type: "exercise", title: "Customer Treasure Hunt and Five-Minute Profile Audit", intro: "Two assignments today. Both end with a written, justified decision and a profile that passes the four-test audit before you leave the room.", items: [
      { num: "1", copy: "Spend 5 minutes on each platform: Facebook, Instagram, TikTok, WhatsApp Business catalogues. On each, search 3 keywords related to YOUR business category (e.g., 'Freetown wedding cakes').", answer: "Note for each: how active are accounts in your category? Are people commenting? Asking real buying questions, or just compliments? Real engagement is your signal." },
      { num: "2", copy: "Rank the four platforms 1–4 by where your real customer is most engaged. Write down the top two and three sentences justifying each choice. Those two are your primary and secondary; the other two you ignore until you have capacity.", answer: "Your platform choice is now based on evidence, not assumption. From this point forward, every hour you spend on a platform that isn't in your top two is an hour stolen from the two that count." },
      { num: "3", copy: "Open your chosen primary platform's profile. Run the 4-test audit — (a) profile picture clearly visible at thumbnail size? (b) bio states what you do + who you serve + the action to take? (c) first 3 posts make the brand readable in 10 seconds? (d) WhatsApp / phone / email tappable?", answer: "Most profiles fail at least two of these tests. Fix every No before you leave the room today — these are the four signals every new visitor reads inside ten seconds." },
      { num: "4", copy: "Set up your WhatsApp Business catalogue with at least 5 products (photos, names, prices). Write an away message in your brand voice. Create three labels: 'New enquiry', 'Order placed', 'Repeat customer'.", answer: "WhatsApp is now wired as the sales engine, not a chat app. Awareness from your two chosen platforms now lands in a thread that closes — catalogue, response time, and a way to find every customer again." },
    ] },
  ],
};
