// Social Media Marketing — Day 8: Analytics & Community
export const smmDay8Module = {
  id: "smm08",
  title: "Day 8 — Analytics & Community",
  type: "Rich Module",
  duration: "5h",
  desc: "Reading numbers, replying to customers, handling complaints. The systems that turn followers into income — separating signal from noise, drafting DM templates that don’t sound robotic, and a 3-step protocol for the complaints every business eventually faces.",
  topics: ["Vanity vs. Business Metrics", "The 4 Metrics That Matter", "Weekly Review System", "DM Templates", "Public Complaint Protocol", "Capstone Prep"],
  quiz: [
    { q: "Hawa opens her Instagram insights on Friday afternoon. Followers: +47 this month. Total likes: 2,300. Reach: 4,800 unique. Engagement rate: 1.2%. Profile visits: 38. DMs leading to enquiries: 0. She wants to celebrate the follower bump. What should she actually focus on?", opts: ["The +47 followers — community is everything", "The 2,300 total likes — it shows resonance", "The zero enquiry-DMs. Reach + likes are vanity if no one’s reaching out. Followers and likes feel good but tell her nothing about whether the business grew. She needs to fix CTAs next week, not throw a party", "The total likes divided by followers"], correct: 2 },
    { q: "A customer DMs: “How much is the green dress?” The trainee’s saved template starts with “Hello valued customer, thank you for your enquiry…” She wonders why her response rate is dropping. What’s the real diagnosis?", opts: ["She needs to send the template faster", "The template sounds robotic. Real customers feel it instantly. The Day 8 price-enquiry template uses the customer’s name, the actual product name, the price, and a soft up-question (‘would you like to see more options?’) — warm, specific, human", "She should add more emojis to the template", "She should ignore short DMs and only reply to long ones"], correct: 1 },
    { q: "An angry customer comments publicly under your latest post: “My order was 3 days late. I want my money back. I’m posting this everywhere.” It’s 9am. What’s the correct first move within the next hour?", opts: ["Delete the comment to protect the brand", "Reply publicly with a long defensive explanation of why the delay happened", "Reply publicly within 1 hour — brief, calm, no defensiveness: ‘We hear you. Sending you a DM now.’ Then resolve privately, then return publicly to close the loop. Every customer who hasn’t complained yet is watching", "Wait 24 hours so emotions cool down before responding"], correct: 2 },
    { q: "Adama runs her first weekly review. She finds: highest reach was a ‘behind the scenes’ Reel posted Tuesday 7pm; highest engagement was a customer testimonial carousel; profile visits spiked on Wednesday after a product reveal. What does the data tell her to do next week?", opts: ["Post the same content at the same times — repeat exact format and rhythm. Reach winners signal distribution, engagement winners signal resonance, and profile-visit spikes signal intent. Replicate, don’t reinvent", "Switch entirely to TikTok since Reels did well", "Post twice as often to push the numbers higher", "Stop posting testimonials — engagement isn’t reach"], correct: 0 },
    { q: "A potential partner DMs: “Hey love! I run a lifestyle blog with 50K followers. We’d love to feature you — can you send three free pieces by Friday for promo?” The trainee feels flattered and is about to say yes. What’s the right reply?", opts: ["Send all three pieces — exposure is exposure", "Use the partnership-pitch template: ‘Thanks for thinking of us! Send me what you’re proposing and a link to your work. We review partnerships once a month.’ Slows it down, asks for proof, signals you’re a real business — not a free-product vending machine", "Block the account immediately as a scam", "Send one piece for free and ask for two paid"], correct: 1 },
    { q: "It’s the night before her capstone. Mariama has 30 minutes and is panicking. She has all 8 days of work but no clear plan for the 10-minute presentation tomorrow. What’s the highest-leverage way to use this last 30 minutes?", opts: ["Rewrite all her slides from scratch", "Memorise a script word-for-word so she doesn’t freeze", "Time herself once through the 6-section structure: 60s business+customer, 60s brand, 2min content strategy, 3min sample posts, 2min 30-day plan, 1min the ad. Speak it out loud once. Tomorrow is a celebration, not an exam", "Watch other people’s capstones on YouTube for inspiration"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 8", title: "Analytics &", titleAccent: "Community", subtitle: "Reading numbers, replying to customers, handling complaints. The systems that turn followers into income.", meta: "Regium Touch × Aurora Foundation  |  Day 8  |  7 Slides" },
    { type: "stats", eyebrow: "THE DATA TRAP", title: "Most insights tabs make you feel productive without being useful", intro: "Followers, likes, post views — they’re real numbers but they don’t tell you what to change. Today: separate the signal from the noise, then build the conversation systems that turn the signal into actual income.", stats: [
      { num: "4", label: "metrics actually worth tracking — reach, engagement rate, profile visits + saves, DMs & conversions" },
      { num: "5 min", label: "weekly review is all it takes — every Friday afternoon, four prompts, a notebook" },
      { num: "1 hr", label: "maximum window to acknowledge a public complaint before silence becomes the story" },
    ], subheading: "What Day 8 Replaces in Your Workflow", bullets: [
      "Stop tracking follower count, total likes, and story views as success",
      "Start tracking the 4 business metrics that signal real growth",
      "Keep 5 DM templates as drafts — customised, never paste-robotic",
      "Use a 3-step public complaint protocol before the first angry comment lands",
      "Walk into Day 9 with a 10-minute presentation already mapped out",
    ] },
    { type: "grid", eyebrow: "THE 4 METRICS THAT MATTER", title: "Stop tracking likes. Start tracking these.", subtitle: "These four tell you whether your business is actually growing. The rest is decoration. If you only check four numbers a week, check these.", items: [
      { num: "01", title: "Reach", desc: "How many unique people saw it. Tells you whether your distribution is working — i.e. whether the algorithm is putting your content in front of new humans, not just the same 80.", icon: "\u{1F4E1}" },
      { num: "02", title: "Engagement Rate", desc: "Percentage of viewers who reacted. Tells you if the content is resonating. Low reach with high engagement = great content, distribution problem. Vice versa = distribution gift, weak content.", icon: "❤️" },
      { num: "03", title: "Profile Visits & Saves", desc: "Intent signals. People considering doing business with you. Saves especially — they’re bookmarking to come back. Tag those posts; you’ll repurpose the same hook all year.", icon: "\u{1F516}" },
      { num: "04", title: "DMs & Conversions", desc: "Action signals. The ones that pay your bills. If reach is rising and DMs are flat, your CTA isn’t working — that’s the diagnosis, not a vibe.", icon: "\u{1F4B0}" },
    ], footer: "Rule: vanity metrics feel good and tell you nothing. Business metrics feel less flattering and tell you what to change." },
    { type: "principle", num: "01", title: "Numbers Tell You What to Change. Conversations Turn Followers Into Customers.", intro: "Two skills sit underneath every social media business that earns money: reading the numbers honestly, and answering DMs like a real human. Most graduates do neither — they obsess over followers and let DMs sit for 12 hours. Here’s the system that fixes both.", sectionTitle: "The 4 Habits That Replace Vanity-Metric Anxiety", sections: [
      { heading: "1. The Friday 5-minute review", example: "Every Friday afternoon: highest-reach post? highest-engagement post? any profile visits or saves? how many DMs led to enquiries?", note: "Write the answers in a notebook. After 4 weeks, patterns emerge. After 12, you have a content playbook tuned to your customer." },
      { heading: "2. DM templates kept as drafts, never paste-robotic", example: "Price enquiry, time-waster, complaint, partnership pitch, follow-up. Five drafts in WhatsApp Business or phone notes — customised every time.", note: "Templates buy you speed. Customisation buys you trust. ‘Hi Aminata! The green dress is NLe 380…’ beats ‘Hello valued customer’ every single time." },
      { heading: "3. The 3-step public complaint protocol", example: "Within 1 hour: acknowledge publicly, brief and calm. In DM: resolve privately, listen fully, document the fix. Once resolved: return publicly, close the loop.", note: "How you handle one angry comment is watched by every customer who hasn’t complained yet. The public-private-public arc protects reputation while solving the actual problem." },
      { heading: "4. CTAs tied to the metric you care about", example: "If you want DMs, the CTA is ‘Message us’ — not ‘Like and comment.’ If you want saves, the CTA is ‘Save this for later.’", note: "The metric you track is the metric you should ask for. If reach is rising and DMs are flat, the post is missing the ask — not the audience." },
    ], rule: "Numbers tell you what to change. Conversations turn followers into customers. Both are skills, not luck. You now have systems for both." },
    { type: "comparison", eyebrow: "VANITY METRICS vs BUSINESS METRICS", title: "Two ways to look at the same insights tab", subtitle: "Same numbers visible to everyone. Most graduates obsess over the wrong half. Here’s the split.", left: { title: "Vanity Metrics (Feel Good. Tell You Nothing.)", color: "#EF4444", items: [
      { strong: "Follower count — celebrating +47 this month", note: "47 followers who don’t buy are noise. The number can climb for 12 months while revenue stays flat. Never the lead indicator." },
      { strong: "Total likes across all posts", note: "Likes are the cheapest action a viewer can take. They cost nothing emotionally and signal nothing about purchase intent." },
      { strong: "Total comments, mostly emojis and tags", note: "Looks like community. Often it’s friends being kind. Compare to actual buying enquiries — usually a 50:1 ratio." },
      { strong: "Story views — ‘so many people watched!’", note: "Stories are 3-second swipes. View count tells you the algorithm pushed it; not that anyone considered buying." },
    ] }, right: { title: "Business Metrics (Less Flattering. Actually Useful.)", color: "#10B981", items: [
      { strong: "Reach — unique people who actually saw it", note: "Distribution truth. If reach is dropping, the algorithm has cooled on your account or your posting rhythm dropped. Real diagnosis." },
      { strong: "Engagement rate — % of viewers who reacted", note: "Resonance truth. 1.5–3% is healthy for small accounts. Below 1% means the content didn’t earn the attention it got." },
      { strong: "Profile visits & saves — intent signals", note: "The viewer left the post and looked at YOU. Or saved it for later. Both are micro-purchases of attention. Track them." },
      { strong: "DMs & conversions — the ones that pay you", note: "The only metric tied directly to revenue. If this is flat for 4 weeks, every other metric is decoration. Fix the CTA, fix the funnel." },
    ] }, footer: "Rule: pick 2 business metrics to check weekly. Ignore the rest. Your weekly review takes 5 minutes and tells you exactly what to change." },
    { type: "table", title: "The 5 DM Templates You’ll Use Every Week", subtitle: "Keep these as drafts in WhatsApp Business or phone notes. Customise per customer; never paste robotic. The shape stays consistent — the words stay human.", columns: ["Scenario", "Template Skeleton", "Why This Shape Works"], rows: [
      ["Price enquiry", "“Hi [name]! Thanks for reaching out. The [product] is NLe X. We have it in [colours/sizes]. Would you like to see more options?”", "Uses her name, the actual product, real price, and ends with a soft up-question to keep the conversation alive."],
      ["Time-waster / endless questions", "“Happy to help. Our prices are listed in our catalogue. If you’re ready to order, send your size and I’ll get it ready.”", "Closes the loop politely. Stops you spending 40 minutes on someone who was never going to buy."],
      ["Complaint", "“I’m so sorry that happened. Tell me what went wrong and I’ll make it right today. What’s the order number?”", "Apologises first, takes ownership, asks for the data needed to fix it. No defensiveness, no blame-shifting."],
      ["Partnership pitch", "“Thanks for thinking of us! Send me what you’re proposing and a link to your work. We review partnerships once a month.”", "Slows the conversation down. Filters serious proposals from free-product hunts. Signals you’re a real business."],
      ["Public complaint (in comments)", "“We hear you. Sending you a DM now.”", "Brief, calm, no defensiveness. Visible to every customer watching. Then you resolve privately and return publicly."],
    ], footer: "Rule: templates buy you speed. Customisation buys you trust. Always swap in the customer’s name and product." },
    { type: "exercise", title: "Vanity-vs-Reality Audit + Capstone Prep", intro: "Two short tasks before you sleep. First: separate the signal from the noise on your own insights tab. Second: scaffold tomorrow’s 10-minute presentation so nerves drop and clarity rises.", items: [
      { num: "1", copy: "Open insights on your primary platform — last 30 days. Write down the one number that makes you feel good (likely follower count or total likes). Then find: reach, engagement rate, profile visits, DMs received.", answer: "The vanity number almost always looks better than the business numbers. That’s the trap. If your follower count grew but your DMs stayed at 0, the business didn’t grow — only the noise around it did. Write both columns side-by-side; the gap is the diagnosis." },
      { num: "2", copy: "Decide: which 2 business metrics will you check weekly from now on? Add a recurring Friday 4pm reminder titled ‘5-minute review.’ Use the 4 weekly review prompts: highest reach? highest engagement? any saves/profile visits? any real DMs?", answer: "Two is the maximum a busy founder will actually check. Most graduates pick reach + DMs (distribution + revenue). Some pick engagement rate + saves (resonance + intent). Either pair works. Three or more becomes a chore you’ll abandon by week 3." },
      { num: "3", copy: "Pair up. Person A is the angry customer (‘My order was 3 days late. I want my money back. I’m posting this everywhere’). Person B walks the 3-step protocol live: Acknowledge publicly → Resolve privately → Follow up publicly. Switch and run a second scenario.", answer: "Saying the words out loud — in front of a peer, with all the awkwardness — is what keeps you calm when it’s real. The first angry comment in your inbox always lands at the worst possible moment. Tonight you rehearse, so tomorrow’s shock is just a script." },
      { num: "4", copy: "Capstone prep: time yourself once through the 6-section structure — 60s business+customer (Day 2) → 60s brand (Day 2) → 2min content strategy (Day 3) → 3min sample posts (Days 4–5) → 2min 30-day plan → 1min your one ad (Day 7). Out loud. Phone timer running.", answer: "Tomorrow is a celebration, not an exam. The trainees who feel calmest tomorrow morning are the ones who said the words once tonight. If you go over 10 minutes, the next person loses time — that’s the only rule. Practise once, sleep, show up." },
    ] },
  ],
};
