// Social Media Marketing — Day 4: Visual Content Creation
export const smmDay4Module = {
  id: "smm04",
  title: "Day 4 — Visual Content Creation",
  type: "Rich Module",
  duration: "5h",
  desc: "Producing professional visuals using only your phone, Canva, and CapCut. Lighting, composition, brand kit, and short-form video — everything you need to make a feed look like a brand, not an afterthought.",
  topics: ["Smartphone Lighting", "Composition & Framing", "Canva Brand Kit", "CapCut Basics", "Anatomy of a Reel", "Asset Organisation"],
  quiz: [
    { q: "Adama sells handbags in Lagos targeting professional women (NGN 18,000–35,000/bag). Her A/B test on the same bag across two weeks: warm phone snapshots got 1.2% engagement; clean side-lit product shots got 3.4% engagement and 2.5x DM enquiries. Visual style is positioning. What does the data prove?", opts: ["Snapshots feel authentic — keep them; engagement is vanity", "Visual quality is the price-point signal her segment uses to vet legitimacy. For a premium-skewed audience, an amateur photo IS a positioning statement that says \"not for you\" — the 2.5x DM lift is the conversion cost of mismatched visual standards. The visuals must match the price tier she's claiming", "Side-light is overrated — it's the caption", "Switch to a cheaper segment"], correct: 1 },
    { q: "A trainee's last 9 posts: 9 different fonts, 7 different colour palettes, no consistent crop. Brand recall (\"can you describe this brand from memory?\") tested at 6%. Brand recall correlates with conversion at the bottom funnel because customers buy from brands they recognise. The fix with the highest brand-equity ROI is:", opts: ["Buy Canva Pro for premium templates", "Add more text to spell out the brand", "Set up the Canva Brand Kit ONCE (logo + 3 hex codes + 2 fonts) so every future design starts 80% on-brand by default. Visual consistency is the lowest-cost lever for unaided recall, and recall is what lets organic content compound instead of restarting brand-awareness from scratch every post", "Hire a designer for the first 10 posts"], correct: 2 },
    { q: "Fatou films a 22-second product Reel; the first second is a slow pan across an empty table. Drop-off at 1s = 78%. On Reels, the algorithm uses 1-second retention as the primary signal for whether to push the video to non-followers. The opening costs her acquisition reach. The marketing diagnosis is:", opts: ["The video is 2 seconds too long", "There's no hook in second one. The first second is the only attribution point that determines whether the algorithm treats this as discovery content (top-of-funnel acquisition) or buries it among existing followers. An empty pan signals \"not worth amplifying\" — the algorithmic cost is the loss of the cheapest organic acquisition channel small businesses have", "CapCut export quality", "Missing hashtags"], correct: 1 },
    { q: "A new visitor lands on a Nairobi boutique grid: mixed aspect ratios, stacked filters, giant centre watermark on every photo. Studies show visitors decide \"real business or hobby\" within 10 seconds of landing on a profile — which directly affects follow rate (top-of-funnel conversion). The single change that lifts follow rate fastest is:", opts: ["Add more filters", "Make watermarks bigger", "Standardise the aspect ratio (one ratio, applied across the grid) and strip filter stacks. Visual-system inconsistency is the loudest \"hobby\" signal a feed sends; the follow-rate cost on cold visitors is real and measurable. Operational fix, but it's solving an acquisition-conversion problem at the profile level — the most-visited \"landing page\" she has", "Delete the feed and restart"], correct: 2 },
    { q: "You finish Day 4 with 8 finished assets. You save them to camera roll among 4,000 personal photos. Three weeks later, when the Eid promotion needs visuals, you can't find anything and re-shoot from scratch — losing 3 hours that should have gone to ad management. The hidden marketing cost is:", opts: ["Lower export resolution", "Missed posting window", "The repurposing economy — well-organised assets get used 4–8 times across stories, posts, ads, and email. Disorganised assets become single-use, which inflates content cost-per-post and steals time from higher-leverage marketing work (audience-building, ad optimisation, DM follow-up). Folder discipline isn't admin; it's how content libraries compound ROI", "Missing watermarks"], correct: 2 },
    { q: "A trainee insists she needs a DSLR (NLe 8,000), ring light (NLe 1,200), and Adobe Premiere subscription before posting \"professional\" content. She has phone + window + Canva free + CapCut free, and NLe 500 total budget. The disciplined allocation is:", opts: ["She's right — phone content reads amateur", "Buy at minimum the ring light first", "Spend NLe 0 on equipment; spend NLe 500 on a small Meta test campaign once she has 30 days of phone-shot content. Equipment is rarely the bottleneck for sub-NLe 5K/month businesses; her real bottlenecks are positioning, cadence, and audience-targeting — none of which a DSLR fixes. The phone + window + free tools combo covers 95% of year-one needs, and the budget is better spent on distribution than production", "Wait until she affords the gear"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 4", title: "Visual Content", titleAccent: "Creation", subtitle: "Producing professional visuals using only your phone, Canva, and CapCut.", meta: "Regium Touch × Aurora Foundation  |  Day 4  |  7 Slides" },
    { type: "stats", eyebrow: "WHY VISUALS DECIDE EVERYTHING", title: "Customers decide in 3 seconds whether to keep scrolling", intro: "In that window, your photo decides whether the rest of your post is even read. The caption matters — but only if the visual earns it the chance. Visuals are the gate; copy is what's behind it.", stats: [
      { num: "3 sec", label: "the window in which a viewer decides whether to keep scrolling past your post" },
      { num: "65%", label: "of people are visual learners — the image teaches before the caption gets a chance" },
      { num: "10×", label: "engagement on posts with strong visuals vs posts where the image was an afterthought" },
    ], subheading: "What Today's Module Will Build Into Your Workflow", bullets: [
      "Apply lighting and composition principles using only a smartphone",
      "Build a Canva brand kit so every future design starts 80% on-brand by default",
      "Edit a short-form video on CapCut with cuts, captions, and music",
      "Organise content assets so they're findable and reusable next month, not lost in 4,000 camera-roll photos",
      "Spot the five amateur traps that mark a page in seconds — and stop doing them today",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF DAY 4", title: "Phone, Canva, CapCut, and a system to find it all again", subtitle: "Master these four and you can produce a week's content in a morning. Skip any one and the work won't compound.", items: [
      { num: "01", title: "Mobile Photography", desc: "Three rules fix 90% of bad business photos: light from the side, use the rule of thirds, clean the background. No ring light required.", icon: "📸" },
      { num: "02", title: "Canva Brand Kit", desc: "Logo, 3 brand colours, 2 brand fonts — set once. Every future design opens already on-brand. No more white-page blank stare.", icon: "🎨" },
      { num: "03", title: "CapCut Short-Form Video", desc: "Cut, trim, auto-captions, free music, 1080p export ready for Reels and TikTok. Free, on your phone, fast.", icon: "🎬" },
      { num: "04", title: "Asset Organisation", desc: "BusinessName / Week / Day folders. Findable, reusable, repurposable. A library, not a camera roll.", icon: "📁" },
    ], footer: "Rule: your phone is enough. Equipment is rarely the bottleneck — lighting choice, composition, and consistency are." },
    { type: "principle", num: "01", title: "Light — The Invisible Force", intro: "Same product, same phone, same person — different light, completely different post. Light is the single biggest variable separating a professional photo from an amateur one. The four rules below cover every situation you'll shoot in this programme.", sectionTitle: "The 4 Rules That Decide Every Photo You Take", sections: [
      { heading: "1. Light from the side, not behind you", example: "Stand the product on a table beside a window. Window to your left or right — never behind you, never behind the product.", note: "Side light gives natural depth and texture. Backlight turns the subject into a silhouette. This single rule fixes more amateur photos than any filter ever will." },
      { heading: "2. Turn on grid lines and use the rule of thirds", example: "Place the product where two grid lines cross — not dead-centre. Centre composition reads as snapshot; rule-of-thirds reads as composed.", note: "Every phone has grid lines hidden in camera settings. Turn them on once; they stay on for every shoot after." },
      { heading: "3. Clean the background before you press the shutter", example: "Wires, clutter, mess kill product shots. Plain wall, clean surface, breathing room around the subject.", note: "The cheapest professional upgrade you can make: clear three feet of wall and a square metre of table. That's the entire studio." },
      { heading: "4. Natural window light beats every ring light", example: "10am near a north-facing window outperforms a ₦300,000 light kit shot at midnight under household bulbs.", note: "Ring lights are useful for video where you control the frame. For product photography, find the window first." },
    ], rule: "Master light first. Filters, fonts, and editing all come after. A perfectly composed photo in bad light still looks bad; a simple photo in good light already looks like a brand." },
    { type: "comparison", eyebrow: "AMATEUR FEED vs ON-BRAND FEED", title: "Same products, two completely different perceived businesses", subtitle: "A new visitor decides whether you're 'a real business' inside ten seconds of landing on your grid. These are the signals.", left: { title: "Amateur Feed (Visitor Bounces)", color: "#EF4444", items: [
      { strong: "Three filters stacked on every photo", note: "Customers register 'fake' instantly. Over-filtered shots scream insecurity about the product itself." },
      { strong: "Walls of text typed inside the image", note: "Image becomes a poster, not a photo. Save the words for the caption — that's what captions exist for." },
      { strong: "Mixed aspect ratios across the grid", note: "Square, portrait, landscape thrown together looks chaotic in the feed view. Visitor reads 'no system here.'" },
      { strong: "Big watermark logo plastered across every photo", note: "Brand recognition without overkill is the goal. A subtle corner mark beats a logo mosaic every time." },
    ] }, right: { title: "On-Brand Feed (Visitor Follows)", color: "#10B981", items: [
      { strong: "One light, clean look applied through the brand kit", note: "Recognisable at a glance. Same filter logic, same colour temperature, same world." },
      { strong: "Photos do the showing; captions do the telling", note: "Image earns the three seconds; caption converts them into trust and an enquiry." },
      { strong: "Single aspect ratio across the grid (1080×1080 or 1080×1350)", note: "The grid view reads as one continuous brand. Visitor's eye moves smoothly from post to post." },
      { strong: "Logo subtle or absent; brand carried by colour, font, framing", note: "Brand recognition built into the visual system itself, not stamped on top of every shot." },
    ] }, footer: "Rule: a feed is read in grid view first, post-by-post second. Optimise for the grid impression — that's the audition every new visitor runs." },
    { type: "table", title: "Anatomy of a 15-Second Reel", subtitle: "Most reels die in the first second. The four parts below decide whether yours doesn't — and they hold whether you're filming product, behind-the-scenes, or a tutorial.", columns: ["Window", "Job", "What Belongs Here"], rows: [
      ["0–1s", "Hook", "A face, motion, a bold question, or visible transformation. Something that stops the thumb. Without this, nothing else lands."],
      ["1–10s", "Promise", "Quick demonstration of the value the viewer gets if she watches — the 'why this is worth 10 more seconds.'"],
      ["10–14s", "Payoff", "Deliver what the hook promised. Reveal, transformation, before-and-after, or punchline. The reason she stayed."],
      ["14–15s", "CTA", "One specific action: 'Comment X', 'DM us', 'Save this'. One ask, not three. Two CTAs equal zero CTAs."],
      ["After post", "Caption hook", "First line of the caption matches the reel's opening promise. Same idea, written form. The algorithm reads both."],
    ], footer: "Rule: if you can't name what's happening in second one of your reel, the reel doesn't have a hook — re-shoot the opening, not the rest." },
    { type: "exercise", title: "The Three-Asset Workshop — Phone, Canva, CapCut", intro: "By the end of today, three real assets are saved into a properly named folder on your phone. Not theory — finished work. Use only your phone, Canva free, and CapCut free.", items: [
      { num: "1", copy: "Shoot one product photo using the side-light rule. Take three versions: side light, backlight, overhead. Compare on your screen and keep the side-light shot.", answer: "You will see — not just be told — how light determines everything. Save the winning shot to a folder named 'BusinessName / Week 1 / Day 4 / Photo'." },
      { num: "2", copy: "Open Canva → Brand Hub → Brand Kits → Create. Upload your logo, add 3 brand hex codes from your Day 2 work, pick 2 fonts (one heading, one body). Then open a 1080×1080 template and apply the kit.", answer: "Every future Canva design now starts 80% on-brand by default. No more blank-page paralysis, no more eyeballing colours that don't match last week's post." },
      { num: "3", copy: "Build a 3-slide carousel in Canva using your brand kit. Slide 1 = hook, slide 2 = teach one thing, slide 3 = single CTA. Export as PNG sequence.", answer: "Carousels earn the highest save-rates of any post format — and saves are the strongest signal you can give the algorithm that your content is worth amplifying." },
      { num: "4", copy: "Film a 15-second reel on your phone. Edit in CapCut: one cut, auto-captions on, one music track from the free library, export at 1080p. Save into 'BusinessName / Week 1 / Day 4 / Reel'.", answer: "By 2:00 PM today, three real assets are saved into a properly-named folder. That folder is your content library — the start of a system you'll find again next month." },
    ] },
  ],
};
