// Social Media Marketing — Day 4: Visual Content Creation
export const smmDay4Module = {
  id: "smm04",
  title: "Day 4 — Visual Content Creation",
  type: "Rich Module",
  duration: "5h",
  desc: "Producing professional visuals using only your phone, Canva, and CapCut. Lighting, composition, brand kit, and short-form video — everything you need to make a feed look like a brand, not an afterthought.",
  topics: ["Smartphone Lighting", "Composition & Framing", "Canva Brand Kit", "CapCut Basics", "Anatomy of a Reel", "Asset Organisation"],
  quiz: [
    { q: "You shoot the same handbag three times: once with a window directly behind you, once with the window to your left, and once under a single bright ceiling bulb. Which photo earns the post — and why?", opts: ["The ceiling-bulb shot — overhead light is the most consistent, so the bag looks identical across all your future posts", "The side-window shot — natural light coming from the side gives depth and texture; the backlit version turns the bag into a silhouette and the overhead version reads flat and amateur", "The window-behind-you shot — backlight makes the bag glow and looks premium on Instagram", "Any of the three — modern phone cameras auto-correct lighting, so the difference doesn't really show in the final post"], correct: 1 },
    { q: "A trainee opens Canva, picks a square template, drags her logo onto it, eyeballs a colour she likes, and types her caption in whichever font Canva defaulted to. Three days later she does the exact same thing for a new post — and the two designs don't look related. The single highest-leverage fix is:", opts: ["Buy Canva Pro so she has access to premium templates", "Add more text to each design so the brand identity is spelled out", "Set up the Canva Brand Kit once — upload logo, save 3 brand hex codes, lock in 2 brand fonts — so every future design starts 80% on-brand by default", "Hire a designer for the first ten posts and copy them"], correct: 2 },
    { q: "You film a 22-second product reel. The first second is a slow pan across an empty table before the product appears. Views drop off a cliff at second 1 and the reel barely leaves your followers. Most likely cause:", opts: ["The video is two seconds too long for Reels", "There's no hook in the first second — a face, motion, or question has to stop the thumb before anything else can land; a slow empty pan tells the algorithm and the viewer to scroll", "CapCut's default export quality is too low for Reels", "You forgot to add hashtags in the caption"], correct: 1 },
    { q: "Your feed grid has one square photo, one tall portrait, one landscape screenshot, two photos with three filters stacked, and a product shot with a giant watermark across the centre. A new visitor lands on it. The fastest single change that lifts perceived professionalism is:", opts: ["Add even more filters so the feed feels stylised", "Make the watermarks bigger so the brand is unmissable", "Standardise the aspect ratio (pick one — 1080×1080 or 1080×1350) and strip the stacked filters; mixed ratios and filter overload are the two loudest 'amateur' signals in a feed", "Delete the feed and start over from zero"], correct: 2 },
    { q: "You finish Day 4 with 1 photo, a 3-slide carousel, and a 15-second reel. You save them straight to your phone's camera roll alongside 4,000 personal photos. Two weeks later you can't find any of them. The discipline you skipped was:", opts: ["Exporting at higher resolution", "Posting them within 24 hours of creation", "Folder organisation — a simple BusinessName / Week1 / Day4 structure means assets are findable and reusable; a camera roll with 4,000 photos is not a content library", "Adding watermarks to every asset"], correct: 2 },
    { q: "A trainee insists she needs a DSLR, a ring light, and Adobe Premiere before she can post 'professional' content. She has a phone, a window, Canva free, and CapCut free. The accurate response is:", opts: ["She's right — phone content always reads as amateur on business pages", "She should at minimum invest in a ring light before launching", "Her phone + window light + Canva + CapCut covers 95% of everything a small business needs in year one; equipment is rarely the bottleneck — lighting choice, composition, and consistency are", "Wait until she can afford the gear, then start posting"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 4", title: "Visual Content", titleAccent: "Creation", subtitle: "Producing professional visuals using only your phone, Canva, and CapCut.", meta: "Regium Touch × Aurora Foundation  |  Day 4  |  7 Slides" },
    { type: "stats", eyebrow: "WHY VISUALS DECIDE EVERYTHING", title: "Customers decide in 3 seconds whether to keep scrolling", intro: "In that window, your photo decides whether the rest of your post is even read. The caption matters — but only if the visual earns it the chance. Visuals are the gate; copy is what's behind it.", stats: [
      { num: "3 sec", label: "the window in which a viewer decides whether to keep scrolling past your post" },
      { num: "65%", label: "of people are visual learners — the image teaches before the caption gets a chance" },
      { num: "10×", label: "engagement on posts with strong visuals vs posts where the image was an afterthought" },
    ], subheading: "What Today's Module Will Build Into Your Workflow", bullets: [
      "Apply lighting and composition principles using only a smartphone",
      "Build a Canva brand kit so every future design starts 80% on-brand by default",
      "Edit a short-form video on CapCut with cuts, captions, and music",
      "Organise content assets so they're findable and reusable next month, not lost in 4,000 camera-roll photos",
      "Spot the five amateur traps that mark a page in seconds — and stop doing them today",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF DAY 4", title: "Phone, Canva, CapCut, and a system to find it all again", subtitle: "Master these four and you can produce a week's content in a morning. Skip any one and the work won't compound.", items: [
      { num: "01", title: "Mobile Photography", desc: "Three rules fix 90% of bad business photos: light from the side, use the rule of thirds, clean the background. No ring light required.", icon: "📸" },
      { num: "02", title: "Canva Brand Kit", desc: "Logo, 3 brand colours, 2 brand fonts — set once. Every future design opens already on-brand. No more white-page blank stare.", icon: "🎨" },
      { num: "03", title: "CapCut Short-Form Video", desc: "Cut, trim, auto-captions, free music, 1080p export ready for Reels and TikTok. Free, on your phone, fast.", icon: "🎬" },
      { num: "04", title: "Asset Organisation", desc: "BusinessName / Week / Day folders. Findable, reusable, repurposable. A library, not a camera roll.", icon: "📁" },
    ], footer: "Rule: your phone is enough. Equipment is rarely the bottleneck — lighting choice, composition, and consistency are." },
    { type: "principle", num: "01", title: "Light — The Invisible Force", intro: "Same product, same phone, same person — different light, completely different post. Light is the single biggest variable separating a professional photo from an amateur one. The four rules below cover every situation you'll shoot in this programme.", sectionTitle: "The 4 Rules That Decide Every Photo You Take", sections: [
      { heading: "1. Light from the side, not behind you", example: "Stand the product on a table beside a window. Window to your left or right — never behind you, never behind the product.", note: "Side light gives natural depth and texture. Backlight turns the subject into a silhouette. This single rule fixes more amateur photos than any filter ever will." },
      { heading: "2. Turn on grid lines and use the rule of thirds", example: "Place the product where two grid lines cross — not dead-centre. Centre composition reads as snapshot; rule-of-thirds reads as composed.", note: "Every phone has grid lines hidden in camera settings. Turn them on once; they stay on for every shoot after." },
      { heading: "3. Clean the background before you press the shutter", example: "Wires, clutter, mess kill product shots. Plain wall, clean surface, breathing room around the subject.", note: "The cheapest professional upgrade you can make: clear three feet of wall and a square metre of table. That's the entire studio." },
      { heading: "4. Natural window light beats every ring light", example: "10am near a north-facing window outperforms a ₦300,000 light kit shot at midnight under household bulbs.", note: "Ring lights are useful for video where you control the frame. For product photography, find the window first." },
    ], rule: "Master light first. Filters, fonts, and editing all come after. A perfectly composed photo in bad light still looks bad; a simple photo in good light already looks like a brand." },
    { type: "comparison", eyebrow: "AMATEUR FEED vs ON-BRAND FEED", title: "Same products, two completely different perceived businesses", subtitle: "A new visitor decides whether you're 'a real business' inside ten seconds of landing on your grid. These are the signals.", left: { title: "Amateur Feed (Visitor Bounces)", color: "#EF4444", items: [
      { strong: "Three filters stacked on every photo", note: "Customers register 'fake' instantly. Over-filtered shots scream insecurity about the product itself." },
      { strong: "Walls of text typed inside the image", note: "Image becomes a poster, not a photo. Save the words for the caption — that's what captions exist for." },
      { strong: "Mixed aspect ratios across the grid", note: "Square, portrait, landscape thrown together looks chaotic in the feed view. Visitor reads 'no system here.'" },
      { strong: "Big watermark logo plastered across every photo", note: "Brand recognition without overkill is the goal. A subtle corner mark beats a logo mosaic every time." },
    ] }, right: { title: "On-Brand Feed (Visitor Follows)", color: "#10B981", items: [
      { strong: "One light, clean look applied through the brand kit", note: "Recognisable at a glance. Same filter logic, same colour temperature, same world." },
      { strong: "Photos do the showing; captions do the telling", note: "Image earns the three seconds; caption converts them into trust and an enquiry." },
      { strong: "Single aspect ratio across the grid (1080×1080 or 1080×1350)", note: "The grid view reads as one continuous brand. Visitor's eye moves smoothly from post to post." },
      { strong: "Logo subtle or absent; brand carried by colour, font, framing", note: "Brand recognition built into the visual system itself, not stamped on top of every shot." },
    ] }, footer: "Rule: a feed is read in grid view first, post-by-post second. Optimise for the grid impression — that's the audition every new visitor runs." },
    { type: "table", title: "Anatomy of a 15-Second Reel", subtitle: "Most reels die in the first second. The four parts below decide whether yours doesn't — and they hold whether you're filming product, behind-the-scenes, or a tutorial.", columns: ["Window", "Job", "What Belongs Here"], rows: [
      ["0–1s", "Hook", "A face, motion, a bold question, or visible transformation. Something that stops the thumb. Without this, nothing else lands."],
      ["1–10s", "Promise", "Quick demonstration of the value the viewer gets if she watches — the 'why this is worth 10 more seconds.'"],
      ["10–14s", "Payoff", "Deliver what the hook promised. Reveal, transformation, before-and-after, or punchline. The reason she stayed."],
      ["14–15s", "CTA", "One specific action: 'Comment X', 'DM us', 'Save this'. One ask, not three. Two CTAs equal zero CTAs."],
      ["After post", "Caption hook", "First line of the caption matches the reel's opening promise. Same idea, written form. The algorithm reads both."],
    ], footer: "Rule: if you can't name what's happening in second one of your reel, the reel doesn't have a hook — re-shoot the opening, not the rest." },
    { type: "exercise", title: "The Three-Asset Workshop — Phone, Canva, CapCut", intro: "By the end of today, three real assets are saved into a properly named folder on your phone. Not theory — finished work. Use only your phone, Canva free, and CapCut free.", items: [
      { num: "1", copy: "Shoot one product photo using the side-light rule. Take three versions: side light, backlight, overhead. Compare on your screen and keep the side-light shot.", answer: "You will see — not just be told — how light determines everything. Save the winning shot to a folder named 'BusinessName / Week 1 / Day 4 / Photo'." },
      { num: "2", copy: "Open Canva → Brand Hub → Brand Kits → Create. Upload your logo, add 3 brand hex codes from your Day 2 work, pick 2 fonts (one heading, one body). Then open a 1080×1080 template and apply the kit.", answer: "Every future Canva design now starts 80% on-brand by default. No more blank-page paralysis, no more eyeballing colours that don't match last week's post." },
      { num: "3", copy: "Build a 3-slide carousel in Canva using your brand kit. Slide 1 = hook, slide 2 = teach one thing, slide 3 = single CTA. Export as PNG sequence.", answer: "Carousels earn the highest save-rates of any post format — and saves are the strongest signal you can give the algorithm that your content is worth amplifying." },
      { num: "4", copy: "Film a 15-second reel on your phone. Edit in CapCut: one cut, auto-captions on, one music track from the free library, export at 1080p. Save into 'BusinessName / Week 1 / Day 4 / Reel'.", answer: "By 2:00 PM today, three real assets are saved into a properly-named folder. That folder is your content library — the start of a system you'll find again next month." },
    ] },
  ],
};
