// Social Media Marketing — Day 1: Foundations & Mindset
// Source: Regium Touch × Aurora Foundation 9-day cohort programme
export const smmDay1Module = {
  id: "smm01",
  title: "Day 1 — Foundations & Mindset",
  type: "Rich Module",
  duration: "5h",
  desc: "The four pillars that turn random posting into real marketing. Mindset shift, the five traps, SMART goal-setting, and an honest audit of your current online presence.",
  topics: ["Posting vs Marketing", "The Four Pillars", "The Five Traps", "SMART Goals", "Presence Audit", "Mindset Shift"],
  quiz: [
    { q: "Aminata's bakery has 1,420 Instagram followers but only 1.4% reach. A neighbour's bakery has 612 followers and 8.2% reach. Both post once weekly. From a marketing standpoint, which signal matters most for next quarter's plan?", opts: ["Aminata's larger follower count — bigger pool to convert", "The neighbour's reach rate — algorithm signal that her audience-content fit is stronger; cheaper to convert per follower than to grow Aminata's dormant audience", "Both are equal because reach × followers gives the same impressions", "Neither — engagement rate is what counts"], correct: 1 },
    { q: "Fatu writes her programme goal as: \"I want to grow my Instagram and get more sales this year.\" Apply the SMART test. Which rewrite passes all five letters?", opts: ["\"Get more Instagram followers and sales\"", "\"50 product enquiries from Instagram DMs by 30 June 2026\"", "\"Become the top bakery in Freetown on Instagram\"", "\"Post every day for the next year\""], correct: 1 },
    { q: "You audit your page using the 12-question checklist. You score 4/12. Three of your weak items: no consistent voice, no measurement, last post 14 days ago. Which fix produces the largest near-term marketing lift?", opts: ["Voice — but voice work takes weeks of writing to land", "Resume posting on a 7-day cadence — algorithm decay is the biggest blocker; voice and measurement compound on top of consistent activity", "Hire a designer to refresh the visual style", "Buy followers to look established"], correct: 1 },
    { q: "A trainee says: \"I'll just post when I have something to sell.\" From the Posting vs Marketing framework, what's the underlying error?", opts: ["She's not posting enough", "She's treating social as a sales channel only — promotional posts without value/engagement layers train followers to ignore her until she sells, collapsing reach over time", "She needs a better camera", "She needs more hashtags"], correct: 1 },
    { q: "You have 8 hours per week for marketing. The Four Pillars are Strategy, Content, Engagement, Measurement. A trainee currently spends 7 hours on Content (creating posts) and 1 hour on the rest. What's the disciplined reallocation?", opts: ["Spend more time on content — content is what people see", "Cut content to 4 hours, add 1 hour Strategy + 2 hours Engagement + 1 hour Measurement — most underperforming pages overspend on creation and underspend on conversation and learning", "Outsource content entirely", "Add a fifth pillar"], correct: 1 },
    { q: "After Day 1's audit, two trainees compare scores: Trainee A scores 2/12. Trainee B scores 9/12. Both join Day 2. Which trainee will likely see larger marketing gains over the 9 days, and why?", opts: ["Trainee B — better starting point compounds faster", "Trainee A — larger gap means more low-hanging fixes (bio, contact details, business profile, pinned post) that lift reach + conversion before the harder strategy work begins", "They'll see equal gains because they attend the same sessions", "Trainee B because she has more followers"], correct: 1 },
  ],
  slides: [
    {
      type: "cover",
      module: "DAY 1",
      title: "Foundations",
      titleAccent: "& Mindset",
      subtitle: "The four pillars that turn random posting into real marketing.",
      meta: "Regium Touch × Aurora Foundation  ·  Monday 11 May 2026  ·  16 Slides",
    },
    {
      type: "stats",
      eyebrow: "WELCOME",
      title: "Welcome to your nine-day transformation",
      intro: "Over the next nine days, you will move from posting occasionally to marketing strategically. That shift — small in language, large in result — is what turns a feed into a funnel.",
      stats: [
        { num: "9", label: "Days of intensive training" },
        { num: "45", label: "Hours of hands-on practice" },
        { num: "1", label: "Transformed business" },
      ],
      subheading: "What you will walk out of Day 9 with",
      bullets: [
        "A written brand voice, customer profile, and one-line positioning statement",
        "A 30-day content calendar built around your own pillars",
        "A measurable SMART goal you can defend to your accountant",
        "A working audit of your own page, with strengths and 8-day fixes named",
      ],
    },
    {
      type: "takeaways",
      title: "Who this programme is built for",
      items: [
        "Women running an existing business — registered or informal",
        "Aspiring founders preparing to launch in the next 6 months",
        "Startup owners building their first serious online presence",
        "Established business owners ready to move from occasional posting to systematic marketing",
        "Women who handle the marketing side of a family or partnership business",
      ],
    },
    {
      type: "takeaways",
      title: "Day 1 — Learning Objectives",
      items: [
        "Articulate why most small businesses fail at social media",
        "Identify the four pillars of effective social media marketing",
        "Define a personal SMART goal for your business",
        "Complete an honest audit of your current online presence",
      ],
      next: "By the end of today, you'll have your goal in writing and your weak spots named.",
    },
    {
      type: "stats",
      eyebrow: "THE LANDSCAPE",
      title: "Where your customers actually are",
      intro: "More Sierra Leoneans are online than ever. The question is no longer whether your business should be there — it's whether the version of your business they find when they search is the one you want them to remember.",
      stats: [
        { num: "75%", label: "of urban Sierra Leoneans use a smartphone daily" },
        { num: "2.5h", label: "average daily time on social media" },
        { num: "9 / 10", label: "customers check your page before buying" },
      ],
      subheading: "What this means for your business",
      bullets: [
        "Your page is now the first impression — earlier than a website, earlier than word of mouth",
        "Search now starts on social, not on Google — Instagram, TikTok, and WhatsApp are the new shopfronts",
        "A neglected page reads as a closed shop — even if your physical business is open",
        "Two and a half hours of attention is up for grabs — daily, from your specific customers",
      ],
    },
    {
      type: "comparison",
      eyebrow: "A TALE OF TWO BUSINESSES",
      title: "Same product. Same neighbourhood. Different approach.",
      subtitle: "Twelve months apart, both started from zero followers.",
      left: {
        title: "Business A — Posting (the hustler)",
        color: "#EF4444",
        items: [
          { strong: "Posts when she remembers", note: "Bursts of activity, then 18-day silences. Algorithm forgets her between posts." },
          { strong: "Different style every time", note: "No recognisable look. Followers can't pattern-match her in a busy feed." },
          { strong: "Posts only when she has stock to sell", note: "Followers learn: she only shows up to take their money." },
          { strong: "Doesn't know what's working", note: "Quietly wonders if social media is worth it. After 12 months: same business size." },
        ],
      },
      right: {
        title: "Business B — Marketing (the marketer)",
        color: "#10B981",
        items: [
          { strong: "Posts on a schedule she follows", note: "Algorithm rewards consistency. Reach grows even when individual posts don't go viral." },
          { strong: "Recognisable voice and visual style", note: "Followers spot her in two seconds — pattern recognition becomes brand equity." },
          { strong: "Mixes value with promotion", note: "80% gives — recipes, behind-the-scenes, customer stories. 20% sells. Followers stay engaged between asks." },
          { strong: "Reads insights weekly, adjusts monthly", note: "After 12 months: 3× the enquiries, regular customers, predictable revenue." },
        ],
      },
      footer: "The product is the same. The system around it is not. Marketing is the system.",
    },
    {
      type: "grid",
      eyebrow: "THE FOUR PILLARS",
      title: "The foundation of every session",
      subtitle: "Most small businesses fail at social media because they only invest in one or two of these. Over the next 9 days, we build all four.",
      items: [
        { num: "01", title: "Strategy", desc: "Brand, customer, positioning, content pillars. The decisions every post sits on top of.", icon: "🧭" },
        { num: "02", title: "Content", desc: "Visuals, copywriting, formats, platform-specific creation. The what.", icon: "✍️" },
        { num: "03", title: "Engagement", desc: "DMs, community, complaints, customer service. Where followers convert into customers.", icon: "💬" },
        { num: "04", title: "Measurement", desc: "Analytics, the four metrics that matter, paid ads performance. How you learn.", icon: "📊" },
      ],
      footer: "Days 1-3: Strategy. Days 4-6: Content. Day 7: Paid + Engagement. Day 8: Measurement. Day 9: Synthesis.",
    },
    {
      type: "comparison",
      eyebrow: "THE MINDSET SHIFT",
      title: "From posting to marketing",
      subtitle: "These two activities look identical from the outside. They are not the same thing.",
      left: {
        title: "Posting",
        color: "#EF4444",
        items: [
          { strong: "Reactive — \"what should I post today?\"", note: "Decision made in the moment. Quality and direction depend on mood." },
          { strong: "Inconsistent voice and look", note: "Each post feels like a different brand. Followers can't recognise you." },
          { strong: "Posts only when there's something to sell", note: "Algorithm and audience both punish the silences in between." },
          { strong: "Stops when life gets busy", note: "Marketing collapses with the first urgent personal week." },
        ],
      },
      right: {
        title: "Marketing",
        color: "#10B981",
        items: [
          { strong: "Strategic — driven by a plan, customer, and goal", note: "Posts decided in advance. The work shifts from creation to execution." },
          { strong: "Consistent voice and visual style", note: "Followers recognise you in two seconds. That recognition compounds into trust." },
          { strong: "Mix of value, promotion, and engagement", note: "80/20 rule: most posts give before they ask. Promotional posts perform better because trust was earned earlier." },
          { strong: "Continues when life gets busy — because it's a system", note: "Batched in advance. Scheduled. Resilient to your schedule because it doesn't depend on inspiration." },
        ],
      },
      footer: "Same hours. Same effort. Different system. Different outcome.",
    },
    {
      type: "principle",
      num: "01",
      title: "The Five Traps — why most small businesses fail at social media",
      intro: "These aren't problems with social media. They're problems with how it's used. Each trap is reversible — and recognising which ones you're in is half the fix.",
      sectionTitle: "The Traps",
      sections: [
        { heading: "1. No clear customer", example: "\"I sell to anyone who needs cakes.\"", note: "Trying to talk to everyone, talking to nobody. Specificity in target = specificity in voice = specificity in conversion." },
        { heading: "2. No consistent voice", example: "Monday: corporate \"We are pleased to announce…\" Wednesday: chatty \"Y'all the new flavours dropped 🔥\"", note: "Random tone confuses the audience and weakens trust. Followers can't tell if you're the same brand week to week." },
        { heading: "3. Inconsistent posting", example: "Five posts on Monday. Nothing for 18 days. Three posts. Silence.", note: "Bursts of activity, weeks of silence — the algorithm punishes both extremes. Steady cadence beats heroic effort." },
        { heading: "4. All sell, no value", example: "Every post asks for the sale: \"Order now.\" \"Buy this.\" \"DM us.\"", note: "Followers leave because the page only shows up when it wants their money. The 80/20 rule reverses this." },
        { heading: "5. No measurement", example: "Posts go up. Engagement happens. Or doesn't. Nobody checks.", note: "Without data, no idea what to repeat or change. Six months in, the same mistakes are still being made." },
      ],
      rule: "Every business in this room is in at least 2 of these. By Day 9, you'll be out of all 5.",
    },
    {
      type: "exercise",
      title: "Exercise 1 of 2 — Reverse-engineer a brand you love (10 min)",
      intro: "Pick one Sierra Leonean business you actually follow on social media — not one you think you should follow. The brand you stop scrolling for, not the one your aunt told you about.",
      items: [
        { num: "1", copy: "Open their page on your phone. Spend 90 seconds scrolling.", answer: "If you can't name the brand by feel within those 90 seconds, you've picked the wrong one. Pick the one you can recognise from a single post." },
        { num: "2", copy: "Write down 3 specific things their content does that makes you stop scrolling.", answer: "Be concrete. \"They're nice\" doesn't count. \"Their hooks are always a question\" or \"Their photos all use the same warm filter\" do." },
        { num: "3", copy: "Match each to one of the Four Pillars (Strategy, Content, Engagement, Measurement).", answer: "If you can't tell which pillar, that's data — it means the work is so integrated you can't see the seams. That's what good marketing looks like." },
        { num: "4", copy: "Pair-share your findings with the person beside you.", answer: "You'll spot 3 things in their brand they didn't see — and they'll spot 3 in yours. Free consultancy you'll never get cheaper." },
      ],
    },
    {
      type: "principle",
      num: "02",
      title: "Goal Setting — vague goals produce vague results",
      intro: "\"Grow my Instagram\" is not a goal. It's a wish. SMART turns it into something you can actually pursue and measure.",
      sectionTitle: "The 5 Letters",
      sections: [
        { heading: "S — Specific", example: "Which platform? Which outcome?", note: "\"Grow Instagram\" → \"Grow Instagram DMs from prospective customers.\"" },
        { heading: "M — Measurable", example: "A number, not a feeling.", note: "\"More enquiries\" → \"50 enquiries.\" Without a number, you can't tell on Day 30 if you won." },
        { heading: "A — Achievable", example: "Stretching, not impossible.", note: "If you got 8 enquiries last month, 50 in the next 30 days is stretch. 5,000 is fantasy." },
        { heading: "R — Relevant", example: "Tied to a business outcome you actually need.", note: "Followers don't pay rent. Enquiries do. Sales do. Anchor the goal to revenue, not vanity." },
        { heading: "T — Time-bound", example: "By a specific date.", note: "\"Soon\" is not a date. \"By 30 June 2026\" is. The deadline is what makes you start today." },
      ],
      rule: "Example: \"Get 50 product enquiries from Instagram DMs by 30 June 2026.\" That's a goal. Anything less specific is a wish.",
    },
    {
      type: "exercise",
      title: "Exercise 2 of 2 — Make your goal SMART (15 min)",
      intro: "By the end of this exercise, your goal for this programme is one specific sentence on paper.",
      items: [
        { num: "1", copy: "Write your current goal as you'd say it to a friend, in plain language.", answer: "Don't try to make it sound smart yet. Just write what you actually want." },
        { num: "2", copy: "Add Specific: which platform, which business outcome.", answer: "Pick ONE platform for this goal. \"All platforms\" diffuses energy. You can have a separate goal per platform later." },
        { num: "3", copy: "Add Measurable: a number, not a feeling.", answer: "Anchor the number to your current baseline. If you got 8 last month, aim for 25-50 — not 5 (too small) or 500 (fantasy)." },
        { num: "4", copy: "Add Time-bound: by what date.", answer: "30 days from today is the typical horizon for a SMART goal in this programme. Long enough to act, short enough to stay urgent." },
      ],
    },
    {
      type: "takeaways",
      title: "Workshop — Audit your current presence (45 min)",
      items: [
        "Using the 12-question checklist, audit your Facebook, Instagram, and WhatsApp Business profiles in real time",
        "A clear picture of where your business stands today, in writing",
        "Your top 3 strengths to keep building on",
        "Your top 3 weaknesses to fix in the next 8 days",
        "One SMART goal for the end of this programme — written, dated, and read aloud once",
      ],
      next: "The audit is the baseline. Day 9's measurement is what proves the gain.",
    },
    {
      type: "table",
      title: "The 12-Question Audit Checklist",
      subtitle: "Tick Yes or No for each. Aim for 12 Yeses by Day 9. Today, just record the truth.",
      columns: ["#", "Question", "Today: Y / N"],
      rows: [
        ["1", "Profile picture is recognisable at thumbnail size", "Y / N"],
        ["2", "Bio explains what you do and who you serve in one line", "Y / N"],
        ["3", "Contact details (phone, WhatsApp, email) are visible", "Y / N"],
        ["4", "Location or service area is stated", "Y / N"],
        ["5", "Pinned post is current and represents the brand", "Y / N"],
        ["6", "Last post was within the past 7 days", "Y / N"],
        ["7", "Visual style is consistent across the last 9 posts", "Y / N"],
        ["8", "Voice is consistent across captions", "Y / N"],
        ["9", "DMs are answered within 24 hours", "Y / N"],
        ["10", "There's at least one social proof post (review/testimonial)", "Y / N"],
        ["11", "There's a clear call-to-action somewhere on the page", "Y / N"],
        ["12", "Page is set up as a business profile (not personal)", "Y / N"],
      ],
      footer: "Score / 12 today. Score again on Day 9. The delta is your evidence.",
    },
    {
      type: "takeaways",
      title: "Homework before Day 2",
      items: [
        "Tonight: finish your audit and your SMART goal at home",
        "Refine your goal — read it aloud to one trusted person and tighten it",
        "Bring your business name, logo, and 5 product photos to Day 2",
        "Join the cohort WhatsApp group if you haven't yet",
        "Tomorrow: brand identity & positioning — voice, customer profile, one-sentence positioning statement",
      ],
      next: "Day 2 builds the document every post for the next year sits on top of.",
    },
    {
      type: "takeaways",
      title: "Day 1 — Closing Takeaway",
      items: [
        "You can't fix what you haven't named. Today you named where you stand. Tomorrow we build the foundation everything else sits on.",
      ],
      next: "Regium Touch × Aurora Foundation  ·  See you Day 2",
    },
  ],
};
