// Social Media Marketing — Day 9: Capstone & Graduation
export const smmDay9Module = {
  id: "smm09",
  title: "Day 9 — Capstone & Graduation",
  type: "Rich Module",
  duration: "5h",
  desc: "Your day. Present what you’ve built, hear what your peers built, and take your next step. Eight days of work synthesised into a 10-minute presentation, a structured peer-feedback loop, and a personal 30-day plan you commit to in writing.",
  topics: ["The Nine-Day Synthesis", "10-Minute Presentation Structure", "Peer Feedback Loop", "Post-Programme 30-Day Plan", "First-30-Days Pitfalls", "The Written Commitment"],
  quiz: [
    { q: "Adama opens her capstone: \"I started Adama Designs in 2019 after my second child was born...\" Room glazes over by minute 2. Pitching frameworks (and Day 2 customer-first positioning) say lead with the customer, not company history — because the audience evaluates whether YOUR customer matches THEIR customer. The marketing error is:", opts: ["Skip the introduction entirely", "She opened with company history instead of the customer profile. Investors, clients, and partners all evaluate businesses through the same lens: \"Whose problem do you solve, specifically?\" Customer-first openings (\"Adama is 32, two children, wants jewellery for office that doesn't feel like office\") signal positioning clarity in 15 seconds; founding stories signal she hasn't decided who the customer is. Same content, opposite first impression", "Show the logo first", "Read off slides"], correct: 1 },
    { q: "Mariama gives Fatou peer feedback: \"Honestly, the whole thing was great, you're doing amazing!\" Vague positive feedback has near-zero ROI for the recipient. The Day 9 structure (one strength, one question, one challenge) maximises signal density. The marketing principle behind structured feedback is:", opts: ["List every weakness", "Specific feedback is the same discipline as specific marketing copy: \"the way you described Adama, I could picture her exactly\" beats \"great customer profile\" because specificity creates actionable signal. Vague praise is the audit-day version of vanity metrics — feels good, changes nothing. Structured feedback (working/question/challenge) gives Fatou three concrete things to act on, which is what feedback exists to produce", "Stay silent", "Only mention bad"], correct: 1 },
    { q: "Hawa's 30-day commitment: \"I will post more often, engage with my audience, and grow my business.\" SMART-goal failure on every dimension. A goal without a number can't be measured; without a deadline can't be enforced; without an outcome can't attribute success. The structural fix is:", opts: ["Make it longer", "Specific outcome + number + deadline + protected time blocks + stuck-point protocol. Example: \"By 22 May 2026, I will have published 20 posts and earned my first 10 paying customers from Instagram. Sundays I batch; Fridays I review. When I get stuck, I post in the alumni group within 48 hours.\" Vague commitments don't survive Week 2 because they have no failure-detection mechanism — you can't tell whether you're on or off track. Numbers + dates are the goal-setting equivalent of attribution: without them, no improvement loop exists", "Mention competitors", "Commit to 90 days"], correct: 1 },
    { q: "Second Monday post-graduation. Isatu's data: 4 posts published of planned 7 (week 1), 1 of planned 7 (week 2). She's scrolling and watching @bigaccountSL hit 50K followers, about to skip today. Comparing to a benchmark she's not targeting (different audience, different segment, different stage) is a positioning error. The fix is:", opts: ["The comparison spiral compounded by the Monday slump and the start of calendar abandonment. Protocol: post in the alumni WhatsApp group within 48 hours (visibility prevents drift), return to the Sunday batch session (system over mood), and re-anchor on her customer profile — Adama doesn't care about @bigaccountSL's follower count. Comparing yourself to the wrong segment produces the wrong strategic decisions; consistency to your own customer is what compounds", "Take 2-week break", "Switch platforms", "Buy followers"], correct: 0 },
    { q: "Mariama is presenting. Minute 6, only on section 2 of 6. Trainer signals 4 min left. The capstone's job is to land decision-relevant content, not recite every section equally. The disciplined adjustment — same logic as a campaign with limited budget — is:", opts: ["Speed-read through everything to fit", "Skip to section 5 (30-day plan) and section 6 (the ad), naming the cut: \"I'm going to jump to my 30-day plan to respect the time.\" Triage by audience-value: the future-facing content (plan + ad) is what the room can act on; foundational sections she already covered implicitly. Ending on time signals self-awareness and respect — both of which are positioning signals to the audience watching her business sense, not just her presentation", "Stop and sit down", "Run over and steal the next person's time"], correct: 1 },
    { q: "3 weeks post-graduation. Aminata has been editing one Reel for 5 days. \"Almost ready.\" Marketing iteration math: imperfect content shipped + measured produces a feedback loop; perfect content never shipped produces nothing. The cure is:", opts: ["Monday slump", "Calendar abandonment — skip the Reel", "Done > perfect. Ship version 1 today, measure (reach, retention, DMs), refine version 2 next week using actual audience signal — not her own anxiety. Endless polishing is the opposite of marketing optimisation: optimisation requires data, data requires shipping. The 5 days of solo editing produced zero learning; one published version produces the only signal that matters — what real customers respond to", "Stay silent in alumni group"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 9", title: "Capstone", titleAccent: "& Graduation", subtitle: "Your day. Present what you’ve built, hear what your peers built, and take your next step.", meta: "Regium Touch × Aurora Foundation  |  Day 9  |  7 Slides" },
    { type: "stats", eyebrow: "THE NINE-DAY JOURNEY", title: "Look at what you built", intro: "Nine days ago, ‘social media’ was a vague pressure. Today, it’s a system you can run. Foundations, brand, strategy, visuals, words, platforms, ads, analytics — every layer in place.", stats: [
      { num: "10 min", label: "your capstone presentation — six sections, one business, your voice" },
      { num: "30 days", label: "the post-programme plan you’ll sign in writing today and pin where you’ll see it daily" },
      { num: "25", label: "women who showed up, did the work, and built something real over nine days" },
    ], subheading: "What Today Actually Is", bullets: [
      "Synthesise 8 days of learning into a coherent 10-minute business case",
      "Show — not tell — using real photos, real captions, the real 30-day calendar, and the real ad draft",
      "Give and receive peer feedback in a structured, specific format that actually helps",
      "Sign a personal 30-day commitment with date, outcome, protected time, and a stuck-point protocol",
      "Walk into the alumni WhatsApp group on Monday morning, not alone",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF GRADUATION DAY", title: "What today is built around", subtitle: "Today is a synthesis day, not a teaching day. Four moves in sequence — each one harder to do without the day before.", items: [
      { num: "01", title: "Synthesis", desc: "Eight days of work pulled into one coherent narrative — business + customer, brand, strategy, content, plan, ad. The whole journey on one page, in one voice.", icon: "\u{1F9E9}" },
      { num: "02", title: "Presentation", desc: "10 minutes, six sections, your business in your words. You’re not pitching strangers — you’re catching up with friends who watched you build this.", icon: "\u{1F399}️" },
      { num: "03", title: "Peer Feedback", desc: "After every presentation: one thing working, one question, one challenge. Specific. Structured. Kind. The format that turns peers into a board of advisors.", icon: "\u{1F4AC}" },
      { num: "04", title: "30-Day Commitment", desc: "Written, dated, signed. Specific outcome by 22 June 2026. Protected weekly time. A stuck-point protocol. Pinned where you’ll see it every morning.", icon: "✍️" },
    ], footer: "Rule: today is not the end. Today is the start of the part where it actually matters." },
    { type: "principle", num: "01", title: "Don’t Read Slides. Tell Us What You Built and What You’ll Do With It.", intro: "The trainees who land their capstone aren’t the most polished — they’re the most specific. They open with the customer, not the company. They show, not tell. They name what surprised them and what they’re still stuck on. They end with the next 30 days. Here’s the structure that does the work for you.", sectionTitle: "The 4 Moves That Make a 10-Minute Capstone Land", sections: [
      { heading: "1. Open with the customer, not company history", example: "Bad: ‘I started this business in 2019…’  Good: ‘Adama is 32. Two children. Office worker. Wants jewellery that feels like her, not like the office.’", note: "The room leans in when they recognise a real human. Founding stories belong in slide 6, not slide 1." },
      { heading: "2. Show, don’t tell — open the actual files", example: "Open the Canva file. The 30-day calendar. The ad draft. The captions. Not screenshots — the real thing.", note: "Real artefacts prove you did the work. Polished slides describing the work prove only that you have a slide template." },
      { heading: "3. Name what surprised you and where you’re stuck", example: "‘I learned my customer wasn’t who I thought she was.’ ‘I still don’t know how to read TikTok analytics — can the room help?’", note: "Vulnerability + specificity = trust. Asking the room turns peers into advisors. The stuck-point question is often the most useful 30 seconds of the whole presentation." },
      { heading: "4. End with the next 30 days, not a thank-you", example: "‘Mondays I batch. Fridays I review. By 22 June 2026 I will have published 20 posts and earned my first 10 Instagram customers.’", note: "The last words are the ones the room remembers. Specific actions + specific date + specific outcome. Make it impossible to forget." },
    ], rule: "You’re not pitching a stranger. You’re catching up with friends who watched you build this. Time yourself once at home tonight — that’s the difference between calm and chaos in the morning." },
    { type: "comparison", eyebrow: "THE FIRST 30 DAYS — TWO PATHS", title: "Same graduate. Same skills. Different month one.", subtitle: "The work doesn’t stop today. The pitfalls in column one sabotage Week 2 onwards. The protocols in column two are how graduates actually compound.", left: { title: "The Pitfall Path (Most Graduates)", color: "#EF4444", items: [
      { strong: "The Monday slump — first Monday alone, all the energy drops", note: "No cohort, no trainer, no one watching. Skipping one day becomes skipping one week becomes giving up by Week 3." },
      { strong: "Calendar abandonment — ‘I’ll post when inspired’", note: "Inspiration is unreliable. The 30-day calendar from Day 3 was the entire point — the moment you abandon it, you’re back to vague pressure." },
      { strong: "Comparison spiral — watching @bigaccountSL hit 50K", note: "Their numbers are not your numbers. Your goal is your customer, not a stranger’s follower count. Spiral kills consistency faster than failure does." },
      { strong: "Tweaking forever and going silent on the group", note: "Endlessly perfecting before posting + disappearing from the alumni WhatsApp = the slow exit. Done is better than perfect; visible is better than gone." },
    ] }, right: { title: "The Compound Path (Real Graduates)", color: "#10B981", items: [
      { strong: "Sunday batch session protected on the calendar", note: "Two hours every Sunday afternoon. Captions written, photos staged, posts scheduled. Monday energy doesn’t matter when Sunday already shipped the week." },
      { strong: "Friday 5-minute review every week without fail", note: "Open insights. Answer the four prompts. Note what to repeat next week. Tiny ritual, compounding return — the graduates who do this for 12 weeks have a content playbook." },
      { strong: "Goal is the customer, not the stranger’s follower count", note: "When the comparison spiral hits, return to your customer profile from Day 2. Adama doesn’t care that someone else has 50K followers. She cares that you serve her well." },
      { strong: "Done > perfect. Stuck-point posted in the group within 48 hours", note: "Imperfect content that ships beats perfect content that never does. And the alumni group is where you stay accountable — silence is the slow exit; asking is the fast lane." },
    ] }, footer: "Rule: most graduates know what to do. The challenge is doing it consistently. Pick your column today, in writing, with a date." },
    { type: "table", title: "The 6-Section Capstone Structure", subtitle: "10 minutes. Six sections. Your business. Time it once tonight at home — phone timer running, out loud.", columns: ["Section", "Time", "What to Show / Source"], rows: [
      ["1. Business + customer", "60 sec", "Who you serve, what you sell, why now. Open with the customer (Day 2)."],
      ["2. Brand identity", "60 sec", "Voice, values, visual style. Show one real example (Day 2)."],
      ["3. Content strategy", "2 min", "Pillars, 80/20 ratio, the actual 30-day calendar (Day 3)."],
      ["4. Sample content", "3 min", "Show 2 real posts. Walk through hook, body, CTA (Days 4–5)."],
      ["5. 30-day plan", "2 min", "What you’ll do every week for the next month. Specific actions (tonight’s homework)."],
      ["6. Your one ad", "1 min", "The first paid ad you’ll run, and why (Day 7)."],
    ], footer: "Rule: if you go over, the next person loses time. End on time — that’s the only inviolable rule of today." },
    { type: "exercise", title: "Sign Your 30-Day Commitment", intro: "Your final assignment isn’t a tactical task — it’s the commitment that keeps every tactic alive after today. Fill this in tonight. Sign it. Take a photo. Pin it where you’ll see it daily. The graduates who write this down and look at it weekly are the ones still posting in 90 days.", items: [
      { num: "1", copy: "Write the opening line: ‘I am [your name], founder of [business name].’ Then the outcome line: ‘By 22 June 2026, I will have ___.’ Fill in a SPECIFIC outcome — a number, an action, a milestone (‘published 20 posts and earned my first 10 paying customers from Instagram’).", answer: "Vague commitments don’t survive Week 2. ‘I will post more’ is a wish. ‘By 22 June 2026, I will have published 20 posts and earned my first 10 paying customers from Instagram’ is a contract with yourself. Numbers + dates make it real. Wishes don’t make it past the first Monday alone." },
      { num: "2", copy: "Protect two weekly time blocks in writing: ‘Every Sunday afternoon for batching. Every Friday afternoon for the 5-minute review.’ Add them to your phone calendar as recurring events with reminders 30 minutes before.", answer: "The Sunday batch is what makes Monday irrelevant — your week ships before the slump arrives. The Friday review is what makes the next week smarter than the last. Two non-negotiable blocks. Everything else flexes around them. Without protected time, you’ll find an excuse by Week 2." },
      { num: "3", copy: "Write the stuck-point protocol: ‘When I get stuck, I will post in the alumni WhatsApp group within 48 hours.’ Save the group as a pinned chat. Set a personal rule: silence longer than a week = a check-in DM to your accountability partner.", answer: "Going silent is the slow exit. Most graduates who quit don’t announce it — they just stop showing up in the group. The 48-hour rule prevents that drift. Asking out loud is what turns a stuck point into the next breakthrough. The alumni group only works if you actually use it." },
      { num: "4", copy: "Sign and date it. Take a photo on your phone. Set the photo as your phone wallpaper OR pin it on the wall above where you work. Read it once every Monday morning before opening Instagram.", answer: "Visible commitments outperform invisible ones by every measure ever studied. Your phone wallpaper is the surface you see 80+ times a day. Your wall is the surface you see at the start of every work session. Either way: the commitment lives where the temptation to skip lives. Today is not the end — today is the start of the part where it actually matters." },
    ] },
  ],
};
