// Social Media Marketing — Day 7: Paid Advertising Basics
export const smmDay7Module = {
  id: "smm07",
  title: "Day 7 — Paid Advertising Basics",
  type: "Rich Module",
  duration: "5h",
  desc: "Start small. Learn fast. Scale only what works. The Meta Ads framework that lets a Sierra Leonean small business run profitable campaigns on NLe 50 a day — and never click “Boost” on impulse again.",
  topics: ["Meta Business Suite & Ads Manager", "Audience Targeting", "Ad Anatomy & Creative", "Daily Budget Ladder", "The 5 Budget Killers", "Boost vs. Real Campaigns"],
  quiz: [
    { q: "Aminata's Aberdeen jewellery shop. AOV: NLe 600. Margin: 40% (NLe 240/sale). She has NLe 1,500 for her first Meta campaign. Two options: (a) Boost a viral post for NLe 1,500 over a weekend — historical CPA on Boost ~NLe 200 (target Awareness), expected DMs that close: 1-2; (b) Ads Manager NLe 50/day × 30 days, Messages objective, saved audience — expected CPA NLe 80, expected sales: 7-9. Which is the disciplined allocation?", opts: ["Option (b). 30-day Ads Manager run. 7-9 sales × NLe 240 = NLe 1,680-2,160 gross margin = positive ROAS; the Boost equivalent loses money. Small + long lets the algorithm exit the learning phase (3-4 days) before optimisation begins. The math says Boost is a money-losing channel for direct response; Ads Manager is the only structure where the unit economics work", "Boost — post already works organically", "Split NLe 750/NLe 750", "All NLe 1,500 in one day"], correct: 0 },
    { q: "Fatou launched her first Ads Manager campaign Monday morning. Tuesday night: CPA NLe 180 (target NLe 80), spend NLe 100, panicking. Meta's algorithm typically needs 3-4 days and ~50 conversion events to exit the learning phase. Killing the campaign now means:", opts: ["Switch off — data is conclusive", "Double the budget to force results", "Hold. Day 2 data is statistically meaningless — the learning phase hasn't finished; CPA at this stage is noise, not signal. The average small business burns ~$500 by killing campaigns mid-learning and rebuilding repeatedly. Marketing-math discipline: never make optimisation decisions on under-50 conversions or under-3-day windows", "Narrow audience to under 10K"], correct: 2 },
    { q: "A trainee's Meta audience: \"All of Sierra Leone, 18–65, interested in business.\" Audience size: 1.8M. Her budget: NLe 50/day. With 1.8M audience, daily reach exhaustion takes ~280+ days, meaning impressions get sprayed across non-buyers. Audience-narrowing is segmentation. The biggest problem is:", opts: ["\"Business\" is too narrow", "Too broad on every dimension. With NLe 50/day across 1.8M people, the algorithm has no concentrated signal to optimise against — CPA stays high indefinitely. Tighten to specific cities, women 28-42, and 3-5 specific interests = 50K-500K sweet spot. At that size, ~NLe 1,500/month creates enough frequency for the algorithm to find buyers within the audience. Targeting precision = budget efficiency", "Add 15 more interests", "Age up to 75"], correct: 1 },
    { q: "Isatu drafts an ad: beautiful photo, 3 paragraphs of features, 2 CTAs: \"Message us OR visit our shop in Lumley.\" Two CTAs split click attribution AND confuse Meta's optimisation algorithm about which action to measure success on. Marketing math: 1 CTA at 4% CTR > 2 CTAs at 1.5% each. The fix is:", opts: ["Looks great — publish", "Add a third for options", "Pick one CTA. Message OR Visit, never both — Meta optimises against the chosen objective; conflicting asks tell the algorithm conflicting success signals, which slows learning and inflates CPA. Single CTA = clean attribution + faster algorithm convergence + higher conversion rate per impression. The dual-CTA tax shows up directly in ROAS", "Remove the photo"], correct: 2 },
    { q: "A graduate debating Boost vs Ads Manager for WhatsApp enquiries. Boost objective default: Engagement (likes). Ads Manager Messages objective: optimises for cost-per-conversation. Same NLe 50/day, same audience, same creative. Real-world data from West African small-business cohorts: Ads Manager Messages produces 4-6x more DMs per Leone vs Boost. The actual marketing difference is:", opts: ["Boost is cheaper per click", "Objective selection is the entire ROAS lever. Boost optimises for vanity (likes from non-buyers); Ads Manager Messages tells Meta to find people likely to start a WhatsApp conversation — the action that actually generates revenue. Same money, different objective, 4-6x revenue gap. Convenience (Boost) vs attribution-aligned conversion (Ads Manager)", "Ads Manager only for NLe 200+/day", "No real difference"], correct: 1 },
    { q: "Mariama: NLe 30/day for 7 days. Reach: 14,000. Frequency: 3.2. Link clicks: 180. DMs: 0. Ad spend: NLe 210, revenue: NLe 0. Reach is fine — conversion is dead. The 5 Budget Killers diagnostic is the right framework. Where does the data point first?", opts: ["Increase to NLe 100/day — reach proves it works", "Expand audience to all of SL", "Walk the 5 Killers in order: (1) objective wrong? (2) audience too broad? (3) creative weak? (4) tracking broken? (5) killed too early? Reach without DMs almost always = wrong objective (Awareness when she needed Messages) OR a hook/CTA that doesn't drive the action. Never increase budget on a campaign that hasn't converted — you're paying for the same broken funnel at higher volume. Diagnose conversion before scaling spend", "Switch platforms"], correct: 2 },
  ],
  slides: [
    { type: "cover", module: "DAY 7", title: "Paid Advertising", titleAccent: "Basics", subtitle: "Start small. Learn fast. Scale only what works. Today: zero live spend.", meta: "Regium Touch × Aurora Foundation  |  Day 7  |  7 Slides" },
    { type: "stats", eyebrow: "WHY ADS BURN MONEY", title: "More small businesses lose money on ads than make it", intro: "That’s not because ads don’t work. It’s because most people skip the work that makes ads work — and click ‘Boost’ on impulse. Today, we fix that before a single Leone is spent.", stats: [
      { num: "70%", label: "of small business ad budgets fail to break even" },
      { num: "$500", label: "average burned before the first profitable campaign" },
      { num: "3–4 days", label: "minimum the Meta algorithm needs to learn before any judgement is fair" },
    ], subheading: "What Day 7 Gives You Before Any Spend Goes Live", bullets: [
      "Meta Business Suite + Ads Manager set up safely — not the Boost button",
      "One saved audience matching your real customer (location, demographics, 3–5 interests)",
      "One drafted ad — image, copy, social proof, single CTA — ready for trainer review",
      "A daily budget you can sustain for at least 7 days without panic",
      "The 5 Budget Killers checklist memorised — the impulse ‘Boost’ click ends today",
    ] },
    { type: "grid", eyebrow: "THE 4 PILLARS OF DAY 7", title: "What every paid campaign needs before it goes live", subtitle: "Miss any of these and the algorithm wastes your money. All four sit underneath every profitable Meta ad.", items: [
      { num: "01", title: "Right Tool, Right Setup", desc: "Meta Business Suite + Ads Manager — not Boost. Proper objective (Messages, Sales, Leads), proper account, no impulse clicks from the post itself.", icon: "\u{1F6E0}️" },
      { num: "02", title: "Tight Audience", desc: "50,000–500,000 in target. Specific cities, narrower age, 3–5 interests. ‘Everyone in Sierra Leone’ is the fastest way to burn NLe 50 on people who will never buy.", icon: "\u{1F3AF}" },
      { num: "03", title: "Ad Anatomy", desc: "Hook in 3 seconds, value statement, one piece of social proof, single CTA. Boosting a bad post is just paying for a bad post to reach more people.", icon: "\u{1F9F1}" },
      { num: "04", title: "Patient Budget", desc: "NLe 30–100/day for 14–30 days. Never under 7 days. Small + long beats big + weekend every single time.", icon: "⏳" },
    ], footer: "Rule: these aren’t optional polish. Skip one and the other three get cancelled out by the gap." },
    { type: "principle", num: "01", title: "Boost = Burn. Ads Manager = Earn.", intro: "The single most expensive habit in small-business marketing is clicking ‘Boost’ on a post that did well organically. It feels like the algorithm rewarding you. It’s actually you paying Meta to show your post to a worse audience for a worse outcome. Here’s why — and how to avoid every Boost trap.", sectionTitle: "The 4 Reasons Ads Manager Always Wins", sections: [
      { heading: "1. The objective is the whole game", example: "Boost defaults to engagement (likes). Ads Manager lets you pick Messages, Sales, Traffic, or Leads.", note: "The objective tells the algorithm who to find. Pick ‘Awareness’ when you need ‘Messages’ and you’ll get likes from people who will never buy." },
      { heading: "2. Targeting depth", example: "Boost: gender, age, broad interests. Ads Manager: specific cities, custom audiences, lookalikes, layered interests.", note: "Aim for 50,000–500,000 in target. Bigger = wasted impressions. Smaller = audience exhaustion in 4 days." },
      { heading: "3. A/B testing actually exists", example: "In Ads Manager you can run two creatives side-by-side, two audiences, two hooks — and let the data pick. Boost gives you no testing at all.", note: "Without A/B you’re guessing. With it, every NLe 50 spent teaches you which photo, hook, or audience earns enquiries." },
      { heading: "4. The metric that matters", example: "Boost optimises for cheap engagement. Ads Manager optimises for the action that pays — a DM, a sale, a form fill.", note: "A boosted post with 200 likes and zero enquiries is a loss. An Ads Manager campaign with 30 likes and 12 DMs is a win. Choose accordingly." },
    ], rule: "If you cannot answer ‘What’s the objective? Who’s the audience? What’s the budget for how many days?’ in 30 seconds — do not boost. Either run a real campaign or save the money." },
    { type: "comparison", eyebrow: "BOOST POST vs ADS MANAGER", title: "Two buttons. Very different outcomes.", subtitle: "‘Boost’ is convenient. Ads Manager is where money actually works. Same NLe 50, opposite results.", left: { title: "Boost Post (Convenient. Wasteful.)", color: "#EF4444", items: [
      { strong: "One-click on a post — no proper campaign setup", note: "No objective choice. Meta defaults to engagement, which means likes from people with zero buying intent." },
      { strong: "Limited audience targeting — broad gender + age only", note: "You can’t pick specific cities, layer interests, or save for reuse. Spend leaks to people 600 km from your shop." },
      { strong: "No A/B testing of creative, copy, or audience", note: "You can never know which photo or hook actually earned the enquiry. Every NLe 50 buys you guesses, not data." },
      { strong: "Optimises for likes, not enquiries", note: "Vanity metric goes up. WhatsApp stays silent. You feel busy without earning a Leone." },
    ] }, right: { title: "Ads Manager (Slower. Works.)", color: "#10B981", items: [
      { strong: "Proper campaign setup with chosen objective", note: "Pick ‘Messages’ if DMs pay you, ‘Sales’ if e-commerce pays you. The objective decides who Meta finds." },
      { strong: "Detailed targeting: location, age, language, layered interests", note: "Saved audience built once, reused forever. Aim for 50K–500K — the sweet spot between broad and exhausted." },
      { strong: "A/B test creatives, audiences, and copy", note: "Run two hooks against each other on NLe 30/day each. After 7 days you know which one to scale." },
      { strong: "Optimises for the action that actually pays", note: "Cost-per-message, cost-per-lead, cost-per-sale. Real numbers tied to real revenue. Decisions stop being feelings." },
    ] }, footer: "Rule: convenience is the price of bad decisions. Always use Ads Manager — even if it takes 20 minutes longer the first time." },
    { type: "table", title: "The Budget Ladder — How Small Can Actually Work", subtitle: "Smaller daily budgets running for longer beat large weekend bursts every time. Here’s the ladder — do not skip rungs.", columns: ["Daily Budget", "Run Length", "What This Spend Is For"], rows: [
      ["NLe 30 / day", "30 days", "Testing your first ad. You’re learning the platform, not chasing sales."],
      ["NLe 50 / day", "30 days", "First real campaign. Enough volume for the algorithm to actually learn."],
      ["NLe 100 / day", "14 days", "Established product, proven creative. Time to push for scale."],
      ["NLe 200+ / day", "varies", "Only after your first 3 profitable campaigns. Not before. Ever."],
      ["Anything", "<7 days", "Wrong. The algorithm hasn’t finished learning. You’re killing it before it could perform."],
    ], footer: "Rule: never run an ad for less than 7 days. NLe 50 × 30 days teaches you more than NLe 1,500 in one weekend." },
    { type: "exercise", title: "Build Your Saved Audience + Pass the Boost-or-Don’t Test", intro: "Two assignments tonight. First: build the saved audience you’ll reuse for every future ad. Second: pass the 30-second test before you ever click ‘Boost’ again.", items: [
      { num: "1", copy: "Open Ads Manager → Audiences → Create Saved Audience. Set location to ONLY the specific cities or districts where your customers actually are (Freetown, Aberdeen, Lumley — not ‘All of Sierra Leone’).", answer: "Specificity is the whole game. ‘All of Sierra Leone’ is 8M+ people, most of whom will never see your shop. ‘Freetown + Aberdeen + Lumley’ keeps every Leone you spend in front of someone who could actually walk in or order." },
      { num: "2", copy: "Set demographics narrower than feels comfortable: women 28–42, not adults 18–65. Add 3–5 specific interests pulled from your Day 2 customer profile — not 30 vague ones.", answer: "Your aim is 50,000–500,000 estimated audience. Smaller than 50K = exhaustion in days. Larger than 500K = spend sprayed on strangers. Save it with a clear name (e.g. ‘Freetown women 28–42 fashion’) and screenshot the size." },
      { num: "3", copy: "Pick one recent organic post you considered boosting. Out loud, run it through the 5 Budget Killers checklist: wrong objective, audience too broad, weak creative, no tracking, stopping early. Score it honestly.", answer: "Most posts fail at least 2 of the 5. That’s not a tragedy — it’s data. Either rebuild the post into a proper Ads Manager campaign with a real objective, or accept that boosting it would have been NLe 500 set on fire." },
      { num: "4", copy: "30-second test before ever clicking ‘Boost’ again: answer in one breath — What’s the objective? Who’s the audience? What’s the budget for how many days? If you cannot answer all three confidently, do not boost.", answer: "From now on this is non-negotiable. Either you have a real campaign with answers to all three questions, or you save the money. The Boost button is no longer an impulse — it’s a decision tree with three required gates." },
    ] },
  ],
};
