// Storytelling for Conversion - Module 4 for Copywriting
// Narrative structures that turn a flat pitch into an irresistible read

export const storytellingModule = {
  id: "stry01",
  title: "Storytelling for Conversion",
  type: "Rich Module",
  duration: "90 min",
  desc: "How narrative structure turns a flat product pitch into something the reader cannot stop reading \u2014 and why AI-generated stories consistently feel hollow.",
  topics: ["Before-After-Bridge", "Hero's Journey (simplified)", "Star-Story-Solution", "Sensory Detail", "Tension & Stakes", "Where to Deploy Stories"],
  quiz: [
    { q: "You draft a customer story: \"Our customer improved their efficiency and saw great results.\" Apply the audit \u2014 how many story elements does it pass?", opts: ["All 6 elements", "Zero \u2014 no named hero, no concrete stakes, no tension, no turning point, no surprising detail, no specific outcome", "2 of 6", "4 of 6"], correct: 1 },
    { q: "Run the Before-After-Bridge test on: \"Your CRM wastes 11 hrs/wk. After: your pipeline updates itself. Bridge: our solution.\" What\u2019s the weakest section and why?", opts: ["Before", "Bridge \u2014 \u201Cour solution\u201D is vague; the Bridge must name the specific mechanism (integrations, time-to-setup, what\u2019s removed)", "After", "All are strong"], correct: 1 },
    { q: "Which sentence signals authenticity most powerfully via sensory / time-place detail?", opts: ['"The team faced various challenges"', '"At 11:47pm on a Thursday, the CTO finally Slacked the 3,400-word message"', '"They worked through issues together"', '"Things improved over time"'], correct: 1 },
    { q: "A brand insists every case study sentence must be \"positive and polished.\" Predict the believability cost:", opts: ["None \u2014 polish increases trust", "Polished-only stories read as marketing; the absence of embarrassing or off-brand detail removes the trust fingerprint \u2014 vulnerability is what makes the rest credible", "Readers always prefer polished", "Depends on the platform"], correct: 1 },
    { q: "Your landing page has a beautifully written customer story, but it\u2019s buried under the nav on a separate Case Studies page. How does this hurt conversion?", opts: ["It doesn\u2019t", "Stories work hardest next to the commitment moment \u2014 the price, CTA, or signup. Buried stories don\u2019t move buyers at the decision point", "Story location is irrelevant", "Should always be in the footer"], correct: 1 },
    { q: "The sharpest difference between a story and a case study is:", opts: ["Length", "Stories centre on a named human character with stakes and tension; case studies typically lead with methodology and metrics \u2014 different emotional architecture", "Stories are fictional", "No meaningful difference"], correct: 1 },
  ],
  slides: [
    {
      type: "cover",
      module: "MODULE 4",
      title: "Storytelling",
      titleAccent: "for Conversion",
      subtitle: "Narrative structure is the single biggest lever in long-form copy \u2014 and the easiest place to tell human-written work apart from AI.",
      meta: "Advanced Copywriting Training  |  Module 4 of 6  |  10 Slides",
    },
    {
      type: "stats",
      eyebrow: "WHY STORIES CONVERT",
      title: "The brain is wired for narrative, not feature lists",
      intro: "Stories light up motor, sensory, and emotional circuits in the reader's brain simultaneously. Feature lists light up only the language-processing regions. That difference compounds at scale.",
      stats: [
        { num: "22\u00D7", label: "more memorable than facts presented alone (Stanford)" },
        { num: "2.6\u00D7", label: "higher conversion on landing pages that open with a story vs. a feature list" },
        { num: "68%", label: "of what the reader recalls 48 hours later is story \u2014 not data" },
      ],
      subheading: "The AI Problem With Stories",
      bullets: [
        "AI can generate a story arc. It cannot generate the weird, specific, embarrassing detail that makes a story believable.",
        "AI defaults to the statistical average of every story it's ever read \u2014 which is exactly what \"generic\" means.",
        "Real stories have stakes, surprise, and a specific reason the reader can trust the narrator. These three things must come from you.",
      ],
    },
    {
      type: "grid",
      eyebrow: "CORE FRAMEWORKS",
      title: "3 Story Structures That Work in Copy",
      subtitle: "Pick one. Fill it in with specifics only you know. Ship.",
      items: [
        { num: "01", title: "Before-After-Bridge (BAB)", desc: "Paint the painful now. Paint the desirable after. Name the specific mechanism that bridges them.", icon: "\u{1F309}" },
        { num: "02", title: "Simplified Hero's Journey", desc: "Ordinary world \u2192 challenge \u2192 struggle \u2192 discovery \u2192 new world. The reader is the hero; you're the guide.", icon: "\u2694\uFE0F" },
        { num: "03", title: "Star-Story-Solution (SSS)", desc: "Star (the hero / customer) \u2022 Story (the tension they faced) \u2022 Solution (how it resolved). Case-study workhorse.", icon: "\u2B50" },
      ],
      footer: "All three structures are free. The specificity inside them is not.",
    },
    {
      type: "principle",
      num: "01",
      title: "Before-After-Bridge \u2014 The Workhorse Structure",
      intro: "BAB is the most-used structure in high-converting long-form copy because it matches how a reader thinks: they feel the pain, want the outcome, and need to believe in the mechanism that connects the two.",
      sectionTitle: "The Three Sections \u2014 And What They Must Contain",
      sections: [
        { heading: "Before \u2014 Name the specific pain", example: '"Your AEs waste 11 hrs/week rekeying CRM notes. Half your pipeline data is stale by Friday."', note: "Vague pain (\"inefficient workflow\") loses. Quantified, role-specific pain lands." },
        { heading: "After \u2014 Paint the concrete outcome", example: '"CRM updates itself. Your Monday pipeline review starts with fresh numbers, not Slack threads."', note: "Avoid aspirational adjectives. Describe a real Monday morning, not a dream." },
        { heading: "Bridge \u2014 Name the mechanism", example: '"Our Gmail plugin auto-logs every reply, updates stages by keyword, and syncs to HubSpot in 4 seconds."', note: "This is where AI goes vague (\"our solution\"). You name the exact how." },
      ],
      rule: "If your Bridge could describe any competitor, rewrite it until it can't.",
    },
    {
      type: "comparison",
      eyebrow: "AI vs HUMAN",
      title: "Same Customer Story \u2014 Two Versions",
      subtitle: "The AI version has the structure. The human version has the texture that makes the structure land.",
      left: {
        title: "AI-Generated Story",
        color: "#EF4444",
        items: [
          { strong: '"Our customer, a growing SaaS company, struggled with inefficient workflows."', note: "Who? How big? What workflow? The reader can't picture anything." },
          { strong: '"After implementing our solution, they saw significant improvements."', note: "\"Significant\" is the tell. It means nothing." },
          { strong: '"The team was able to focus on what really matters: their customers."', note: "Cliché ending. Could appear in literally any case study." },
        ],
      },
      right: {
        title: "Human-Written Story (Winner \u2605)",
        color: "#10B981",
        items: [
          { strong: '"Clara is VP of Sales at a 40-person Series B. Her team of 11 AEs used to spend the last hour of every Friday updating Salesforce \u2014 and getting it wrong."', note: "Named character. Named role. Named company size. Specific scene." },
          { strong: '"After 6 weeks: 0 Friday updates. Pipeline accuracy up from 63% to 94%. Clara won her Q3 forecast bet."', note: "Exact numbers. Personal stake. One weird specific (\u201Cforecast bet\u201D) that could only be real." },
          { strong: "\"\u2018I finally stopped having Sunday night dread about Monday\u2019s 1:1s,\u2019 Clara says.\"", note: "Direct quote with a surprising emotional detail. AI will not write \"Sunday night dread.\"" },
        ],
      },
      footer: "Both stories use the same frame. Only one is readable. The difference is ~20 minutes of reporting and zero extra words.",
    },
    {
      type: "principle",
      num: "02",
      title: "Sensory Detail \u2014 The Fastest Trust Signal",
      intro: "AI averages language. Human stories contain odd, specific sensory detail that could only come from someone who was actually there. One good detail carries more trust than three testimonials.",
      sectionTitle: "The Four Flavours of Specific Detail",
      sections: [
        { heading: "Time-and-place detail", example: '"At 11:47pm on a Thursday, the CTO finally posted the 3,400-word Slack message."', note: "A specific timestamp signals a real memory, not a generic recap." },
        { heading: "Sensory detail", example: '"The warehouse floor was cold enough that you could see your breath."', note: "Temperature, sound, smell, texture. AI never writes these without being prompted to." },
        { heading: "Embarrassing or off-brand detail", example: '"We lost the first enterprise deal because our SOC 2 report was literally a Word doc."', note: "Vulnerability = credibility. AI is risk-averse and smooths these away." },
        { heading: "Named, specific thing", example: '"Maya from Procurement killed the deal over a missing ISO 27001 certificate."', note: "Real names, real artifacts. Generic stories don't have procurement people named Maya." },
      ],
      rule: "Every story needs at least one detail that would be embarrassing or pointless to invent. That's the trust fingerprint.",
    },
    {
      type: "table",
      title: "The Story Audit \u2014 6 Things Every Good Story Has",
      subtitle: "Run your draft through this checklist before shipping. Missing 3+ rows = rewrite.",
      columns: ["Element", "Question to Ask", "If missing, the story feels..."],
      rows: [
        ["Named hero", "Who specifically? Name, role, company size.", "Vague \u2014 could be anyone, converts no one"],
        ["Concrete stakes", "What did they stand to lose or gain? In hours, dollars, or headcount?", "Low-stakes \u2014 reader has no reason to care"],
        ["Tension or conflict", "What was the specific moment when things almost didn't work?", "Flat \u2014 reads like a press release"],
        ["Turning point", "What changed? The specific insight, tool, decision?", "Unearned \u2014 feels like marketing, not reality"],
        ["Surprising detail", "One detail that would be weird to invent.", "AI-generated \u2014 too smooth, too clean"],
        ["Specific outcome", "Numbers, dates, direct quotes \u2014 not \u201Csignificant improvement\u201D.", "Unverifiable \u2014 reader's trust stays at 0%"],
      ],
      footer: "If you can run the same story for a competitor by changing 2 words, your story is still generic.",
    },
    {
      type: "table",
      title: "Before \u2192 After \u2014 One Paragraph, Rewritten",
      subtitle: "Same story, same facts. The \"After\" column shows what 10 minutes of specificity does to a story's believability.",
      columns: ["AI-Default Draft", "Human Rewrite", "What Changed"],
      rows: [
        ["\"Our customer improved their efficiency with our platform.\"", "\"Priya's ops team at Zendesk cut ticket-triage time from 14 min to 2 min \u2014 in 3 weeks.\"", "Named person, named company, specific metric + timeframe"],
        ["\"The team was initially skeptical but came around.\"", "\"Her eng lead, Rahul, told her it was 'yet another glorified Zap.' He changed his mind in the live demo when he saw the backfill complete in 40 seconds.\"", "Named skeptic, his exact quote, the moment he changed his mind"],
        ["\"The results were impressive.\"", "\"Q3 CSAT up 8pts. Priya used the slack time to finally hire her first CX manager \u2014 the thing she'd been postponing for 2 years.\"", "Metric + personal consequence the reader can feel"],
        ["\"They continue to see success with our tool.\"", "\"Six months in: 94% of tickets auto-tagged correctly, Rahul now recommends us in his Slack communities without being asked.\"", "Durability signal + unpaid-advocate detail"],
      ],
      footer: "Every human rewrite took under 10 minutes and zero additional data. All it took was asking: \"What's the specific version of this?\"",
    },
    {
      type: "grid",
      eyebrow: "WHERE TO DEPLOY STORIES",
      title: "6 High-Leverage Places for a Story",
      subtitle: "Stories belong where the reader is about to make a commitment \u2014 not in a PDF no one reads.",
      items: [
        { num: "01", title: "Above the pricing CTA", desc: "One 3-sentence customer story right next to the buy button reduces hesitation more than any testimonial wall.", icon: "\u{1F4B3}" },
        { num: "02", title: "Email #1 of any sequence", desc: "Open with a named person, a specific tension, a turning point. Beats \u201CHi {{FirstName}}, welcome!\u201D by 3\u20135\u00D7 open rate.", icon: "\u{1F4E7}" },
        { num: "03", title: "About page", desc: "Not the founder bio. The origin story: the specific day, the embarrassing realisation, the thing that had to change.", icon: "\u{1F4D6}" },
        { num: "04", title: "Ad creative hook (first 3s)", desc: "Stories stop the scroll. \u201CI had $847 in the bank the week I launched this\u201D > \u201CDiscover our AI platform.\u201D", icon: "\u{1F3AC}" },
        { num: "05", title: "Sales deck \u2014 slide 2", desc: "Replace the company logo grid with one named customer's before-and-after. Sales reps remember stories; they forget features.", icon: "\u{1F4CA}" },
        { num: "06", title: "Support / trust pages", desc: "\u201CHere\u2019s what happened the one time we had a 3-hour outage in 2025 \u2014 including the Slack thread.\u201D Transparency builds trust AI can\u2019t fake.", icon: "\u{1F6E1}\uFE0F" },
      ],
      footer: "Rule: Every landing page should have at least one story within 150px of the primary CTA.",
    },
    {
      type: "exercise",
      title: "Story Diagnosis Challenge",
      intro: "Each draft below is an AI-generated or AI-influenced story. Identify what's missing, then rewrite using one specific real detail you could plausibly have.",
      items: [
        { num: "1", copy: '"Our customer was having trouble with their marketing and decided to try our platform. They saw great results and are very happy now."', answer: "Missing: named hero, specific pain, tension, surprising detail, quantified outcome. Fix: name the person, describe the exact day they broke, name the number that changed, end with a direct quote." },
        { num: "2", copy: '"We help businesses of all sizes streamline their operations for maximum efficiency."', answer: "There's no story at all here \u2014 just positioning. Fix: \"Last year, Tara's 12-person ops team processed 4,100 invoices by hand. This year: 41,000. Same team. Here's the one Tuesday meeting that changed everything.\"" },
        { num: "3", copy: '"The team faced various challenges but persevered and overcame them with our solution."', answer: "Zero specificity; every clause is filler. Fix: name the exact challenge (\"the Snowflake bill hit $38K in October\"), the turning point (\"the CFO gave them 14 days\"), the mechanism (\"they consolidated 6 pipelines into one DAG\"), and the outcome (\"bill was $11K in November\")." },
        { num: "4", copy: '"Our founder started the company because he saw a need in the market and wanted to help people."', answer: "Generic founding-story cliché. Fix: one specific day, one specific moment. \"On March 4th 2022, Josh got the 7th cold email that month asking how we did billing. He realised he was answering the same question over and over \u2014 that was the product.\"" },
      ],
    },
  ],
};
